reown-com/appkit

package.json

This new version of the Fortmatic SDK contains compatibility fixes for various web3 beta 1.0 versions.

update fortmatic sdk to v0.8.1

---

src/providers/index.ts

Change Nifty wallet extension name

---

README.md
src/components/Modal.tsx

Some developers may need to not show Injected providers or WalletConnect by Default (#39). By default, those are going to show but I've added props that if included it will not show the Injected Provider or WalletConnect

Disable defaults

---

src/core/connectors/portis.ts

Portis now connects directly and no additional wallet pop up is shown

fixed modal on Portis

---

package-lock.json
package.json
src/core/connectors/portis.ts

In order to enable the GasRelay on Portis, it is required to allow to send different [network & config parameters](https://docs.portis.io/#/configuration) when creating a new instance. Changes in this PR include proper interfaces to accept all Portis config params.
Portis also offer different [methods](https://docs.portis.io/#/methods?id=showportis) to control the wallet and network connection. If web3connect only returns the provider, dApp lose the access to these useful methods. To overcome this, the new Portis instance is included within the provider instance.

Enable GasRelay on Portis

---

README.md

The examples in the readme weren't working without the torus-embed import.

Fix readme, missing import for torus.

---

README.md
src/core/index.tsx
src/helpers/types.ts
src/helpers/utils.ts

Simplifying API to a single promise method called `connect()`
**Example**
```javascript
const web3Connect = new Web3Connect.Core(...options)
const provider = await web3Connect.connect();
```

add  Connect method

---

src/core/index.tsx

I don't think #150 is completely fixed by v1.6.0, as it currently only rejects the promise on an error event. Closing the dialog by clicking elsewhere on the page does not reject the promise.
I have not tested these changes locally but believe they should work

Subscribe to close event on connect and connectTo

---

example/package-lock.json
example/src/helpers/chains.ts

Fixes `ChainId missing or not supported` error when connecting to binance smart chain
@pedrouid is this correct way to set initial chain id? 
```js
const providerOptions = {
walletconnect: {
package: WalletConnectProvider,
options: {
rpc: {
56: "https://bsc-dataseed1.defibit.io/",
},
chainId: 56,
},
},
};
```
I still got chain id 1 in session request:
```json
{
"id": 1600931566732639,
"jsonrpc": "2.0",
"method": "wc_sessionRequest",
"params": [{
"peerId": "75c54fb0-edf2-4015-ab4e-40736aee584f",
"peerMeta": {
"description": "",
"url": "http://localhost:3000",
"icons": ["http://localhost:3000/favicon.ico"],
"name": "Web3Modal Example"
},
"chainId": 1
}]
}
```

Add binance smart chain to example

---

src/providers/connectors/injected.ts

Address: [#206](https://github.com/Web3Modal/web3modal/issues/206)
The injected connector is using a deprecated method as described in the metamask specs:
https://docs.metamask.io/guide/ethereum-provider.html#legacy-methods

Replace deprecated metamask API method

---

src/providers/connectors/walletconnect.ts

WalletConnect constructor misses the options for the QRCode modal

Add qrcodeModalOptions to WalletConnect

---

docs/providers/fortmatic.md

Docs only, no code changes, no compatibility break.
Fixes #371 with adding *required* network options to Fortmatic. Without these settings, Formatic will default to connecting to `localhost:8454`

README: Add required network-options for Fortmatic-provider

---

src/helpers/local.ts
src/helpers/utils.ts

When cookies are disabled, browsers (at least chromium based browser) throw an error when you try to access localStorage.
localStorage is no longer just undefined, but it triggers an error that stop web3modal from working entirely.
You can reproduce this by disabling cookies on your browser and visit https://web3modal.com you will see a white page with this error in the console: `Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`
To fix this, we can check differently with a try catch that will try to use localStorage and return true or false depending on whether it works or not.

Add a better check for localStorage availability

---

src/providers/injected/index.ts
src/providers/providers/index.ts

@TrevvvD from Coinbase requested that the copy on the Provider.name be changed from `Coinbase` to `Coinbase Wallet` 
to make it clear that users can connect with the Coinbase Wallet extension as opposed to Coinbase retail app.

update coinbase wallet copy

---

src/providers/connectors/venly.ts

Venly connector can now connect to google Facebook or twitter with authenticationOptions object passed in parameters.
This object contain idpHint, which is the social media you want to connect to

:sparkles: add authenticationOptions to venly connector options

---

packages/react/readme.md

- Fix places in readme where we reference the ethereum package when needing to
reference the react one

Clear up package name in react docs

---

docs/development.md
examples/react/.env.local.example
package.json
readme.md

Adding some dev setup instructions while I'm seeing it with fresh eyes.
Also:
- removes seemingly dead `dev:html` script

docs(readme): adds development instructions

---

packages/ui/src/utils/UiHelpers.ts

###
The default icon is shown when Exodus wallet is displayed. This PR adds Exodus wallet icon Id to the preset icon list to fetch Exodus actual icon

fix: add Exodus wallet icon

---

examples/react/next.config.js
examples/react/package.json
yarn.lock

There was some caching done within `.next` folder of react example that made following error slip by:
When repository is pulled fresh and users try to run react example, they encounter an error like this
```
error - ../../chains/ethereum/index.ts
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export type { Chain, ChainProviderFn, Connector, Provider, WebSocketProvider } from '@wagmi/core'
| export { Web3ModalEthereum } from './src/api'
| export { chains, providers } from './src/utils/wagmiTools'
``` 
After some investigation, it looks like it was happening because nextjs in `dev` mode does not transpile linked monorepo packages …

[fix] react example in dev mode

---

README.md
src/providers/injected/index.ts
src/providers/logos/rainbow.svg

- Exported `RAINBOW` injected provider metadata type
- Added Rainbow Wallet logo in `./providers/logos/`
- Updated `README` to confirm support for Rainbow's injected provider
With Rainbow injected:
With MetaMask injected:

Support for Rainbow Wallet

---

packages/ui/src/partials/w3m-balance/index.ts

If the balance is less than exactly 6 digits, w3m-balance will not show the balance correctly and `_._`
Create a new wallet account, transfer 0.01 and connect with that wallet.
In the output of the Web3Modal component, the `_._` appears in the output of the Web3Modal component.
Goerli Test net , Ethereum Main net

fix Less than 6 digits remain unchanged

---

packages/ui/src/presets/EthereumPresets.ts

Dawn Wallet (https://twitter.com/dawn_wallet) is an iOS mobile Ethereum Wallet. We are about to enter production later this week. This PR adds support for Dawn into the Web3Modal so our users can use dapps that make use of WalletConnect. We have also submitted the `cloud.walletconnect.com` application.

Add Dawn Wallet

---

packages/ui/src/utils/TemplateUtil.ts

Fixes the bug where a manually added mobile wallet doesn't appear on the wallet selection screen.

fix: manualWalletsTemplate not loading MobileWallets

---

packages/ui/src/views/w3m-wallet-explorer-view/index.ts

N/A
- feat:
- fix: reduce search threshold to 1 character to allow search wallets with just 2 chars in their names
- chore:
closes #1144

reduce search threshold to 1 character

---

packages/core/index.ts
packages/core/src/controllers/AccountController.ts
packages/core/src/controllers/NetworkController.ts
packages/core/tests/controllers/AccountController.test.ts
packages/core/tests/controllers/NetworkController.test.ts
packages/scaffold-html/index.ts
packages/scaffold-html/src/client.ts
packages/wagmi/src/client.ts

Simplified account and network controllers to where they mostly have `set` methods which are called from client implementation i.e wagmi. This means that in scaffold we just need to "react" to changes when they happen on state, will reduce logic in there substantially latter on.

[v3] Simplify and make account and network controllers reactive

---

apps/laboratory/package.json
package-lock.json
package.json
packages/core/src/controllers/AccountController.ts
packages/core/tests/controllers/AccountController.test.ts
packages/scaffold-html/src/client.ts
packages/scaffold-html/src/modal/w3m-modal/index.ts
packages/scaffold-html/src/modal/w3m-modal/styles.ts
packages/scaffold-html/src/partials/w3m-connecting-wc-desktop/index.ts
packages/scaffold-html/src/partials/w3m-connecting-wc-injected/index.ts
packages/scaffold-html/src/partials/w3m-connecting-wc-mobile/index.ts
packages/scaffold-html/src/partials/w3m-connecting-wc-web/index.ts
packages/scaffold-html/src/partials/w3m-connecting-widget/index.ts
packages/scaffold-html/src/views/w3m-account-view/index.ts
packages/scaffold-html/src/views/w3m-connecting-external-view/index.ts
packages/scaffold-html/src/views/w3m-connecting-wc-view/index.ts
packages/scaffold-html/src/views/w3m-network-switch-view/index.ts
packages/wagmi/src/client.ts

- Keyboard management
- Mobile layout
- Dependency updates
- Balance formatting
- Scroll locking
- connection widget simplification

[v3] Mobile and other improvements

---

apps/gallery/package.json
apps/laboratory/package.json
examples/react-wagmi/package.json
examples/vue-wagmi/package.json
lerna.json
package-lock.json
package.json
packages/core/package.json
packages/polyfills/package.json
packages/scaffold/package.json
packages/ui/package.json
packages/wagmi/package.json
packages/wagmi/src/client.ts
packages/wagmi/src/utils/constants.ts

N/A
- feat: `connectorImages` option allowing you to set or override connector images based on their id. Does not affect wallets fetched from web3modal api (recommended). You will only need to use this when you remove metamask that comes in the modal by default and replace it with wagmi connector. For example:
```ts
createWeb3Modal({
connectorImages: {
coinbaseWallet: 'https://images.mydapp.com/coinbase.png',
metamask: 'https://images.mydapp.com/metamask.png'
}
})
```
- chore: Update dependencies
N/A

tag 3.0.2, connectorImages option

---

packages/ui/src/components/wui-shimmer/styles.ts
packages/ui/src/composites/wui-account-button/styles.ts
packages/ui/src/composites/wui-avatar/styles.ts
packages/ui/src/composites/wui-icon-box/styles.ts
packages/ui/src/composites/wui-list-item/styles.ts
packages/ui/src/composites/wui-network-button/styles.ts
packages/ui/src/composites/wui-qr-code/styles.ts
packages/ui/src/composites/wui-tabs/styles.ts
packages/ui/src/composites/wui-transaction-visual/styles.ts
packages/ui/src/composites/wui-visual-thumbnail/styles.ts

In old versions of Safari (Mac and iOS) and Chrome (in old iOS versions) don't have the ability to shape the outline depending on the component. Instead, another approach to giving items outline is using the box-shadow property. 
- fix: replace all outline stylings with box-shadow
- [Slack conversation](https://walletconnect.slack.com/archives/C03RVH94K5K/p1700216019771239)
- [Slack conversation](https://walletconnect.slack.com/archives/C03RVH94K5K/p1700164765905539)

refactor: replace outline stylings with box shadow

---

packages/wagmi/src/connectors/EIP6963Connector.ts

Override onAccountChange function & added `this.storage?.removeItem(connectedRdnsKey)`
- feat:
- fix: EIP6963 wallets were triggered on reload when were manually disconnected, this would trigger the accountsChanged event and clear the storage without calling the overriden `disconnect` function
- chore:
closes https://github.com/WalletConnect/web3modal/issues/1488

fix: remove EIP6963 connector from localStore on account change

---

packages/ethers5/src/client.ts
packages/scaffold/src/modal/w3m-account-button/index.ts
packages/scaffold/src/views/w3m-account-view/index.ts
packages/wagmi/src/client.ts

We're accessing the network image SRC in different ways in different components. We can use custom chain images if we use `AssetUtil.getNetworkImage`. So instead of manually getting the network image, using `AssetUtil` will fix the issue linked below.
- fix: custom network image rendering
Add a map to the `createWeb3Modal` function as parameter like the following:
```js
const modal = createWeb3Modal({
...
chainImages: {
1: 'image_url...'
}
})
```
Closes https://github.com/WalletConnect/web3modal/issues/1406
Closes https://github.com/WalletConnect/web3modal/issues/1405

fix: network image access in account button and account page

---

packages/scaffold/src/partials/w3m-all-wallets-list/index.ts
packages/scaffold/src/views/w3m-connect-view/index.ts

When we set `includeWalletIds` and `featuredWalledIds` as the same array, in case people want to show only a few wallets in the wallet select page, the all wallets button and the all wallets page have a few issues:
- All wallets button shows a wrong number of wallet options on the right side. This is fixed in https://github.com/WalletConnect/web3modal/pull/1499/files but we should consider featured apps for the whole count too.
- All wallet lists should be considered if there are only featured apps. When we calculate the `count` value in `ApiController`, the `featured` wallets are not counted, but we fetch the featured ones in all wallet lists 
- In the `createWeb3Modal` function, pass the `includeWalletIds` and pass `featuredWalletIds` as the same array of Wallet id's.
- fix: all wallets …

fix: all wallets shimmer bug

---

packages/core/src/controllers/AccountController.ts
packages/core/src/utils/TypeUtil.ts
packages/ethers/src/client.ts
packages/ethers5/src/client.ts
packages/wagmi/src/client.ts

When we switch network, we don't sync the profile information. This causes displayin ENS name or avatar in all networks, which is not expected. 
(Considering you have ENS name set to your account):
- Connect wallet to Ethereum Mainnet
- See ENS name
- Switch to Avalanche
You still see the ENS name. 
- fix: sync profile on the network switch and consider not only mainnet
Closes https://github.com/WalletConnect/web3modal/issues/1407
Closes https://github.com/WalletConnect/web3modal/issues/1544
Closes https://github.com/WalletConnect/web3modal/issues/1519#issue-2018270402

fix: syncing profile info on network switch

---

.github/workflows/ui_tests.yml
.gitignore
apps/laboratory/package.json
apps/laboratory/playwright.config.ts
apps/laboratory/tests/basic-tests.spec.ts
apps/laboratory/tests/shared/constants/index.ts
apps/laboratory/tests/shared/fixtures/w3m-fixture.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tsconfig.json
dangerfile.ts
package-lock.json

teammate closed previous PR #1581  by accident and I cannot reopen it - see comments there
N/A
- feat(lab): scaffolds a basic UI test
#1582
closes #...

feat(lab): add UI tests

---

packages/scaffold/src/views/w3m-transactions-view/index.ts

With the recent changes, we removed the prop binding prefix from the `images` prop of the transaction items. This breaks the props and causes an error. Since the images are an array of string, we should use `dot` prefix.
- fix: images prop binding for `wui-transaction-list-item`

fix: use prop binding for images in transaction item components

---

packages/scaffold/src/partials/w3m-connecting-wc-qrcode/index.ts

We're currently rendering the copy link button conditionally depending on the `uri` and `ready` states. This causes a layout shift when we get these values updated. Instead of hiding the copy button, we could disable it so it'll be available at the same the the QR code is loaded
N/A
- fix: copy button causes layout shift on QR code loaded
https://walletconnect.slack.com/archives/C03RVH94K5K/p1703056394669249?thread_ts=1702956728.455579&cid=C03RVH94K5K

refactor: update copy link rendering condition

---

apps/laboratory/src/components/Ethers/EthersConnectButton.tsx
apps/laboratory/src/components/Wagmi/WagmiConnectButton.tsx
apps/laboratory/tests/basic-tests.spec.ts
apps/laboratory/tests/connect.spec.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tests/shared/pages/WalletPage.ts
apps/laboratory/tests/shared/validators/ModalValidator.ts
apps/laboratory/tests/shared/validators/WalletValidator.ts
packages/scaffold/src/modal/w3m-account-button/index.ts
packages/scaffold/src/modal/w3m-button/index.ts
packages/scaffold/src/modal/w3m-connect-button/index.ts
packages/scaffold/src/partials/w3m-connecting-wc-qrcode/index.ts
packages/scaffold/src/views/w3m-account-view/index.ts
packages/scaffold/src/views/w3m-connect-view/index.ts

- chore(ui-tests): cover sign
@chris13524 @tomiir apologies I decided to expand this PR a bit to actually introduce more coverage.

chore(ui-tests): cover sign

---

package-lock.json
packages/ethers5/package.json

In the `ethers5` package, we're using the old version of `siwe` package which is not automatically updated via Lerna CLI. Instead using asterix `*` to get the latest version in Monorepo should fix it.
- fix: update `siwe` version in ethers5 package
closes https://github.com/WalletConnect/web3modal/issues/1650
closes https://github.com/WalletConnect/web3modal/issues/1653

chore: update siwe version in optional deps list

---

packages/ui/src/composites/wui-account-button/styles.ts

N/A
- feat:
- fix: wui-account-button responsive styles. Removed balance on small screens.
- chore:
https://github.com/WalletConnect/web3modal/issues/1668

fix: account button hide balance on small device views

---

apps/laboratory/src/components/Ethers/EthersConnectButton.tsx
apps/laboratory/src/components/Wagmi/WagmiConnectButton.tsx
apps/laboratory/src/constants.ts
apps/laboratory/tests/connect.spec.ts
apps/laboratory/tests/shared/pages/WalletPage.ts
apps/laboratory/tests/shared/validators/ModalValidator.ts

We were covering successful signing. This now also covers the wallet rejecting the sign request.
- feat(ui-test): cover reject signing
closes #...

feat(ui-test): cover reject signing

---

.github/workflows/ui_tests.yml
apps/laboratory/tests/connect.spec.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
packages/scaffold/src/partials/w3m-header/index.ts
packages/scaffold/src/views/w3m-account-view/index.ts
packages/scaffold/src/views/w3m-networks-view/index.ts

Signing was already implemented and this test covers the network switching functionality in conjunction with signing on the new network
- feat(ui-test): cover switching networks
closes #...

feat(ui-test): cover switching networks

---

.github/workflows/ui_tests.yml

The work to parallelize the tests to make them faster is currently [blocked](https://github.com/WalletConnect/web3modal/pull/1682).
N/A
- feat:
- fix:
- chore:
closes #...

chore(ui-test): extend more time for tests

---

packages/scaffold/src/views/w3m-networks-view/index.ts
packages/scaffold/src/views/w3m-networks-view/styles.ts

N/A
- feat:
- fix: networks view max-height
- chore:
Closes [Peanut : Network Switching interface issue#1703](https://github.com/WalletConnect/web3modal/issues/1703)

fix: capped networks view grid height to 70vh

---

apps/laboratory/src/components/Ethers/EthersTransactionButton.tsx
packages/wallet/src/W3mFrameSchema.ts
packages/wallet/src/W3mFrameTypes.ts

N/A
- feat:
- fix: adds eth_chainId and eth_blockNumber to possible RPC call tpyes in zod, to prevent errors when ethers does intermediate rpc calls.
- chore:
- Have been able to sort out zod errors on lab side with this, but secure site needs this to be deployed in order to work.

fix: ethers send transaction

---

packages/ui/src/composites/wui-transaction-visual/styles.ts

N/A
- feat:
- fix: images tearing on activity when scrolling the view.
- chore:
- This was only happening on windows, would need a windows user to test this

fix: activity image tearing

---

packages/wagmi/src/client.ts

N/A
- fix: If the chain wasn't in config we were fetching the balance of the defaultChain or the first configured chain which is inacurated data from the current connected chain, this PR will skip the fetch of the balance and set it directly to `0.000` if the chain is not registered. 
Notice:
- We cannot fetch the balance of an unregistered chain because Wagmi function will throw an error + we don't have the symbol info to display in the UI
- We should have a UI view to show the user is on an incorrected chain
closes https://github.com/WalletConnect/web3modal/issues/1836

fix balance

---

packages/scaffold/src/modal/w3m-modal/index.ts

For some reason you have used vanilla address when CAIP one was expected. This breaks SIWE flow.
When `isConnected && newCaipAddress && this.caipAddress !== newCaipAddress` condition is checked on https://github.com/WalletConnect/web3modal/blob/V4/packages/scaffold/src/modal/w3m-modal/index.ts#L170, obviously it fails, leading to re-sign-in using SIWE.

fix: set caipAddress to caipAddress

---

.github/workflows/ui_tests.yml
apps/laboratory/playwright.config.ts
apps/laboratory/tests/shared/constants/devices.ts

We've seend often tests downloading obsolte caches. 
N/A
[- fix:](fix: cache might restore the wrong files)
closes #...

fix: cache might restore the wrong files

---

.github/workflows/ci_canary.yml
Dockerfile
apps/laboratory/package.json
apps/laboratory/playwright.config.ts
apps/laboratory/tests/canary.spec.ts

Very simple Playwright test to get full end-2-end confidence/latency metrics including:
1. Explorer API
2. Blockchain API
3. Other tools
Built successfully into ECR and tested locally
https://github.com/WalletConnect/web3modal/actions/runs/7835190121/job/21380181938
- [feat: export web3modal Canary image](https://github.com/WalletConnect/web3modal/commit/ae1cf0b7c9c8a8bc57a4897dd538d1b082c68ca0)
closes #...

feat(canary): export web3modal Canary image

---

apps/laboratory/src/utils/ConstantsUtil.ts

You can see that now `lab.web3modal.com` is passed in the metadata.
closes #...

fix(verify): passing wrong domain for Verify

---

packages/scaffold/src/views/w3m-buy-in-progress-view/index.ts

N/A
- feat:
- fix: buy in progress interval premature clear
- chore:

fix: buy in progress interval being cleared prematurely

---

packages/ethers/src/client.ts
packages/wagmi/src/client.ts
packages/wallet/src/W3mFrameProvider.ts

When we receive `FRAME_IS_CONNECTED_SUCCESS` with value isConnected set to `false` instead of `true`, we are stuck in infinite loading state

fix: infinite loader when user is not connected

---

apps/laboratory/scripts/install-brave-browser.sh

Disable man-db auto update in CI in order to reduce time it takes to finish package installation

fix: disable man-db auto update

---

packages/scaffold/src/partials/w3m-onramp-providers-footer/index.ts

N/A
- feat:
- fix:
- chore: update onramp footer copy
Closes W3M-95

chore: update onramp footer copy

---

apps/laboratory/src/components/Ethers/EthersWriteContractTest.tsx
apps/laboratory/src/components/Wagmi/WagmiWriteContractTest.tsx
apps/laboratory/src/utils/DonutContract.ts

Update donut contract so it doesn't have stock. Allows unlimited purchasing of donuts.

chore: update donut contract

---

apps/laboratory/tests/canary.spec.ts

Logs how long each step takes to help debugging long times.

chore: log canary times

---

.github/workflows/ui_tests.yml
apps/laboratory/.env.example
packages/wallet/src/W3mFrameConstants.ts

Add an option to configure secure site url so we can implement automated tests for the secure site

chore: configurable secure url

---

apps/laboratory/package.json
apps/laboratory/tests/shared/fixtures/w3m-email-fixture.ts
apps/laboratory/tests/shared/pages/DeviceRegistrationPage.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tests/shared/utils/project.ts
dangerfile.ts

- Add email test command
- Add additional checks 
- Add test project to dangerfile

fix: email tests

---

.github/workflows/ui_tests.yml
apps/laboratory/tests/email.spec.ts
apps/laboratory/tests/shared/fixtures/w3m-email-fixture.ts
apps/laboratory/tests/shared/fixtures/w3m-smart-account-fixture.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tests/shared/pages/ModalWalletPage.ts
apps/laboratory/tests/shared/validators/ModalWalletValidator.ts
apps/laboratory/tests/smart-account.spec.ts
packages/core/src/controllers/NetworkController.ts
packages/core/tests/controllers/ConnectorController.test.ts
packages/core/tests/controllers/NetworkController.test.ts
packages/ethers/src/client.ts

N/A
- feat:
- fix: ethers `disconnect` not being awaited. Issue where a SA user could disconnect, connect with a non-enabled account and SA flow would be prompted due to network being enabled, ending in error.
- chore: add corresponding UI test and controller test. Add disconnect UI test.

fix: reset sa enabled networks

---

Dockerfile.canary
apps/laboratory/tests/canary.spec.ts
apps/laboratory/tests/shared/fixtures/w3m-fixture.ts
apps/laboratory/tests/shared/fixtures/w3m-wallet-fixture.ts
apps/laboratory/tests/shared/utils/logs.ts

Logs (console.time) are now optional and turned off by default

chore: add conditional logs for canary

---

packages/wagmi/src/client.ts

N/A
- feat:
- fix: issue where email connector would re subscribe to rpc callbacks on connectors sync and cause multiple responses to be executed
- chore:

fix: do not sync rpc callbacks multiple times

---

apps/laboratory/tests/shared/validators/ModalValidator.ts
packages/ethers/src/client.ts

N/A
- feat:
- fix: "Failed to disconnect" error on ethers + relay connections
- chore:
Email provider does not implement `emit` which  was being fired after disconnection. This caused the client to actually disconnect, but throw an error causing desync in the UI and an error popup.
Tests were not capturing this because the UI kept the modal open and the button in loading state so "account button" was never displayed. Updated it to expect to see the connect button instead

fix: ethers fail to disconnect

---

packages/common/src/utils/TypeUtil.ts
packages/core/src/utils/CoreHelperUtil.ts

N/A
- fix: issue where wallet balance would show NaN when having scam tokens without a `value`.

fix: NaN balance 

---

apps/laboratory/tests/shared/utils/project.ts

Solana E2E has a regression issue while disconnecting and signing messages. This is not reproducible while testing manually and is highly possibly related to a state issue between UI and the connector status. 
The Solana team currently investigating this. While we work with other features, let's unblock our team and continue without Solana tests for now since we didn't launch Solana yet.

chore: disable wallet tests for solana temporary

---

apps/laboratory/tests/shared/fixtures/w3m-smart-account-fixture.ts
apps/laboratory/tests/shared/pages/ModalWalletPage.ts
apps/laboratory/tests/shared/validators/ModalWalletValidator.ts
apps/laboratory/tests/smart-account.spec.ts

N/A
- chore: refactor SA tests to prevent using fixed ids which were causing issues when ran from different environments with different keys.
- chore: unpack `openSettings` and other utils into single actions to allow for more flexible testing

chore: remove fixed addresses from SA tests

---

packages/ethers/src/client.ts
packages/ethers5/src/client.ts
packages/wagmi/src/client.ts

N/A
- feat:
- fix: Web3Modal was calling the SIWE's signOut function twice.
the signOut function from SIWE is already called internally in [`scaffold/src/modal/w3m-modal`](https://github.com/WalletConnect/web3modal/blob/0478feb5b420c2eefcadd3410f97e2d8bffbbecf/packages/scaffold/src/modal/w3m-modal/index.ts#L181)
Context: https://walletconnect.slack.com/archives/C03RVH94K5K/p1713282453076899
- chore:
closes #...

remove siwe signOut function on high level packages

---

apps/laboratory/src/components/Solana/SolanaWriteContractTest.tsx
apps/laboratory/tests/email.spec.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tests/shared/validators/ModalValidator.ts
apps/laboratory/tests/wallet.spec.ts

N/A
Fixes isssue where switch network test would have flaky behavior due to the modal being closed too quickly, causing following modal openings to close prematurely. 
Modified the test to better reflect user flow by expecting the screen to return to account view and show the apropiate network.

fix: switch network test flakyness

---

apps/laboratory/tests/email.spec.ts
apps/laboratory/tests/shared/fixtures/w3m-smart-account-fixture.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tests/smart-account.spec.ts

We have fadeout animation of the modal. In some test scenarios, are opening the approved transaction page right after we close the modal. If we do this without waiting for the main modal to be closed, this goes into a state where the overlay does not disappear.
This PR introduces some optimizations to our timeouts and add the timeout for the fade out animation only and removes other extra timeouts from tests.

fix: e2e test decrease timeouts

---

Dockerfile.canary
apps/laboratory/docker-canary.sh

N/A
- chore: fixes that /usr/bin/env wasn't in the canary Docker image and fix canary script name
N/A

chore: don't use /usr/bin/env

---

apps/laboratory/tests/email.spec.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tests/shared/utils/email.ts

Reuse same set of emails for tests. Introduce offset for email change emails. Number of emails we consume is currently `numberOfWorkers * 2` (16 at the moment)

fix: don't use random emails in tests

---

apps/laboratory/public/.well-known/apple-app-site-association

Add `.well-known/apple-app-site-association` to Lab for testing purposes of mobile clients

chore: add apple app site association

---

apps/laboratory/next.config.js

`apple-app-site-association` didn't have `application/json` content type

fix: apple-app-site-association content type header

---

packages/ethers/src/client.ts

N/A
- feat:
- fix: ethers not using pre-selected network and defaulting to mainnet on email
- chore:

fix: ethers email defaults mainnet

---

packages/common/src/utils/DateUtil.ts

As we any other modules we are exporting, we need to add `.js` extension for one of the modules from `dayjs`.

fix: add extension for locale import from dayjs

---

packages/ethers/src/client.ts
packages/ethers5/src/client.ts

web3modal/ethers & web3modal/ethers5 were sending `personal_sign` payloads as plain text instead of hex

fix: encodes all `personal_sign` messages to hex

---

apps/laboratory/tests/siwe.spec.ts

N/A
- feat:
- fix:
- chore:
Siwe tests were expecting legacy two-click-auth and started to fail once one-click-auth is in the main web wallet

fix: siwe tests for 1 click auth

---

apps/gallery/stories/composites/wui-account-button.stories.ts
apps/gallery/stories/composites/wui-profile-button.stories.ts
packages/scaffold/src/modal/w3m-account-button/index.ts
packages/scaffold/src/partials/w3m-account-wallet-features-widget/index.ts
packages/ui/src/composites/wui-account-button/index.ts
packages/ui/src/composites/wui-profile-button/index.ts

When we have profile name, the `wui-account-button` makes conditional truncating by `isProfileButton` but it's not rendering the name properly. This PR introduces refactors to `wui-profile-button` and `wui-account-button` components to render profile name if it exists and make required truncating

refactor: update profile name rendering logic

---

packages/siwe/scaffold/views/w3m-connecting-siwe-view/index.ts

SIWE modal have old version of styles. Size and border radius props needs to be updated.
| Column 1 Header | Column 2 Header |
|-----------------|-----------------|
| <img width="200" alt="Screenshot 2024-05-28 at 11 02 45" src="https://github.com/WalletConnect/web3modal/assets/19428358/31b8ba93-997f-48fd-9c8b-95ebdcbdcef7">  | <img width="200" alt="Screenshot 2024-05-28 at 11 06 53" src="https://github.com/WalletConnect/web3modal/assets/19428358/0bb63adc-64f2-42b8-a833-a934e2300ad0">  |

chore: update siwe action button props

---

renovate.json

- chore: fix renovate config to use matchFileNames
This configuration was tested [here](https://github.com/chris13524/web3modal/pulls)

chore: fix renovate matchFileNames

---

packages/ethers/src/client.ts
packages/scaffold-utils/src/PresetsUtil.ts

N/A
When Coinbase Wallet extension is installed, Coinbase shows up twice in ethers.
Also, wagmi did not trigger connection flow when clicking on Coinbase connector from the "All wallets" list. 
- feat:
- fix: filter cb connector on ethers. Add explorer ID for coinbase sdk connector
- chore:

fix: coinbase connector issues

---

apps/laboratory/src/components/Ethers/EthersModalInfo.tsx
apps/laboratory/src/components/Wagmi/WagmiModalInfo.tsx
apps/laboratory/src/components/Web3ModalInfo.tsx
apps/laboratory/src/pages/library/ethers-all.tsx
apps/laboratory/src/pages/library/ethers-siwe.tsx
apps/laboratory/src/pages/library/wagmi-all.tsx
apps/laboratory/src/pages/library/wagmi-siwe.tsx

N/A
- feat:
- fix:
- chore: adds relay clientId (when applicable) to connection information in lab

chore: add clientId to web3modal info

---

packages/scaffold/src/modal/w3m-modal/index.ts

When we open the modal, we are disabling scroll and pointer events for both `html` and `body`. This causing some issues if you use absolute or sticky styling in one of the elements under the `body` tag. 
See examples: 
- Wagmi website: https://1.x.wagmi.sh/examples/connect-wallet
- Go to link
- Select WalletConnect modal
- See the layout is shifting
Most of the primitive UI libraries (like [Radix](https://www.radix-ui.com/primitives/docs/components/dialog#dialog)) 
locking only `body`, not `html`. When building web page, it's generally an anti-pattern to override `html` tag's overflow or positioning props. So our modal should follow the same pattern and let users have sticky positioned elements work better along with web3modal.
- fixes …

refactor: update scroll lock stylings

---

apps/laboratory/src/components/Wagmi/WagmiModalInfo.tsx
apps/laboratory/src/pages/library/wagmi-all.tsx
apps/laboratory/src/pages/library/wagmi-email.tsx
apps/laboratory/src/pages/library/wagmi-siwe.tsx
apps/laboratory/src/pages/library/wagmi-wallet.tsx
apps/laboratory/src/pages/library/wagmi.tsx
apps/laboratory/src/utils/WagmiConstants.ts

N/A
Relay connections were being established twice because we were initializing an instance of wagmi config for email and another for default.
Change the way we structure our default configs so that `createDefaultWagmiConfig` is called a single time, instantiating connectors a single time.

fix: wagmiconfig being created twice causeing multiple relay requests

---

apps/laboratory/tests/shared/utils/email.ts
apps/laboratory/tests/smart-account.spec.ts

N/A
- feat:
- fix: remove unallowed test  for smart accounts
- chore:

fix: remove unallowed address sa test

---

renovate.json

- Renovatebot will by default auto rebase all open renovate PRs when the base branch is updated.
- This is causing Vercel build cascades that cause long queue times unnecessarily for more important builds.
- We already use this rule here: https://github.com/WalletConnect/web-examples/blob/main/renovate.json#L10

chore(renovate): only auto rebase renovate PRs when conflicted

---

apps/laboratory/src/components/Wagmi/WagmiModalInfo.tsx
apps/laboratory/tests/siwe.spec.ts
packages/core/src/controllers/NetworkController.ts
packages/scaffold/src/modal/w3m-modal/index.ts
packages/scaffold/src/utils/NetworkUtil.ts
packages/scaffold/src/views/w3m-network-switch-view/index.ts
packages/scaffold/src/views/w3m-networks-view/index.ts
packages/scaffold/src/views/w3m-unsupported-chain-view/index.ts
packages/wallet/src/W3mFrameProvider.ts

Fix issue where an integration with `signOutOnNetworkChange: false` would get stuck on the loading modal after switching in the wallet. 
- feat:
- fix: close modal if there's no need to re-auth SIWE
- chore:
closes #APKT-596

fix: close modal if no need to reauth

---

apps/laboratory/src/pages/library/ethers.tsx
packages/core/src/controllers/OptionsController.ts
packages/ethers/src/client.ts
packages/ethers5/src/client.ts
packages/scaffold-ui/src/partials/w3m-connect-featured-widget/index.ts
packages/scaffold-ui/src/partials/w3m-connect-recommended-widget/index.ts
packages/scaffold-ui/src/partials/w3m-connector-list/index.ts
packages/scaffold-ui/src/utils/WalletUtil.ts
packages/scaffold/src/client.ts
packages/wagmi/src/client.ts

If `enableEIP6963` was set to false, all other connectors wouldn't work, including wallets fetched from the API in web browser contexts. When utilizing the flags to include wallets from the API, these fetched wallets would show but have no underlying connector on web contexts, causing an unusable state.
This PR makes it so connectors are always initialized, but they are not shown if the flag is set to false. This way, they are readily available to be used as transport for api fetched wallets.
- chore: refactor flow to have 6963 wallets available but hidden
- fix: issue on recommended, recent and featured connect wallet widgets where connector would not be used even if present

feat: includeWalletIds mapping to RDNS if 6963 is disabled

---

apps/laboratory/src/components/Wagmi/WagmiGetCallsStatusTest.tsx
apps/laboratory/src/components/Wagmi/WagmiSendCallsTest.tsx
apps/laboratory/src/components/Wagmi/WagmiSendCallsWithPaymasterServiceTest.tsx
packages/scaffold/src/client.ts
packages/wagmi/src/client.ts

This PR is changing the `syncAccount` function over wagmi `Web3Modal` client to not allow the account data to be fetched twice for the same CAIP. This fixes the issue with account data being fetched multiple times between wagmi's `watchAccount` onChange callbacks.
Edit: This PR doesn't contain test coverage because the testing setup is a wip being done by @enesozturk.
APKT-684
The change can be seen on [here](https://web3modal-laboratory-git-fix-multiple-acc-b5c937-walletconnect1.vercel.app/library/wagmi/) compared to [live](https://lab.web3modal.com/library/wagmi/), when the account is connected and you refresh the page it updates a single the account info a single time.

fix: not allow multiple account syncs for same caip address

---

apps/laboratory/tests/shared/pages/WalletPage.ts
apps/laboratory/tests/shared/validators/ModalValidator.ts
apps/laboratory/tests/wallet.spec.ts
packages/core/src/controllers/NetworkController.ts

This PR readds the modal opening when there is a change in the wallet for a network that is not supported by the app.
Closes APKT-694
closes #2518
https://github.com/user-attachments/assets/1fb93534-3f47-475b-8147-d6fd827710b3

fix: missing network not supported modal on wallet network switch

---

packages/scaffold-ui/src/partials/w3m-connecting-wc-desktop/index.ts
packages/scaffold-ui/src/partials/w3m-connecting-wc-qrcode/index.ts

Removes excessive delay to display QR codes. Seems like a `setTimeout(..., 0)` is required for the WalletConnect button case as without it the resizing animation is delayed and there are svg errors for some reason. This issue isn't on the desktop QR.

fix: remove 200ms QR delay

---

packages/wagmi/src/utils/defaultWagmiCoreConfig.ts

We [previously refactored](https://github.com/WalletConnect/web3modal/pull/2119/files#diff-b8b34b308c4640de370e32093cd7f927efbf66d70cf48c397a0f3dfb5af7d228R44) our logic to create `transports` array for `wagmi`, to use `chain` object directly instead of `chain.id` in the `defaultWagmiReactConfig.ts`. But we still use `chain.id` in the `defaultWagmiCoreConfig.ts`. Wagmi is looking for chainID while mapping the transport objects, as could be seen in any dApp that uses our package `>=5.0.6`:
```sh
TypeError: rest.transports[chainId] is not a function
at Object.transport (createConfig.js:121:66)
at createClient (createClient.js:15:51)
at Object.getClient (createConfig.js:115:72)
```
This PR introduces changes to revert this back.  …

refactor: use chain id for the transports array mapping

---

apps/laboratory/src/components/Solana/SolanaSendTransactionTest.tsx

Enable sign and send versioned transactions on `/solana`

fix: remove limitation on sending versioned tx

---

apps/laboratory/tests/shared/pages/ModalWalletPage.ts
apps/laboratory/tests/shared/validators/ModalValidator.ts
apps/laboratory/tests/wallet-features.spec.ts
packages/scaffold-ui/src/modal/w3m-router/index.ts
packages/scaffold-ui/src/views/w3m-register-account-name-view/index.ts
packages/ui/src/composites/wui-input-text/index.ts

Add missing screens for ENS names in `w3m-router`. Introduces test for checking account name.
For Linear issues: Closes APKT-835

refactor: fix missing ens screens

---

packages/scaffold-ui/src/partials/w3m-activity-list/index.ts
packages/scaffold-ui/src/partials/w3m-onramp-activity-item/index.ts
packages/scaffold-ui/src/partials/w3m-onramp-provider-item/index.ts
packages/ui/index.ts

In the `scaffold-ui` which have dependency of `ui` package, we are importing some type definitions by using the full path, which we shouldn't do due to resolving modules. This PR introduces changes to import paths. 
For Linear issues: Closes APKT-844

fix: import types from the package root in partials

---

renovate.json

- Include `examples` path since these are [ignored by default](https://docs.renovatebot.com/presets-default/#ignoremodulesandtests)
- Group related and possibly dependent dependencies together in the same PR
- Apply recommended schema migration:
```
WARN: Config migration necessary
"oldConfig": {
"$schema": "https://docs.renovatebot.com/renovate-schema.json",
"extends": [
"config:best-practices",
":prConcurrentLimit10",
":prHourlyLimit2",
":semanticCommits",
":semanticCommitScope(deps)"
],
"rebaseWhen": "conflicted",
"packageRules": [
{"matchPackagePatterns": ["*"], "enabled": false},
{
"enabled": true,
"matchPackageNames": [
"@walletconnect/ethereum-provider",
"@walletconnect/universal-provider",
"@walletconnect/utils",
"@wagmi/core",
"wagmi",
"@wagmi/connectors",
"viem",
"ethers", …
```

chore: renovate updates

---

apps/laboratory/tests/metamask.spec.ts
packages/solana/src/utils/wallet-standard/watchStandard.ts

Wallet Standard's `on` listener is not getting triggered when MM is disabled but other extensions like Trust or Phantom is enabled. This causing an issue that the none of the injected wallets are getting visible in connector list if MM is not installed or disabled. 
This PR introduces a slight changes to the `watchStandard` method to make sure it's passing the available options to it's `callback` parameter. 
Also adding a tests that checks the MM option in the injected connectors list.
While this resolving the issue, like to double checking the issue with the Wallet Standard team here: https://github.com/wallet-standard/wallet-standard/issues/109
For Linear issues: Closes APKT-845
If …

fix(solana): injected connectors not detected

---

renovate.json

The previous PR (https://github.com/WalletConnect/web3modal/pull/2673) used `includePaths` but this resulted in ignoring all paths that weren't `examples`.
Instead overriding the [default `ignorePaths`](https://docs.renovatebot.com/presets-default/#ignoremodulesandtests) to not include `examples` from the ignore list.

chore: fix renovate includePaths

---

.github/workflows/pr_checks.yml
examples/react-wagmi/package.json
examples/react-wagmi/vite.config.js
package.json
pnpm-lock.yaml

Adding a workflow to compare bundle size difference between the base branch and the current branch
Example of the comment in https://github.com/WalletConnect/web3modal/pull/2696

feat: add bundle size check

---

packages/siwe/exports/index.ts

In our SIWE package, we are exporting the type definitions but this is handled manually by importing them all and exporting again. This might lead to missing some type definitions to be exported, like we did for `SIWEMessageArgs`. This PR introducing slight improvements to SIWE type exports.

refactor: export missing type defs from siwe package

---

apps/laboratory/src/components/Solana/SolanaWriteContractTest.tsx
packages/solana/src/client.ts
packages/solana/src/providers/WalletConnectProvider.ts
packages/solana/src/providers/WalletStandardProvider.ts
packages/solana/src/utils/scaffold/SolanaHelpersUtils.ts
packages/solana/src/utils/scaffold/SolanaTypesUtil.ts
packages/solana/tests/GenericProvider.test.ts
packages/solana/tests/WalletConnectProvider.test.ts
packages/solana/tests/WalletStandardProvider.test.ts
packages/solana/tests/mocks/Transaction.ts
packages/solana/tests/mocks/UniversalProvider.ts
packages/solana/tests/mocks/WalletStandard.ts
packages/solana/tests/util/TestConstants.ts

This PR brings somes fixes after a QA round of tests:
- Correct handling of available chains by wallet;
- Improved parsing of deprecated chains;
- Fix for `SolanaWriteContractTest`;
- Bring back previous base64 encoding of the transaction as described in our RPC specs.

fix: solana qa round

---

apps/laboratory/package.json
packages/ethers/package.json
packages/ethers5/package.json
packages/siwe/package.json
packages/wagmi/package.json
pnpm-lock.yaml

Rolls back `utils` and `ethereum-provider` packages to 2.14.0 since 2.15.0 introduced an issue with `rollup` builds
For Linear issues: Closes APKT-894

chore: rollback utils and ethereum-provider packages to 2.14.0

---

apps/laboratory/src/pages/library/ethers.tsx
apps/laboratory/src/pages/library/ethers5.tsx
apps/laboratory/src/pages/library/solana.tsx
apps/laboratory/src/pages/library/wagmi.tsx
packages/base/src/client.ts
packages/base/utils/TypesUtil.ts
packages/core/src/controllers/EnsController.ts
packages/core/src/controllers/NetworkController.ts
packages/ethers/exports/index.ts
packages/ethers/exports/react.tsx
packages/ethers/exports/vue.ts
packages/ethers5/exports/index.ts
packages/ethers5/exports/react.tsx
packages/ethers5/exports/vue.ts
packages/solana/exports/index.ts
packages/solana/exports/options.ts
packages/solana/exports/react.tsx
packages/solana/exports/vue.ts
packages/wagmi/exports/index.ts
packages/wagmi/exports/react/index.ts
packages/wagmi/exports/vue.ts

We have different clients (wagmi|ethers|solana) and each have different type of chain object. In the old architecture, we were casting them to our internal `CaipNetwork` object and was using. While switching to new architecture, this logic is missed. 
It's required to pass the casted object to the AppKit from the adapters. This PR introduces changes to fix this issue by updating the backwards compatible packages' exports and pass `defaultChain` value to `AppKit` instance.
The reason we are doing this is that, inside of the adapters, the `defaultChain` value is turned to `CaipNetwork`, on the adapter's constructors, like the following:
```js
this.defaultChain = getCaipDefaultChain(defaultChain)
```
If there is a UI change …

fix: defaultChain option setting to base

---

packages/scaffold-ui/src/partials/w3m-input-address/styles.ts
packages/scaffold-ui/src/views/w3m-wallet-send-view/styles.ts

Currently it's almost impossible to press send address field on iOS. You have to click on borders / edges to be able to type on the input.
For Linear issues: Closes APKT-932

fix: impossible to press on send placeholder input on mobile

---

packages/core/src/controllers/BlockchainApiController.ts
packages/core/src/controllers/TransactionsController.ts
packages/core/src/utils/TypeUtil.ts
packages/core/tests/controllers/TransactionsController.test.ts

Adds missing `chainId` param for BlockchainApiController transactions request.

fix: add missing chainId param for transactions request

---

apps/laboratory/tests/shared/utils/project.ts
examples/react-ethers5/src/App.tsx
examples/react-solana/src/App.tsx
examples/react-wagmi/src/App.tsx
packages/base/adapters/evm/ethers/client.ts
packages/base/adapters/evm/ethers5/client.ts
packages/base/adapters/evm/wagmi/client.ts
packages/base/adapters/solana/web3js/client.ts
packages/core/src/controllers/NetworkController.ts
packages/scaffold-ui/src/modal/w3m-account-button/index.ts
packages/scaffold-ui/src/modal/w3m-network-button/index.ts
packages/scaffold-utils/src/ethers/EthersHelpersUtil.ts
packages/scaffold-utils/src/solana/SolanaHelpersUtils.ts

In the ethers/ethers5/solana adapters, we are not setting the default caip network when users pass chain object to `defaultChain` parameter for the `createWeb3Modal`. 
Besides, fixes a few other things:
- Due to multi-chain architecture, `checkIfSupportedNetwork` is running false since the requested caip networks are false at first (before adapters initialized). This causing users to see `Unsupported Network` page when they open the AppKit for the first time.
- We are rendering the network image before the network image is being fetched. Thus, the network image is getting empty. Added event listeners of `AssetsController` and update the network image when they are stored. 
If there is a UI change include the screenshots with …

fix: logics to set default chain

---

apps/laboratory/next.config.mjs

- Adds `NEXT_PUBLIC_SECURE_SITE_SDK_URL` to  CSP `frame-src` field to allow for secure-site previews to be injected into lab when being called from e2e workflows

chore: add NEXT_PUBLIC_SECURE_SITE_SDK_URL to CSP

---

apps/laboratory/src/utils/ConstantsUtil.ts

For some reason custom `NEXT_PUBLIC_VERCEL_URL` environment variables were being ignored. This uses a different variable that isn't automatically set by Vercel.

chore: fix public URL

---

packages/core/src/controllers/BlockchainApiController.ts

- forwards `apiVersion: 2` query parameter to blockchain API making it respond `[]` instead of `HTTP 404` for addresses without names or unregistered names.
For Linear issues: Closes APKT-1012

chore: use apiVersion v2 on names endpoint

---

packages/core/src/controllers/AccountController.ts
packages/core/src/controllers/ChainController.ts
packages/core/src/controllers/EnsController.ts
packages/core/src/controllers/SwapController.ts

Currently most of imports are from valtio vanilla, but these are the only ones that are left out that are problematic to projects that don't need to have react in their dependencies.
This PR aims to fix that.
adds `/vanilla` to import paths where applicable

fix: import valtio from vanilla path

---

apps/laboratory/src/pages/library/solana.tsx
packages/base/adapters/solana/web3js/client.ts

Fix the logic for setting default chain id over Solana client.

fix: solana default chain logic

---

packages/base/adapters/solana/web3js/providers/WalletConnectProvider.ts
packages/base/adapters/solana/web3js/tests/WalletConnectProvider.test.ts

This PR is adding a fallback for `accounts` param when connecting to Solana with `WalletConnectProvider` and the session `chains` param is not available. 

fix: fallback to account chains to get session chains

---

packages/base/adapters/solana/web3js/client.ts
packages/base/adapters/solana/web3js/providers/CoinbaseWalletProvider.ts
packages/base/adapters/solana/web3js/tests/GenericProvider.test.ts
packages/base/adapters/solana/web3js/tests/mocks/CoinbaseWallet.ts

This PR is adding `CoinbaseWalletProvider` for allowing coinbase extension to work on Solana
For Linear issues: Closes APKT-1132

feat: add CoinbaseWalletProvider for solana

---

.changeset/nasty-rats-destroy.md
.changeset/two-cats-wave.md
apps/laboratory/next.config.mjs
packages/adapters/ethers/src/client.ts
packages/adapters/ethers/src/tests/mocks/AuthConnector.ts
packages/adapters/ethers5/src/client.ts
packages/adapters/ethers5/src/tests/mocks/AuthConnector.ts
packages/adapters/solana/src/providers/AuthProvider.ts
packages/adapters/solana/src/tests/mocks/AuthConnector.ts
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts
packages/core/src/controllers/ConnectorController.ts
packages/core/tests/controllers/ConnectorController.test.ts
packages/wallet/src/W3mFrameProvider.ts

- Fixes issue on wagmi + solana where wagmi auth provider was not properly merged to a multichain connector.
- Fixes wagmi's authConnector name to `w3mAuth`
- Makes type stay as `AUTH` so that it's recognized by the UI
- Amends `getAuthConnector`
- Fixes issue where wagmi would not reconnect automatically when `isConnected = true` 
Supersedes https://github.com/reown-com/appkit/pull/2876
For Linear issues: Closes APKT-1131

fix: wagmi provider not properly merged and reconnection

---

.github/workflows/pr_checks.yml

chore: add danger step enabled on workflows

---

.changeset/polite-dogs-search.md
packages/scaffold-ui/src/utils/WalletUtil.ts

- Non-announced connectors were being filtered as duplicates even when they are not present on the screen in the first place.
- Adds fix to only filter announced/injected connectors
For Linear issues: Closes APKT-1072

fix: non announced connectors filtered as repeated

---

.changeset/selfish-books-applaud.md
apps/laboratory/tests/shared/utils/validation.ts
packages/adapters/ethers5/src/client.ts
packages/appkit/src/client.ts
packages/appkit/src/tests/appkit.test.ts
packages/appkit/src/universal-adapter/client.ts
packages/common/src/utils/SafeLocalStorage.ts
packages/core/src/controllers/AccountController.ts
packages/core/src/controllers/ChainController.ts
packages/core/src/utils/StorageUtil.ts
packages/core/tests/controllers/AccountController.test.ts
packages/core/tests/controllers/ChainController.test.ts
packages/core/tests/utils/StorageUtil.test.ts
packages/scaffold-ui/src/views/w3m-select-addresses-view/index.ts

After connecting with a wallet on mobile deeplinks will fail when trying to sign a message or tx. 
This is happening because [this.appkit.getIsConnectedState()](https://github.com/reown-com/appkit/blob/main/packages/appkit/src/universal-adapter/client.ts#L517) is always `false`.
For Linear issues: Closes APKT-1133

fix: deeplinks not working

---

packages/core/src/utils/TypeUtil.ts
packages/scaffold-ui/src/partials/w3m-connecting-wc-mobile/index.ts

Adds error event message when there is an issue while parsing the deeplink URL in `w3m-connecting-wc-mobile` component.

chore: add connect proxy error event

---

packages/base/adapters/solana/web3js/providers/WalletConnectProvider.ts
packages/base/adapters/solana/web3js/providers/shared/Errors.ts
packages/base/adapters/solana/web3js/tests/WalletConnectProvider.test.ts
packages/base/adapters/solana/web3js/tests/mocks/UniversalProvider.ts

- Adds batched call for `solana_signAllTransactions` RPC call on Solana WalletConnectProvider;
- Updates logic of parallel requests to chained when falling back to `solana_signTransaction` for `signAllTransactions` call.

feat: solana sign all transactions

---

.changeset/eighty-brooms-poke.md
packages/adapters/solana/src/providers/WalletConnectProvider.ts
packages/adapters/solana/src/providers/shared/Errors.ts
packages/adapters/solana/src/tests/WalletConnectProvider.test.ts
packages/adapters/solana/src/tests/mocks/UniversalProvider.ts

This PR is referent of #2915 (V5) for Reown.
- Adds batched call for `solana_signAllTransactions` RPC call on Solana WalletConnectProvider;
- Updates logic of parallel requests to chained when falling back to `solana_signTransaction` for `signAllTransactions` call.

feat: add implementation for solana_signAllTransactions rpc request

---

apps/laboratory/tests/shared/pages/WalletPage.ts
apps/laboratory/tests/shared/validators/ModalValidator.ts
apps/laboratory/tests/wallet.spec.ts
packages/scaffold-ui/src/partials/w3m-account-default-widget/index.ts

Removing multi-account screen when one account connected.
For Linear issues: Closes APKT-1042

fix: show single account screen if one account connected

---

packages/base/adapters/solana/web3js/providers/WalletConnectProvider.ts
packages/base/adapters/solana/web3js/tests/mocks/UniversalProvider.ts

Changes `base58` encoding from Solana WalletConnectProvider responses to `base64`.

fix: v5 solana walletconnetprovider response encoding

---

apps/laboratory/src/pages/library/solana-no-email.tsx
apps/laboratory/src/pages/library/solana-no-socials.tsx
apps/laboratory/src/pages/library/solana.tsx
packages/base/src/client.ts
packages/core/src/controllers/ApiController.ts
packages/core/src/controllers/OptionsController.ts
packages/core/src/utils/ConstantsUtil.ts
packages/core/tests/controllers/ApiController.test.ts
packages/core/tests/controllers/OptionsController.test.ts

This PR sets default AppKit options into a constant and changes `enableAnalytics` to true by default.

fix: v5 default options

---

apps/laboratory/next.config.mjs

Adds Solflare Widget CSP rule for Laboratory.

chore: v5 add solflare widget csp rule

---

.changeset/lucky-bats-lie.md
packages/appkit-utils/src/LoggerUtil.ts

We're importing the logger like this:
`import { pino } from '@walletconnect/logger'`
This causes the webpack bundlers to throw an CommonJS module error

refactor: `Loggerutil.ts`

---

.changeset/three-deers-kneel.md
apps/laboratory/tests/email.spec.ts
apps/laboratory/tests/shared/validators/ModalWalletValidator.ts
packages/core/src/controllers/NetworkController.ts
packages/core/src/utils/ConstantsUtil.ts
packages/core/tests/controllers/NetworkController.test.ts
packages/scaffold-ui/src/views/w3m-account-settings-view/index.ts

This PR removes names flow on settings view for solana namespace
For Linear issues: Closes APKT-1033

fix: remove names flow on settings view for solana namespace

---

.changeset/giant-moons-guess.md
packages/scaffold-ui/src/modal/w3m-modal/index.ts
packages/scaffold-ui/src/views/w3m-connecting-wc-view/index.ts

There was an issue where if you used SIWE and connected with your mobile wallet, the SIWE modal never showed up.
For Linear issues: Closes APKT-1254

fix: siwe modal not opening for some wallets

---

.changeset/fair-wombats-move.md
.changeset/spotty-buses-think.md
apps/laboratory/src/components/Wagmi/WagmiRequestPermissionsAsyncTest.tsx
apps/laboratory/src/components/Wagmi/WagmiRequestPermissionsSyncTest.tsx
packages/adapters/ethers/src/client.ts
packages/adapters/ethers/src/tests/client.test.ts
packages/adapters/ethers5/src/client.ts
packages/adapters/ethers5/src/tests/client.test.ts
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts
packages/appkit-utils/src/ethers/EthersTypesUtil.ts
packages/appkit/src/store/ProviderUtil.ts
packages/appkit/src/store/index.ts

For Embedded wallet, on successful connection, provider returns undefined for below code.  
`ProviderUtil.getProvider(CommonConstantsUtil.CHAIN.EVM)`
This PR is to fix this issue.

Add missing setProvider call

---

.github/workflows/pr_checks.yml
examples/react-wagmi/package.json
package.json
pnpm-lock.yaml

Removing vite-size script and the action workflow

chore: remove vite-size

---

.changeset/warm-toes-unite.md
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts
packages/adapters/wagmi/src/utils/helpers.ts
packages/appkit-utils/package.json
packages/appkit-utils/src/CaipNetworkUtil.ts
pnpm-lock.yaml

Refactors Wagmi adapter's constructor to handle custom transport arrays for Wagmi configs.
Previously we were using only given network's RPC urls to create transport objects for Wagmi configs. Users should be able to override those.
For Linear issues: Closes APKT-1293
For GH issues: closes https://github.com/reown-com/appkit/issues/3056 closes https://github.com/reown-com/appkit/issues/2910

refactor: handle custom transport objects for wagmi adapter

---

.changeset/cool-walls-fix.md
apps/laboratory/playwright.config.ts
apps/laboratory/tests/email.spec.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tests/shared/validators/ModalValidator.ts
packages/ui/src/composites/wui-snackbar/index.ts
packages/wallet/src/W3mFrameProvider.ts

Edited maximum timeouts for frame requests. We currently have our timeout duration on 15 seconds, but we don't throw an error and the timeout duration is low as well. We instead decided to increase the timeout duration to 25 - 30 seconds and also abort the request if it takes that long.
For Linear issues: Closes APKT-1147
Here is an example if the request takes more than 30 seconds.

chore: add max timeouts for frame requests

---

.changeset/perfect-walls-count.md
packages/appkit-utils/src/CaipNetworkUtil.ts

Unichain support has been added to our RPC supported networks. This PR adds Unichain's CAIP id to the list of supported networks to use Reown's RPC URLs.

chore: add unichain to wc rpc supported chains

---

.changeset/unlucky-walls-turn.md
packages/core/src/controllers/SnackController.ts
packages/scaffold-ui/src/partials/w3m-snackbar/index.ts

When we call Snackbar before the previous one is become hidden, this causing unexpected behaviour. This PR introduces changes to make sure they can be called one after other.
Before:
https://github.com/user-attachments/assets/c7bd958c-6563-4a65-a414-ed43526b91c3
After:
https://github.com/user-attachments/assets/f9c4b161-6b48-4df7-9e2f-49b39054531c

refactor: update snackbar logics to prevent closing when new one added before previous is closed

---

.changeset/dry-rivers-cover.md
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tests/shared/validators/ModalValidator.ts
apps/laboratory/tests/wallet-features.spec.ts
packages/scaffold-ui/src/utils/w3m-connecting-widget/index.ts
packages/scaffold-ui/src/views/w3m-connecting-wc-view/index.ts

Whenever we're choosing a web app wallet and click the "Open", for some reason we fetch the URI again instead of redirecting. This was causing some unsubscribe events to appear by the universal provider which led to a few issues with web app wallets.
For Linear issues: Closes APKT-1302
**Before:**
**After:**

fix: web app wallets not working

---

.changeset/orange-melons-divide.md
apps/laboratory/src/components/AppKitButtons.tsx
apps/laboratory/tests/shared/validators/ModalValidator.ts
apps/laboratory/tests/wallet.spec.ts
packages/adapters/ethers/src/client.ts
packages/adapters/ethers5/src/client.ts
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/connectors/AuthConnector.ts
packages/appkit/exports/constants.ts

There is an issue where if you refresh your page even tho you've connected with e.g metamask it'll take too much time to finish loading. This is because we're always reconnecting to auth connector even tho we haven't connected with it before.
For this change we'll make sure that we're only reconnecting to auth connector if a user has already connected before.
For Linear issues: Closes APKT-1358
**Before:**
https://github.com/user-attachments/assets/e5ca1521-e18b-4e10-ba5c-8cfb8a0b8abb
**After:**
https://github.com/user-attachments/assets/8a2600da-98d3-4197-a424-ded5678b048f

chore: optimize connection handling for connectors

---

.changeset/tidy-turtles-jump.md
packages/core/src/controllers/ConnectorController.ts
packages/core/tests/controllers/ConnectorController.test.ts

When using multichain the evm connectors aren't working at the moment.
For example if you use multichain and try to connect with phantom (ethereum) you'll get an error. This happens because the wagmi connector cannot be found [here](https://github.com/reown-com/appkit/blob/main/packages/adapters/wagmi/src/client.ts#L391-L393).
We're mixing the wagmi connector id with solana connector id which results into getting this error.
For Linear issues: Closes APKT-1286
**Before:**
https://github.com/user-attachments/assets/e411f482-6009-4387-ac8b-37b14a9a3950
**After:**
https://github.com/user-attachments/assets/6f032623-6a05-4eb9-bd46-4a8bdc32d935

fix: multichain connectors not working

---

.changeset/perfect-toes-tie.md
packages/appkit/src/client.ts
packages/appkit/src/tests/appkit.test.ts

We should be able to override metadata values instead of using window / document properties only.
For Linear issues: Closes APKT-1366

chore: override metadata values

---

.changeset/large-lemons-heal.md
packages/appkit/src/client.ts
packages/appkit/src/tests/appkit.test.ts

When universal provider was initialised it had no metadata included.

fix: metadata values weren't included in the universal provider

---

.changeset/short-pumas-change.md
packages/appkit/src/client.ts
packages/core/src/utils/TypeUtil.ts

For plain JS users we are not providing expected listeners as we do with the hooks (`useAppKitAccount` and `useAppKitNetwork`). This PR introduces changes to AppKit client to have the same listener for plain JS users to subscribe account and network state.
*The testing of these will be handled in another PR specific to CDN updates

refactor: add subscribe account and network methods for plain js use case

---

.changeset/silver-laws-buy.md
packages/core/src/controllers/SwapController.ts

In swaps, we have logic to check if user have enough balance to pay the gas; `SwapController.hasInsufficientToken`. For specifically to smart accounts, we've returning direct value for gas availability if the account is smart account.
This logic directly returning `true` and it have two issues:
- Bypasses the balance check for swap (not for paying gas)
- It should be return `false` to make the swap available, returning `true` means user has insufficient token as function name describes. 
For Linear issues: Closes APKT-1288

refactor: sa gas availability check logics for swaps

---

.changeset/six-pumpkins-suffer.md
apps/laboratory/tests/smart-account.spec.ts
packages/adapters/wagmi/src/client.ts
packages/appkit/exports/constants.ts
packages/appkit/src/tests/mocks/AppKit.ts
packages/appkit/src/tests/mocks/UniversalProvider.ts
packages/appkit/src/tests/universal-adapter.test.ts
packages/appkit/src/universal-adapter/client.ts

We require the `clientId` of the relay connections to be serialized on BlockchainApi requests

fix: client Id not being set

---

.github/workflows/publish_canary.yml
dangerfile.ts

- Fix publish canary action
- Add danger rule to warn about modified workflows and to fail on deleted ones

fix: publish canary workflow. add danger rule

---

packages/appkit/src/networks/solana/solana.ts
packages/appkit/src/networks/solana/solanaDevnet.ts
packages/appkit/src/tests/mocks/UniversalProvider.ts
packages/appkit/src/tests/utils/HelpersUtil.test.ts
packages/appkit/src/utils/HelpersUtil.ts

Add the workaround for deprecated solana chain ids in Universal Provider Adapter.

fix: add deprecated caip network ids for solana chains as a workaround

---

.changeset/dull-parents-turn.md
packages/adapters/ethers/src/client.ts
packages/adapters/ethers/src/tests/client.test.ts
packages/adapters/ethers5/src/client.ts
packages/adapters/ethers5/src/tests/client.test.ts

There is a bug where if you connected your wallet and try to switch address manually you'll see that there is no address being shown in the connect button.
For Linear issues: Closes APKT-1393
**Before:**
https://github.com/user-attachments/assets/8c9b17b6-e55b-43c5-96b1-488d2cce2c9e
**After:**
https://github.com/user-attachments/assets/3709d1a0-02e3-40dc-9760-0f230b883322

fix: ethers/ethers5 `accountsChanged` handler not working

---

.changeset/six-scissors-remember.md
packages/scaffold-ui/src/partials/w3m-email-login-widget/index.ts
packages/scaffold-ui/src/partials/w3m-email-login-widget/styles.ts

When entering an email to something like "example@" and then clicking Enter, you'll see that it breaks the button styles that's on the right side of the input field.
For Linear issues: Closes APKT-1212
**Before:**
**After:**

fix: email input breaking styles of button

---

.changeset/twelve-kings-jog.md
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts

Fixes an issue where the connect modal on mobile was always showing 'Browser Wallet' option when the injected provider wasn't detected. This happened because we included `info.rdns` field for the injected connector which caused the logic to not work [here](https://github.com/reown-com/appkit/blob/main/packages/scaffold-ui/src/partials/w3m-connect-injected-widget/index.ts#L61-L64).
For Linear issues: Closes APKT-1432
This shouldn't appear if injected provider is not detected on mobile.

fix: remove browser wallet when injected provider is not detected

---

apps/gallery-new/utils/PresetUtils.ts
packages/ui-new/src/components/wui-text/index.ts
packages/ui-new/src/components/wui-text/styles.ts
packages/ui-new/src/utils/TypeUtil.ts

…ith wui-text component
- Added error, warning and accent-primary text color options
- Fixed a bug where inline css variables weren't working in `<wui-text>` component

chore: add error, warning and accent primary text color options

---

.changeset/rude-wasps-shake.md
apps/laboratory/tests/siwe.spec.ts
packages/adapters/wagmi/src/connectors/UniversalConnector.ts

Fix wagmi siwe not reconnecting on page refresh and re-enable test.

fix: wagmi siwe reconnect on refresh

---

packages/adapters/bitcoin/package.json
packages/adapters/polkadot/package.json
packages/appkit-new/package.json
packages/scaffold-ui-new/package.json
packages/ui-new/package.json

For the packages we don't want to publish to npm yet, we need to set the `private` value to `true`. We are having some NPM issues on the CI that's why the Changeset is failing for the packages it cannot publish, then it's not proceed to creating GitHub Releases. Example: https://github.com/reown-com/appkit/actions/runs/11954262429/job/33323967180

chore: set the unused packages to private to prevent changeset to try publishing

---

.changeset/curly-cameras-call.md
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/connectors/UniversalConnector.ts
packages/core/src/controllers/ChainController.ts
packages/core/src/utils/SIWXUtil.ts
packages/siwe/src/mapToSIWX.ts
packages/siwe/tests/mapToSIWX.test.ts

Adds check for missing address or chainId when getting siwe session for guarantee of backwards compatibility.

fix: add check for missing address or chainId when getting siwe session

---

.changeset/cyan-eels-join.md
packages/siwx/package.json
packages/siwx/src/verifiers/BIP122Verifier.ts
packages/siwx/tests/verifiers/BIP122Verifier.test.ts
pnpm-lock.yaml

Fix BIP122Verifier replacing the library used for one with a wider range of signature verifications.
Replaces `bitcoinjs-message` with `bip322-js`.

fix: bitcoin verifier for different signature format

---

.eslintrc.json

Adding eslint rule to enforce boolean naming. Currently as a warning. Will change to error in due time.
- [] My changes generate no new warnings (THEY DO GENERATE LINT WARNINGS!)

chore: add eslint rule for boolean naming

---

.changeset/bright-ads-relate.md
packages/adapters/solana/src/client.ts
packages/adapters/wagmi/src/connectors/AuthConnectorExport.ts
packages/appkit/src/client.ts
packages/appkit/src/tests/appkit.test.ts
packages/core/src/controllers/OptionsController.ts

Fixed a regression where debug mode wasn't working properly when universal provider was throwing an error. I also set debug mode to true by default.
For Linear issues: Closes APKT-1694

fix: debug mode not working with universal provider

---

.changeset/tender-moles-notice.md
packages/adapters/bitcoin/src/adapter.ts
packages/adapters/bitcoin/src/connectors/SatsConnectConnector.ts
packages/adapters/bitcoin/src/connectors/WalletStandardConnector.ts
packages/adapters/bitcoin/tests/BitcoinAdapter.test.ts
packages/adapters/bitcoin/tests/connectors/SatsConnectConnector.test.ts
packages/adapters/bitcoin/tests/connectors/WalletStandardConnector.test.ts

Fix the chainId response when connecting to bitcoin with multichain adapters.

fix: correct return of chain when connecting to bitcoin

---

.changeset/ninety-kangaroos-promise.md
packages/appkit/src/client.ts
packages/core/src/controllers/ChainController.ts
packages/core/src/controllers/ConnectionController.ts
packages/core/src/utils/TypeUtil.ts
packages/core/tests/controllers/ChainController.test.ts

- Refactors's disconnect functionality to make sure it's calling the connectionController's `disconnect` method
- Moves all adapters iteration from adapter specific code (from `appkit/client` to `ChainController`)
- Makes sure it's removing account and network data for each adapter

refactor: disconnect logic and state update for multiple adapter use cases

---

.changeset/silver-rockets-brush.md
apps/builder/components/configuration-sections/section-connect-options.tsx
apps/builder/components/configuration-sections/section-wallet-features.tsx
apps/builder/components/preview-content.tsx
apps/builder/components/sidebar-content.tsx
apps/builder/components/social-buttons.tsx
apps/builder/components/sortable-list-connect-method.tsx
apps/builder/components/sortable-list-wallet-features.tsx
apps/builder/contexts/appkit-context.tsx
apps/builder/providers/appkit-context-provider.tsx
packages/appkit/src/client.ts
packages/core/src/controllers/PublicStateController.ts
packages/core/tests/controllers/PublicStateController.test.ts
packages/scaffold-ui/exports/utils.tsx
packages/scaffold-ui/package.json
packages/scaffold-ui/src/utils/WalletUtil.ts
packages/scaffold-ui/src/views/w3m-connect-view/index.ts

We recently introduced changes to our connect method orders logic. In the connect view, we are conditionally changing the default order if user has injected wallets or not. 
- If user has injected wallets, the default order goes as `wallets`, `email`, `socials`
- If not, the default order goes as  `email`, `socials`, `wallets`
This breaks the logics on the Builder/Demo since there is no static default value and it's now calculated dynamically. This causes an issue when we open the Demo, the order of the items getting changed after first render. This brings an issue that we need to create two data binding between Demo app and AppKit to control the connect methods.
- Expose `getConnectMethodOrder` from AppKit class to call from outside
- Refactor `w3m-connect-view` to use `WalletsUtil` from …

chore: expose a public function to get connect method order with appkit instance

---

.changeset/metal-coins-guess.md
packages/common/src/utils/SafeLocalStorage.ts
packages/siwx/src/configs/CloudAuthSIWX.ts
packages/siwx/tests/configs/CloudAuthSIWX.test.ts

We've updated the Cloud Auth API to send a different header when making the authenticate request.

chore(cloud-auth-nonce): update CloudAuthSIWx to provide the nonce header

---

.changeset/angry-snakes-judge.md
packages/appkit/src/tests/siwe.test.ts
packages/core/src/utils/SIWXUtil.ts

Set active chain as first chain when calling authenticate on universal provider

fix: active chain for siwx authenticate

---

.changeset/seven-shirts-act.md
packages/core/src/controllers/ChainController.ts
packages/core/src/utils/StorageUtil.ts
packages/core/tests/controllers/ChainController.test.ts

Fixed an issue where an incorrect EOA label and icon were displayed in the profile view after reconnecting through social/email login.
**Reproduction Steps:**
- Connect with github
- Disconnect
- Connect with same email associated with the GH account (email login)
- Go to settings
For Linear issues: Closes APKT-1398

fix: incorrect EOA label/icon shown on reconnect with email/social login

---

.changeset/rich-bulldogs-rush.md
packages/core/src/controllers/AccountController.ts
packages/scaffold-ui/src/views/w3m-connecting-social-view/index.ts
packages/scaffold-ui/test/views/w3m-connecting-social-view.test.ts

Fixed an issue where the modal didn't close after completing login if users navigated between different social login options.
For Linear issues: Closes APKT-1277
https://github.com/user-attachments/assets/f6196ca4-262c-4667-b7c7-9d21b5291b79

fix: modal not closing after logging in with social

---

.changeset/great-feet-impress.md
packages/common/src/utils/ConstantsUtil.ts
packages/core/src/controllers/AccountController.ts
packages/scaffold-ui/src/partials/w3m-account-wallet-features-widget/index.ts
packages/scaffold-ui/test/partials/w3m-account-wallet-features-widget.test.ts

Fixed an issue where the balance endpoint kept retrying every 30 seconds, even after returning a 503 status code.
For Linear issues: Closes APKT-987

fix: prevent unnecessary retries for balance endpoint on unsupported networks

---

.changeset/big-olives-ring.md
packages/appkit-utils/src/ErrorUtil.ts
packages/appkit/tests/appkit.test.ts

Added error message for debug mode when a user provides an invalid project id
For Linear issues: Closes APKT-1372

chore: add error message for invalid project id

---

.github/workflows/pr_checks.yml
packages/appkit/tests/appkit.test.ts

Updates if condition for E2E tests workflows to work only when static tests are succeeds. This would allow us to not unnecessarily run E2E since they are expensive.

chore: update pr_checks to run e2e tests when code style and unit tests are succeeds

---

.changeset/twelve-spiders-warn.md
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts

Fixed an issue where wagmi did not reconnect on page reload

fix: wagmi connection not working on page reload

---

.changeset/nice-planets-hang.md
packages/adapters/bitcoin/src/connectors/OKXConnector.ts
packages/adapters/bitcoin/src/connectors/SatsConnectConnector.ts
packages/adapters/bitcoin/tests/connectors/OKXConnector.test.ts
packages/adapters/bitcoin/tests/connectors/SatsConnectConnector.test.ts

When using the Bitcoin adapter on server side framework, `getWallets` and `getProvider` methods throwing `window is not found` error on server side. `sats-connector` package prob doing some window call on background while it's not available on server

fix: bitcoin connectors server side issues

---

packages/scaffold-ui/src/partials/w3m-account-tokens-widget/index.ts
packages/scaffold-ui/test/partials/w3m-account-tokens-widget.test.ts

Added integration test for `w3m-account-tokens-widget` component
For Linear issues: Closes APKT-1905

chore: add test for `w3m-account-tokens-widget`

---

.changeset/eight-forks-smoke.md
packages/appkit/src/universal-adapter/client.ts
packages/appkit/tests/universal-adapter.test.ts

Add default value if namespace is not available on upa getAccounts
For Linear issues: Closes APKT-1998

fix: add default value if namespace is not available on upa getAccounts

---

.changeset/rich-monkeys-smell.md
apps/browser-extension/src/core/transport.ts
apps/laboratory/tests/multichain-extension.spec.ts
packages/adapters/ethers/src/client.ts
packages/adapters/ethers/src/tests/client.test.ts
packages/adapters/ethers5/src/client.ts
packages/adapters/ethers5/src/tests/client.test.ts
packages/appkit/src/client.ts
packages/core/src/controllers/ChainController.ts

Refactors Ethers adapters to handle switch network if the wallet's active network is different than AppKit's active network. 

refactor: switch network if wallet active network is different

---

.changeset/nine-chicken-join.md
packages/appkit/src/client.ts
packages/appkit/tests/appkit.test.ts
packages/appkit/tests/mocks/Options.ts
packages/core/src/utils/StorageUtil.ts

- Refactors AppKit client to handle undefined network object when calling `syncBalance`
- Refactors AppKit client tests to remove redundant mocks

refactor: handle undefined caipNetwork when calling syncBalance

---

.changeset/selfish-rivers-shout.md
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts

Fixed an issue where `ProviderUtil.getProvider('eip155')` returned `undefined` for wagmi adapter when connected to a wallet.
For Linear issues: Closes APKT-2041

fix: `ProviderUtil.getProvider('eip155')` returns `undefined` when using wagmi adapter

---

apps/builder/providers/appkit-provider.tsx
packages/core/src/controllers/ConnectionController.ts
packages/core/src/utils/CoreHelperUtil.ts
packages/scaffold-ui/src/partials/w3m-connecting-wc-mobile/index.ts
packages/scaffold-ui/src/utils/w3m-connecting-widget/index.ts
packages/scaffold-ui/src/views/w3m-connect-view/index.ts
packages/scaffold-ui/test/partials/w3m-connecting-wc-mobile.test.ts

This PR fixes the issue of when attempting to connect with Wallet Connect on iOS Safari through an `iframe` that would not trigger `window.open` with deeplinks.
For Linear issues: Closes APKT-2024

fix: add safari ios to prefetch wc uri

---

.changeset/hot-dogs-rest.md
apps/laboratory/tests/multichain-extension.spec.ts
apps/laboratory/tests/multichain-siwe-extension.spec.ts
apps/laboratory/tests/shared/pages/ModalPage.ts
apps/laboratory/tests/shared/validators/ModalValidator.ts
packages/appkit/src/client.ts
packages/appkit/tests/appkit.test.ts
packages/common/src/utils/ConstantsUtil.ts
packages/core/src/controllers/ChainController.ts
packages/core/src/controllers/RouterController.ts
packages/core/src/utils/StorageUtil.ts
packages/scaffold-ui/src/modal/w3m-modal/index.ts
packages/scaffold-ui/src/views/w3m-networks-view/index.ts
packages/scaffold-ui/src/views/w3m-switch-active-chain-view/index.ts
packages/scaffold-ui/test/modal/w3m-modal.test.ts
packages/scaffold-ui/test/views/w3m-swap-preview-view.test.ts
packages/scaffold-ui/test/views/w3m-swap-view.test.ts
packages/scaffold-ui/test/views/w3m-wallet-send-preview-view.test.ts

- Refactors `onNewNetwork` and `onNewAddress` methods to handle unnecessary `RouterController.goBack()` calls
- Refactors `onSwitchNetwork` method and few other parts to show `SwitchActiveChain` page when users trying to switch to a network from different namespace, and filter connectors with that namespace
- Go to multichain example
- Connect to a namespace
- Switch network
- Connect to another namespace
or
- Go to multichain example
- Connect to a namespace
- Switch network but don't connect, close modal
- Switch to network that previously connected
Try several flows like this
For Linear issues: Closes APKT-2040

fix: redundant goBack call when switching to another namespace

---

.changeset/violet-monkeys-dream.md
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts

Fixed an issue where wagmi adapter would emit disconnect event when user was not connected causing SIWE to break.
For Linear issues: Closes APKT-2090

fix: wagmi/siwe signout

---

.changeset/shy-lamps-build.md
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts

Fixed an issue where wagmi connectors were not appearing in the connect modal
For Linear issues: Closes APKT-2091

fix: wagmi connectors not appearing on connect modal

---

.changeset/four-mangos-yell.md
packages/appkit/src/client.ts
packages/appkit/src/library/react/index.ts
packages/appkit/src/library/vue/index.ts
packages/appkit/tests/appkit.test.ts
packages/core/src/controllers/ModalController.ts

Expanded more views in the modal open function to include Swap, Send, Wallet Is a Wallet, Wallet Is a Network and All Wallets.
For Linear issues: Closes APKT-1873

feat: expand more views for modal open function

---

.changeset/tasty-flies-call.md
packages/adapters/solana/src/providers/AuthProvider.ts
packages/adapters/solana/src/tests/AuthProvider.test.ts
packages/adapters/wagmi/src/connectors/AuthConnector.ts
packages/appkit/src/adapters/ChainAdapterBlueprint.ts
packages/common/src/utils/ConstantsUtil.ts

Multichain social login is currently broken when using all adapters at once, you can test it here https://appkit-lab.reown.com/library/siwx-default
For some reason if we don't use the same connector names for all of our auth providers the auth provider will not be found during the connection. This line of code is causing this issue https://github.com/reown-com/appkit/blob/main/packages/core/src/controllers/ConnectorController.ts#L76
As a fix i've made sure to use the exact same auth connector name for all of our auth connectors 

fix: socials multichain not working

---

packages/ui/src/components/wui-icon/index.ts
packages/ui/src/components/wui-icon/styles.ts
packages/ui/src/utils/CacheUtil.ts

Our `<wui-icon>` is bundling all of the svg icons which can increase the bundle size. Made a simple refactor where we lazy load the icons and also include caching so we don't re-fetch them when not needed.

chore: lazy load svg icons

---

packages/scaffold-ui/src/partials/w3m-all-wallets-list/index.ts
packages/scaffold-ui/test/partials/w3m-all-wallets-list.test.ts

We have several calls for fetching wallets:
- 1) When opening the modal, we are fetching 4 recommended wallets (MM one of them)
- 2) When opening the all wallets page, we are fetching 40 top wallets (MM one of them) 
In 2), we are excluding recommended wallets in the query params, but the problem is when we open directly All Wallets view, both requests going concurently and 2) doesn't know about the recommended wallets on the state. Thus, the MM and three other wallets getting duplicated
This PR fixes by getting unique wallets on all wallets list

refactor: render only unique wallets on the wallets list

---

packages/appkit/tests/client/adapter-management.test.ts
packages/appkit/tests/client/balance.test.ts
packages/appkit/tests/client/connection.test.ts
packages/appkit/tests/client/initialization.test.ts
packages/appkit/tests/client/listeners.test.ts
packages/appkit/tests/client/public-methods.test.ts
packages/appkit/tests/client/universal-adapter.test.ts
packages/appkit/tests/client/walletconnect-events.test.ts
packages/appkit/tests/test-utils.ts

- Fixes AppKit client unit tests as we separated the main client into chunks for WCM deprecation bundle improvements.
- Adds `sequential` to Balance tests. This is quite important when we have more than one async test running. If sequential is not used, the test runner will initialize next tests AppKit client before the other finished and this will run into unexpected situations in the test cases

fix: appkit tests for basic

---

packages/core/src/controllers/ChainController.ts
packages/core/tests/controllers/ChainController.test.ts

We didn’t set status to `disconnected` for all namespaces, instead we only set it for the current namespace. This caused a bug where switching between namespaces showed `connected` status even though we were actually disconnected.
For Linear issues: Closes APKT-2207

fix: wrong status shown when using `useAppKitAccount` hook

---

packages/appkit/src/client/appkit-basic.ts
packages/appkit/tests/client/appkit-basic.test.ts

Do not open modal on `appkit.open()` in basic case
For Linear issues: Closes APKT-2200

chore: prevent appkit.open from opening modal in basic

---

examples/html-ak-basic/src/main.js

Fixed an issue where bifrost wallet signing wasn't working

fix: sign message not working in basic example

---

examples/html-ak-basic-up/src/main.js
examples/next-ak-basic-sign-client-app-router/src/app/components/ActionButton.tsx
examples/next-ak-basic-up-app-router/src/app/page.tsx
examples/react-ak-basic-sign-client/src/components/ActionButton.tsx
examples/vue-ak-basic-sign-client/src/components/ActionButton.vue
examples/vue-ak-basic-up/src/App.vue
packages/appkit/src/client/appkit-basic.ts
packages/appkit/src/client/core.ts

Fixed an issue where if you open the modal and cancel right after you can't open again
For Linear issues: Closes APKT-2245

fix: cannot reconnect after cancelling modal

---

packages/appkit-utils/src/PresetsUtil.ts

This PR maps the chain logos added to the WalletConnect mono repo to AppKit. This is to ensure that the chains configured on AppKit Lab have properly configured chain logos. The PR made to WalletConnect mono repo can be found [here](https://github.com/reown-com/web-monorepo/pull/1727)
NA
NA

chore: Mapping chain logos for missing chain logos on AppKit Lab

---

apps/builder/sentry.client.config.ts

- These two errors (one is from `core`, one is IndexedDB) are consuming a big chunk of our overall sentry error quota
- Ignore them from client side ingestion, as they are both non-actionable.
- Also: adjust error sampling to 50%, traces to 20%. This is in line with what we do on Cloud app.

chore(demo): adjust sentry sample rates, ignore noisy non-actionable errors

---

.changeset/early-radios-begin.md
packages/scaffold-ui/src/partials/w3m-social-login-widget/index.ts
packages/scaffold-ui/test/partials/w3m-social-login-widget.test.ts

We have an asynchronous function which takes time to load up the popup window which then causes browsers like safari to block our popup window.
For Linear issues: Closes APKT-2306

fix: social login popup blocked by safari

---

.github/workflows/pr_checks.yml

- Removes `build:sample-apps` from the `checks` job to start `ui_tests` earlier
- Adds a separate build-sample-apps job running concurrently

chore: do not wait until sample apps build to run ui_tests 

---

packages/adapters/ethers/src/client.ts
packages/adapters/ethers/src/tests/EthersMethods.test.ts
packages/adapters/ethers5/src/client.ts
packages/core/src/controllers/SendController.ts

- Ethers adapters were using `caipAddress` instead of the regular `address` for `writeContract` interactions and tried to create a signer with it, causing Send and Swap to fail.

fix: ethers write contract using caipAddress

---

.changeset/curly-news-draw.md
packages/appkit/src/client/core.ts
packages/appkit/tests/client/listeners.test.ts
packages/appkit/tests/mocks/Adapter.ts

Fixes an issue where user switch network but profile info not getting updated when it should:
- Switching from non EVM to non EVM network
- Switching from profile supported network to testnet

fix: reset profile info if not evm or testnet

---

.changeset/many-camels-grow.md
packages/common/src/utils/ConstantsUtil.ts

Changes the label from `Ethereum` which confused users to `EVM Networks`.
For Linear issues: Closes APKT-2100/change-label-ethereum-to-evm-networks-in-the-select-chain-modal
(label in the image is outdated)

chore(multichain): rename Ethereum to EVM

---

packages/adapters/wagmi/src/connectors/UniversalConnector.ts
packages/adapters/wagmi/src/tests/UniversalConnector.test.ts
packages/adapters/wagmi/src/tests/mocks/AppKit.ts

In the Wagmi adapter's WC connector, we are calling `enable()` function of UniversalProvider, which is an old method from before EIP1193, and not compatible with multi chain functionality. Using enable() causes some issues on multiple adapters examples, where it's returning Solana address and Viem is throwing the following error in the screen shot.
This PR replaces that with the `getAccounts()` method which is doing the same actually. 

fix: using enable from up returns solana address

---

.changeset/modern-tools-relax.md
packages/scaffold-ui/src/modal/w3m-modal/index.ts
packages/scaffold-ui/test/modal/w3m-modal.test.ts

We are calling to `RouterController.goBack` in the W3mModal's `onNewNetwork` event handler even though the modal is not open. This causes an issue where we are clearing the `ConnectorController`'s `filterByNamespace` state, thus, the connector list doesn't get the filtered connectors as expected.
For Linear issues: Closes APKT-2525

fix: prevent unnecessary goback call

---

.changeset/poor-rules-design.md
packages/ui/package.json
pnpm-lock.yaml

- declare appkit packages as dependencies not dev deps as there are imports of non-types

fix: declare appkit packages as dependencies not dev deps

---

.changeset/twelve-cougars-try.md
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/connection.test.ts

When using multichain if we don’t emit `chainId` the CAIP address will not be set for the namespace.
For Linear issues: Closes APKT-2519

fix: account not syncing on some namespaces when using multichain

---

.changeset/every-actors-train.md
packages/scaffold-ui/src/partials/w3m-connecting-wc-web/index.ts
packages/scaffold-ui/src/utils/w3m-connecting-widget/index.ts
packages/scaffold-ui/test/partials/w3m-connecting-wc-web.test.ts
w3m-connecting-wc-web.ts.new

Web wallets can only be opened once a connection to WalletConnect has been established. Currently the UX is confusing as the button can be clicked whilst loading with no effect. This change disables the button until it is actually clickable.
https://github.com/user-attachments/assets/5eae7635-51b5-449b-a552-ea47dba9020a

feat(web-wallet): disable button while loading

---

.changeset/twelve-months-hammer.md
apps/laboratory/tests/shared/utils/project.ts
packages/adapters/solana/src/providers/CoinbaseWalletProvider.ts
packages/adapters/solana/src/tests/providers/CoinbaseWalletProvider.test.ts
packages/controllers/src/controllers/ChainController.ts
packages/controllers/src/controllers/ConnectorController.ts
packages/controllers/tests/controllers/ChainController.test.ts
packages/controllers/tests/controllers/ConnectionController.test.ts
packages/controllers/tests/controllers/ConnectorController.test.ts

When using multichain to connect to Coinbase with Ethereum, there’s a bug where the active namespace isn’t properly checked which causes it to connect to the Coinbase Solana wallet instead.
For Linear issues: Closes APKT-2547

fix: coinbase multichain not working

---

.changeset/lemon-forks-appear.md
packages/adapters/wagmi/src/client.ts
packages/appkit-utils/src/CaipNetworkUtil.ts
packages/appkit-utils/tests/CaipNetworkUtil.test.ts
packages/common/src/utils/TypeUtil.ts

Switches to CAIP network id for `customRpcUrls` property.

refactor: switch to CAIP network id for `customRpcUrls` prop

---

.changeset/fancy-falcons-knock.md
packages/wallet-button/src/tests/scaffold-ui/appkit-wallet-button.test.ts
packages/wallet-button/src/utils/ConnectorUtil.ts

Fixed an issue where the WalletConnect wallet button wasn't opening the "All Wallets" modal view on mobile devices
For Linear issues: Closes APKT-2511
Uploading repro.mov…

fix: open `AllWallets` view on mobile when using WC wallet button

---

.changeset/tame-views-fall.md
packages/controllers/exports/index.ts
packages/controllers/src/controllers/OptionsStateController.ts
packages/scaffold-ui/src/partials/w3m-legal-checkbox/index.ts
packages/scaffold-ui/src/views/w3m-connect-socials-view/index.ts
packages/scaffold-ui/src/views/w3m-connect-view/index.ts
packages/scaffold-ui/src/views/w3m-connect-wallets-view/index.ts
packages/scaffold-ui/src/views/w3m-onramp-fiat-select-view/index.ts
packages/scaffold-ui/src/views/w3m-onramp-tokens-select-view/index.ts
packages/scaffold-ui/test/partials/w3m-legal-checkbox.test.ts
packages/scaffold-ui/test/views/w3m-onramp-fiat-select-view.test.ts
packages/scaffold-ui/test/views/w3m-onramp-tokens-select-view.test.ts

If a user enables the legal checkbox feature, they are forced to click it again after navigating away and returning to the connect view.
For Linear issues: Closes APKT-2527
https://github.com/user-attachments/assets/c8536c97-bca1-4c96-a96f-77837735488a

fix: legal checkbox double confirmation

---

apps/laboratory/src/components/Wagmi/WagmiSendCallsCustomAbiWithPaymasterServiceTest.tsx

- Fix issue with form state not updating if updated out of order

fix: form state dep array

---

.changeset/bitter-days-talk.md
packages/adapters/wagmi/src/connectors/UniversalConnector.ts
packages/appkit/exports/constants.ts
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/src/connectors/WalletConnectConnector.ts
packages/appkit/src/utils/HelpersUtil.ts
packages/appkit/tests/utils/HelpersUtil.test.ts
packages/controllers/src/controllers/OptionsController.ts

Adds support for customizing Universal Provider namespace configuration via the new `universalProviderConfigOverride` option in OptionsController.
This change enables:
- Custom RPC methods for different namespaces (e.g., EVM, Solana)
- Override for namespace chains, events, and RPC endpoints

feat: createAppkit option to override universal provider config

---

.changeset/orange-dancers-listen.md
packages/scaffold-ui/src/views/w3m-swap-view/index.ts
packages/scaffold-ui/test/views/w3m-swap-view.test.ts

Fixed an issue where the swap screen froze if allowance approval failed
For Linear issues: Closes APKT-2225
**Before:**
https://github.com/user-attachments/assets/13cc9586-dce5-4a9b-af81-1bd1943c2454
**After:**
https://github.com/user-attachments/assets/93c20328-e5ca-4139-bd64-6beb42d4b0a7

fix: swap screen freezes when swap allowance fails

---

apps/laboratory/src/components/Wagmi/WagmiSendCallsCustomAbiWithPaymasterServiceTest.tsx

We currently don't have a good way of testing the Paymaster. The only example we have, the "Donut contract", is not documented and requires the user to have native gas token which entirely defeats the purpose of the paymaster.
As an improvement to this we're introducing a simple button to sponsor 0.10USDC.

feat(paymaster): add sample ABI

---

.changeset/three-trams-guess.md
packages/adapters/ethers/src/client.ts
packages/adapters/ethers5/src/client.ts
packages/adapters/solana/src/providers/AuthProvider.ts
packages/adapters/wagmi/src/client.ts
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/src/client/appkit.ts
packages/appkit/tests/client/listeners.test.ts
packages/appkit/tests/client/public-methods.test.ts

Fixed an issue where preferred account type wasn't properly switching on initial connection when using email/social login
For Linear issues: Closes APKT-2540

fix: preferred account type not switching on connect

---

.changeset/young-beans-raise.md
packages/appkit/src/client/appkit.ts
packages/appkit/tests/client/appkit-core.test.ts
packages/controllers/src/controllers/ApiController.ts
packages/controllers/tests/controllers/ApiController.test.ts
packages/scaffold-ui/src/partials/w3m-connect-announced-widget/index.ts
packages/scaffold-ui/src/partials/w3m-connect-injected-widget/index.ts
packages/scaffold-ui/src/utils/ConnectorUtil.ts
packages/scaffold-ui/test/partials/w3m-all-wallets-search.test.ts
packages/scaffold-ui/test/partials/w3m-all-wallets-widget.test.ts
packages/scaffold-ui/test/partials/w3m-connect-announced-widget.test.ts
packages/scaffold-ui/test/partials/w3m-connect-injected-widget.test.ts
packages/scaffold-ui/test/utils/ConnectorUtil.test.ts

Fixed an issue where `excludeWalletIds` option wasn't properly filtering Bitcoin wallets
For Linear issues: Closes APKT-2548

fix: `excludeWalletIds` not working with bitcoin wallets

---

apps/laboratory/tests/email.spec.ts
apps/laboratory/tests/smart-account.spec.ts

This PR updates test flows in the laboratory tests by adding explicit delays in the smart account tests to avoid intermittent sign errors and by removing the loader expectation in the email tests.
- Introduces a 1000ms delay before signing in smart account tests to mitigate a 'user rejected' error.
- Comments out the loader expectation in email tests to skip waiting for a loader that now loads almost instantly.

chore: avoids expecting a loader on socials tests

---

.changeset/eighty-things-cheat.md
packages/adapters/ethers5/src/tests/client.test.ts
packages/adapters/ethers5/src/utils/Ethers5Methods.ts
packages/appkit/src/client/appkit-base-client.ts

Fixed an issue where swaps were not working properly when using the ethers/ethers5 adapter
For Linear issues: Closes APKT-2588

fix: swaps not working properly for ethers/ethers5

---

apps/laboratory/src/utils/ConstantsUtil.ts

When we use `NEXT_PUBLIC_VERCEL_URL` on production, we are getting some domain mismatch about the app's metadata on the wallet views:
This is because we are using the `NEXT_PUBLIC_VERCEL_URL` env in the lab app which is automatically being set by Vercel as Preview domain
This PR changes to use `appkit-lab.reown.org` if the production is deployment.

chore: use main domain if the deployment is production

---

examples/html-wagmi-cdn/src/main.js

Fixed an issue where WalletConnect wouldn’t reconnect after a page refresh, even if the user was previously connected.
For Linear issues: Closes APKT-2485

fix: appkit cdn not reconnecting after page refresh

---

apps/laboratory/tests/email-after-farcaster.spec.ts
apps/laboratory/tests/email.spec.ts
apps/laboratory/tests/smart-account.spec.ts
packages/adapters/wagmi/src/connectors/AuthConnector.ts
packages/appkit/src/client/appkit-base-client.ts
packages/wallet/src/W3mFrameProvider.ts

- Implemented ephemeral calls to secure site so only one call goes at a time, when multuple calls are fired from Appkit, they all resolve a single result
- temporary adjusted tests to accommudate new secure site caching and behaviour  
TODO(in another PR): refactor the web of event driven flows so work is done only when needed e.g. resync accounts/network etc

fix: Ephemeral secure site calls

---

.github/workflows/pr_checks.yml

The merge queue will no longer require the team to `Require branches to be up to date before` before merging as the merge queue will handle this. It will still require all tests to pass of course.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

chore(ci): GitHub Merge Queue compatibility

---

.changeset/moody-keys-bet.md
packages/scaffold-ui/src/partials/w3m-account-wallet-features-widget/index.ts
packages/scaffold-ui/src/utils/HelpersUtil.ts
packages/scaffold-ui/test/partials/w3m-account-wallet-features-widget.test.ts

Removed activity and nft tabs from account modal when using solana
For Linear issues: Closes APKT-2528

chore: remove activity and nft tabs for account view when using solana

---

packages/appkit/package.json
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/public-methods.test.ts

Fixed an issue where connectors didn’t sync properly when using multichain
For Linear issues: Closes APKT-2648
**Before when using SIWX multichain 👇**

fix: connectors not syncing properly when using multichain

---

.changeset/few-pugs-pull.md
apps/laboratory/src/components/AppKitHooks.tsx
apps/laboratory/tests/wallet-features.spec.ts
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/src/client/appkit-core.ts
packages/appkit/src/library/react/index.ts
packages/appkit/src/library/vue/index.ts
packages/appkit/tests/client/public-methods.test.ts
packages/controllers/src/controllers/ModalController.ts
packages/controllers/src/controllers/RouterController.ts
packages/controllers/src/controllers/SwapController.ts
packages/scaffold-ui/src/views/w3m-swap-view/index.ts
packages/scaffold-ui/test/views/w3m-swap-view.test.ts

Add `arguments` param for `appkit.open` function and attach swap initial arguments when opening Swap view.
This allows to open the `Swap` view with predefined tokens and input amount.
https://github.com/user-attachments/assets/a349c3e1-5cba-465a-b5bb-6acb64d5ceb4

feat: swap view opening arguments

---

.changeset/fluffy-toys-vanish.md
packages/adapters/bitcoin/src/connectors/SatsConnectConnector.ts
packages/adapters/bitcoin/tests/connectors/SatsConnectConnector.test.ts

When using SatsConnect Connector (i.e XVerse) it's not emitting the `accountChanged` event as expected. Thus, the AppKit doesn't get the connected account as expected.
In this PR it's trigering the `accountChanged` event inside the `connect()` function. This has been working before and XVerse team has been informed about this. 
- https://docs.xverse.app/sats-connect/xverse-wallet-events#listen-to-wallet-events

fix: sats-connect connector doesn't trigger accountChanged event on after connecting

---

.changeset/fifty-beers-take.md
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/connection.test.ts
packages/appkit/tests/mocks/Adapter.ts

Fixed an issue where the wallet connection would remain in a pending state after a user rejected the connection request
For Linear issues: Closes APKT-2668
This remains pending forever after rejecting request.

fix: connecting state stays pending after request rejection

---

.changeset/tricky-spiders-enter.md
packages/scaffold-ui/src/partials/w3m-connect-recent-widget/index.ts
packages/scaffold-ui/src/utils/WalletUtil.ts
packages/scaffold-ui/test/partials/w3m-connect-recent-widget.test.ts

Fixed an issue where recent wallets were not hidden when included in `excludeWalletIds`
For Linear issues: Closes APKT-2318

fix: hide recent wallets listed in `excludeWalletIds`

---

apps/laboratory/tests/multichain/multichain-wagmi-solana.spec.ts
packages/adapters/wagmi/src/client.ts
packages/appkit/exports/constants.ts

- Subscribe to UP connections that happen outside wagmi context and reconnects to keep internal state in sync
For Linear issues: Closes APKT-2693

fix: subscribe to up in wagmi to sync connection state

---

.changeset/odd-buttons-jam.md
packages/scaffold-ui/src/views/w3m-wallet-compatible-networks-view/index.ts
packages/scaffold-ui/src/views/w3m-wallet-receive-view/index.ts
packages/scaffold-ui/test/views/w3m-wallet-receive-view.test.ts

- Receive screen was showing networks from different namespaces, which could cause issues given the address is different 
- Filters displayed networks to only show corresponding namespace networks
Closes APKT-2694
https://github.com/user-attachments/assets/2fb68a33-d56e-46c3-84a4-847045886b19

fix: only show namespace networks on receive screen

---

.changeset/gentle-papers-obey.md
apps/laboratory/src/components/AppKitInfo.tsx
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/public-methods.test.ts
packages/controllers/exports/react.ts
packages/controllers/exports/vue.ts
packages/controllers/tests/hooks/react.test.ts
packages/controllers/tests/hooks/vue.test.ts

- When using non-embedded wallets, `embeddedWalletInfo` is bringing wrong information.
- Only expose the field if a Reown embeddedWallet is connected
Closes APKT-2218

fix: embeddedwalletinfo showing for non-embedded wallets 

---

.changeset/puny-streets-care.md
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/connection.test.ts
packages/appkit/tests/mocks/Adapter.ts

- `useWalletInfo` and `appkit.getWalletInfo` were not returning information after connecting a wallet
- Call `syncWalletInfo` on all connection types. 
Closes APKT-2715

fix: wallet info not set on connection

---

.changeset/vast-sheep-cut.md
packages/controllers/src/controllers/BlockchainApiController.ts
packages/controllers/tests/controllers/BlockchainApiController.test.ts

- Adds try/catch block on `getSupportedNetworks` to prevent error from bubbling up
Closes APKT-2328

fix: try/catch getSupportedNetworks 

---

packages/appkit/src/client/appkit.ts
packages/wallet/src/W3mFrameProvider.ts
packages/wallet/tests/W3mFrameProvider.test.ts

This PR improves embeded wallet communication by awaiting iframe to load before sending messages to it.
Also removes the initial `setPreferredAccount` request that was sent on provider init. Now `setPreferredAccount` is sent as part of `getUser` 
context https://reown-inc.slack.com/archives/C07C28F0ALX/p1746712558714139

fix: wait for magic to initialize

---

apps/laboratory/src/components/EmbeddedWalletInfo.tsx
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/connection.test.ts

Reworked `connectExternal` flow to use the accounts from `AccountController` if available instead of calling `adapter.getAccounts` second time and doing duplicate work  

refactor: uses existing accounts from AccountController

---

package.json
pnpm-lock.yaml

Fixing typescript mismatch by updating the dev deps to `5.8.3` and match `typescript` version all other packages 
This mismatch was resulting in 
```
> @reown/appkit-siwx@1.7.4 watch /Users/ganchoradkov/www/web3modal/packages/siwx
│ > tsc --watch
│ 
│ node:internal/modules/cjs/loader:1147
│   throw err;
│   ^
│ 
│ Error: Cannot find module '/Users/ganchoradkov/www/web3modal/node_modules/.pnpm/typescript@5.8.2/node_modules/typescript/bin/tsc'
│     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
│     at Module._load (node:internal/modules/cjs/loader:985:27)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
│     at node:internal/main/run_main_module:28:49 {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: []
│ }
│ 
│ Node.js …
```

fix: updates ts to `5.8.3` in dev dependencies

---

.changeset/vast-goats-dream.md
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/connection.test.ts
packages/appkit/tests/client/public-methods.test.ts

AppKit does set connector ID as connected wallet info if the connector or provider not found, which is misleading value bc if these are not found it should keep/set the connected value as undefined

fix: connected wallet info sets connector id if connector or provider not found

---

.changeset/shiny-seas-lose.md
apps/laboratory/tests/mobile-wallet-features.spec.ts
packages/controllers/src/controllers/ConnectorController.ts
packages/controllers/src/utils/MobileWallet.ts
packages/controllers/tests/controllers/ConnectorController.test.ts
packages/controllers/tests/utils/MobileWallet.test.ts

Since Phantom doesn't have WC implementation, having UL redirection available for all namespaces is required to make it work for EVM/Bitcoin use cases, besides Solana. This PR removes active chain check for Phantom on `MobileWallet.handleSolanaDeeplinkRedirect` function. 

fix: phantom mobile wallet select logics to handle evm and bitcoin

---

apps/laboratory/tests/shared/pages/WalletPage.ts

Updated UI tests behaviour to use `click` in `react-wallet` as the old `focus+space` doesn't work with the merging of https://github.com/reown-com/web-examples/pull/880 

refactor: UI tests to `click` a button instead of `focus + space`

---

.github/workflows/ui_tests.yml

Little oversight causing the post-merge action to fail.

fix(e2e-tests): conditionally run S3 upload step

---

.changeset/bright-queens-spend.md
apps/laboratory/src/components/Wagmi/WagmiSignMessageTest.tsx
packages/adapters/solana/src/tests/mocks/W3mFrameProvider.ts
packages/adapters/wagmi/src/connectors/AuthConnector.ts
packages/appkit/src/auth-provider/W3MFrameProviderSingleton.ts

Fixes W3mFrameProvider initialization without current chain id which causes network sync issues betwen AppKit and Secure site

fix: pass chain id to w3m frame provider initialization

---

.changeset/quiet-friends-stay.md
.github/workflows/ui_tests.yml
apps/demo/package.json
apps/demo/tests/email.spec.ts
apps/demo/tests/network.spec.ts
apps/demo/tests/pages/DemoPage.ts
apps/demo/tests/pages/DeviceRegistirationPage.ts
apps/demo/tests/utils/email.ts
apps/demo/tests/validators.ts
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/src/client/appkit.ts
pnpm-lock.yaml

When connected with email, there is an issue for `enableEmbedded` cases (where we see on demo.reown.com), which is redirecting user to first Connect screen then Account screen which is looking odd.
We are calling `this.setUser` method in `onSocialConnected` event handler, which does set user to the namespace object only, doesn't make the AppKit connected. When this function got called, we are calling `ModalController.close()` which is actually detecting that AppKit is not connected yet, and redirecting user to Connect screen rather than Account screen. See:
```js
provider.onSocialConnected(({ userName }) => {
this.setUser(
{ ...(AccountController.state.user || {}), username: userName },
ChainController.state.activeChain
)
})
```
This PR fixes account redirection issue along introducing …

fix: email on connect redirection to account page instead of connect page

---

.changeset/sixty-clowns-cough.md
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/public-methods.test.ts

There is a case where we are calling `syncWalletConnectAccount` which is iterating all AppKit adapters and checking them in the existing WC connection, if the adapter's namespace is not in the connection's available namespaces, we are disconnecting that adapter. 
But there is a case where WC can be used for some adapters, while some others use different connector types. I.e:
- Go to https://appkit-lab.reown.com/library/multichain-all/
- Connect with Trust iOS app with WC 
- It'll connect EVM and Solana only since Bitcoin is not supported on Trust yet)
- Connect Bitcoin with an extension wallet (i.e XVerse)
- Refresh page
- It should reconnect all adapters to whatever they've connected with. Currently, we are disconnecting Bitcoin adapter bc it's not supported on current WC connection, …

fix: disconnecting namespace where it's not on WC connection's available namespaces

---

.changeset/cold-plants-drive.md
apps/laboratory/tests/multichain/multichain-ethers-solana-email.spec.ts
apps/laboratory/tests/multichain/multichain-ethers5-solana-email.spec.ts
apps/laboratory/tests/multichain/multichain-wagmi-solana-email.spec.ts
packages/adapters/ethers/src/client.ts
packages/adapters/wagmi/src/connectors/AuthConnector.ts
packages/appkit-utils/src/HelpersUtil.ts
packages/appkit-utils/tests/HelpersUtil.test.ts
packages/appkit/src/client/appkit.ts

We have an issue on Auth connector when using AppKit with multiple adapters with Wagmi where Wagmi is auto connecting it's AuthConnector no matter what is the last active network on the dapp. 
If last active network on Solana, and refreshing page, Wagmi is calling `reconnect` and this causing Auth provider to switch to Mainnet from Solana unexpectedly.
This PR fixes the auto connection when syncing adapter connections.

fix: auth connector to reconnect only on last active network

---

.changeset/young-otters-mix.md
packages/siwx/src/configs/CloudAuthSIWX.ts
packages/siwx/tests/configs/CloudAuthSIWX.test.ts

Cloud Auth SIWX skip get sessions if token is not set.

fix: cloud auth siwx get sessions

---

.changeset/whole-moose-double.md
apps/laboratory/tests/multichain/multichain-wagmi-solana-email.spec.ts
packages/adapters/bitcoin/src/adapter.ts
packages/adapters/bitcoin/src/connectors/SatsConnectConnector.ts
packages/adapters/bitcoin/tests/BitcoinAdapter.test.ts
packages/adapters/bitcoin/tests/connectors/SatsConnectConnector.test.ts
packages/appkit-utils/src/HelpersUtil.ts
packages/appkit-utils/tests/HelperUtil.test.ts

Fixed an issue where Sats Connect connectors (e.g Leather and Xverse) didn't appear in the connect modal after page load
For Linear issues: Closes APKT-3071

fix: sats connect connectors not appearing in connect modal after page load

---

packages/appkit/package.json
packages/appkit/src/client/appkit.ts
packages/appkit/tests/client/connection.test.ts

Fixed an issue where we showed the wrong preferred account type on profile wallets screen

fix: showing wrong preferred account type in `ProfileWallets` view

---

.changeset/witty-rings-trade.md
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts

Fixed an issue where adding a network using wagmi used the walletconnect rpc instead of wagmi rpc
For Linear issues: Closes APKT-3026,APKT-3145

fix: use wagmi rpc instead of walletconnect rpc when switching network

---

.changeset/clear-parks-lose.md
packages/adapters/bitcoin/tests/exports.test.ts
packages/appkit-utils/src/CaipNetworkUtil.ts
packages/appkit-utils/tests/CaipNetworkUtil.test.ts
packages/appkit/exports/constants.ts
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/appkit-base-client.test.ts
packages/controllers/src/controllers/ChainController.ts
packages/controllers/tests/controllers/ChainController.test.ts

When using the following approach when initializing the AppKit. AppKit throws error when extending networks. 
```tsx
import * as networkDefinitions from '@reown/appkit/networks'
createAppKit({
networks: Object.values(networkDefinitions)
})
```
Thrown error:
```sh
Uncaught TypeError: Cannot read properties of undefined (reading 'default')
at Object.extendCaipNetwork (CaipNetworkUtil.ts:151:54)
at CaipNetworkUtil.ts:201:24
at Array.map (<anonymous>)
at Object.extendCaipNetworks (CaipNetworkUtil.ts:200:25)
at AppKit.extendCaipNetworks (appkit-base-client.ts:403:47)
at new AppKitBaseClient (appkit-base-client.ts:139:30)
at new AppKit (appkit.ts:61:7)
at createAppKit (react.ts:26:13)
at useAppKit.ts:22:16
```
This is possibly bc that one of the Viem chains doesn't have rpcUrlsfield and we are …

fix: networks logics for the ones doesn't have required files

---

.github/dependabot.yml

Updated Dependabot settings as it'll open PRs as group of updates rather than one by one:
- `@walletconnect/*` dependencies from all package.json's
- `viem`, `@wagmi/*` dependencies from all package.json's
- Production dependencies from only AppKit packages
- Development dependencies from only Appkit packages

chore: update dependabot configs

---

.changeset/upset-pets-wash.md
apps/laboratory/tests/email-default-account-types.spec.ts
packages/appkit/exports/constants.ts
packages/controllers/src/controllers/ChainController.ts
packages/controllers/tests/controllers/ChainController.test.ts

When we disconnect the namespace, we are setting `preferredAccountType` of the account status to last used account type, where it should give priority to `defaultAccountTypes` option. 

fix: default account type after disconnect

---

packages/wallet/src/W3mFrame.ts
packages/wallet/tests/W3mFrame.test.ts

- Replace `schema.parse` with `schema.safeParse' 
Closes APKT-3192

chore: use Zod's safeParse 

---

.changeset/salty-files-kick.md
packages/adapters/solana/package.json
packages/adapters/solana/src/client.ts
packages/adapters/solana/src/utils/createSPLTokenTransaction.ts
packages/appkit-utils/exports/solana.ts
packages/appkit-utils/package.json
pnpm-lock.yaml

Fixes `spl-token` dependency issues because the dependency was in devDependencies of appkit-utils. Moving the implementation to the Solana adapter 

chore: fix spl token dependency

---

.changeset/orange-clouds-fail.md
apps/demo/lib/config.ts
apps/demo/package.json
apps/laboratory/app/library/multichain-all/page.tsx
apps/laboratory/app/library/multichain-ethers-solana-siwe/page.tsx
apps/laboratory/app/library/multichain-ethers-solana/page.tsx
apps/laboratory/app/library/multichain-ethers5-solana-siwe/page.tsx
apps/laboratory/app/library/multichain-ethers5-solana/page.tsx
apps/laboratory/app/library/multichain-wagmi-solana-bitcoin/page.tsx
apps/laboratory/app/library/multichain-wagmi-solana-siwe/page.tsx
apps/laboratory/app/library/multichain-wagmi-solana/page.tsx
apps/laboratory/app/library/pay-default/page.tsx
apps/laboratory/app/library/siwx-default/page.tsx
apps/laboratory/app/library/solana-debug-mode/page.tsx
apps/laboratory/app/library/solana-no-email/page.tsx
apps/laboratory/app/library/solana-no-socials/page.tsx
apps/laboratory/app/library/solana-wallet-button/page.tsx
apps/laboratory/app/library/solana/page.tsx
apps/laboratory/package.json
examples/html-wagmi-cdn/src/main.js
examples/react-solana/package.json
examples/react-solana/src/config.ts
examples/vue-solana/package.json
examples/vue-wagmi-solana/package.json
examples/vue-wagmi-solana/src/config.ts
packages/adapters/solana/src/client.ts
pnpm-lock.yaml

- Deprecates unused Solana adapter `wallets` parameter as it is misleading.

chore: deprecate solana wallets parameter

---

.github/workflows/ui_tests.yml

To run the backwards compatibility tests on secure site, we are going to call AppKit's `ui_tests.yml` workflow with different branches. To be able to run this workflow from SS's workflow multiple time with different branches, it's required to make sure the artifacts' file names are unique by branch. This PR makes changes to `ui_tests.yml` to name the artifacts depending on the branch.
*Since the artifact names are file names, it cannot accept slashes, so we do replace slashes with underscore and use this value in the names using env variables. 

chore: add branch name to artifacts

---

.github/workflows/ui_tests.yml

Adds branch name to some artifacts to not confuse the secure site backwards compatible tests 

chore: fix artifact name conflict

---

dangerfile.ts

Removing high entropy string warning from dangerfile. It doesn't provide any value and it causes clutter so more important warning could be missed because of it.

chore: remove high entropy string warning from dangerfile

---

.changeset/eighty-states-wonder.md
packages/controllers/src/utils/ConnectorControllerUtil.ts
packages/controllers/tests/utils/ConnectorControllerUtil.test.ts

Fixed an issue where `UpdateEmailWallet` view would not open when using the `useAppKitUpdateEmail` hook
For Linear issues: Closes APKT-3346

fix: `UpdateEmailWallet` view not opening when using `useAppKitUpdateEmail` hook

---

.changeset/fifty-coats-camp.md
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/walletconnect-events.test.ts
packages/controllers/src/controllers/ConnectionController.ts
packages/controllers/src/controllers/EventsController.ts

Fixed an issue where WalletConnect connections didn't include the `address` value when sending the `CONNECT_SUCCESS` event
For Linear issues: Closes APKT-3440

chore: fix missing `address` in WC success event

---

.changeset/wicked-nails-mix.md
.github/dependabot.yml
packages/adapters/bitcoin/src/connectors/LeatherConnector.ts
packages/adapters/bitcoin/src/connectors/OKXConnector.ts
packages/adapters/bitcoin/src/connectors/UnisatConnector/index.ts
packages/adapters/bitcoin/src/connectors/UnisatConnector/types.ts
packages/adapters/bitcoin/tests/connectors/LeatherConnector.test.ts
packages/adapters/bitcoin/tests/connectors/OKXConnector.test.ts
packages/adapters/bitcoin/tests/connectors/UnisatConnector.test.ts
packages/appkit-utils/src/bitcoin/BitcoinTypesUtil.ts
packages/appkit-utils/tsconfig.json

Refactors OKX and Unisat connectors to pass signInputs to wallet provider's `signPsbt` method
- https://docs.unisat.io/dev/open-api-documentation/unisat-wallet#signpsbt
- https://web3.okx.com/build/dev-docs/sdks/chains/bitcoin/provider#signpsbt

refactor: update OKX and Unisat connectors to pass signInputs to wallet provider's `signPsbt` method

---

packages/controllers/src/controllers/ExchangeController.ts

- Uses `tokenAmount` instead of `amount` for fund from exchange

fix: use token amount

---

.changeset/fluffy-ducks-arrive.md
packages/adapters/ethers/src/client.ts
packages/adapters/ethers/src/tests/client.test.ts
packages/adapters/ethers5/src/client.ts
packages/adapters/ethers5/src/tests/client.test.ts
packages/adapters/wagmi/src/client.ts
packages/adapters/wagmi/src/tests/client.test.ts

Introduced checksum address conversion when connecting to wallets
For Linear issues: Closes APKT-2895

chore: checksum address conversion

---

.changeset/little-boats-lead.md
packages/adapters/wagmi/src/client.ts
packages/controllers/src/controllers/ConnectionController.ts
packages/controllers/tests/controllers/ConnectionController.test.ts
packages/scaffold-ui/src/views/w3m-connecting-wc-view/index.ts

Fixed an issue where rejecting a connection request from a mobile wallet would not redirect back to the previous screen to allow re-initiating the connection
For Linear issues: Closes APKT-3181
https://github.com/user-attachments/assets/bb5e1da7-e58c-4c06-b4ee-50d4ca1263c8

fix: redirect to previous screen and show proper error message if connection request was rejected on mobile

---

.changeset/polite-pianos-run.md
packages/siwx/src/ui/w3m-data-capture-view/index.ts
packages/siwx/tests/ui/w3m-data-capture-view.test.ts

For Linear issues: Closes DAS-752
- [ x I have filled out all required sections

fix: add better error message when reown authentication is not enabled

---

packages/controllers/src/controllers/ExchangeController.ts
packages/controllers/tests/controllers/ExchangeController.test.ts
packages/scaffold-ui/src/views/w3m-deposit-from-exchange-view/index.ts

- Fixes issue where entering fund screen after starting a tx would redirect to Account inmediately
-  Opens popup instead of new tab

fix: Fund from exchange redirect and popup

---

packages/scaffold-ui/src/views/w3m-register-account-name-view/index.ts

Updates top padding on account name select screen where input's border getting cut by header
Before
After

chore: update top padding on input page

---

.changeset/seven-rabbits-behave.md
packages/common/src/utils/ConstantsUtil.ts
packages/controllers/src/controllers/SendController.ts
packages/controllers/tests/controllers/SendController.test.ts

Fixed an issue where users could not send SPL solana tokens through the send flow
For Linear issues: Closes APKT-3625

fix: allow sending spl solana tokens in send flow

---

apps/demo/package.json
packages/appkit/exports/constants.ts
packages/appkit/tests/client/walletconnect-events.test.ts
packages/controllers/src/controllers/ConnectionController.ts
pnpm-lock.yaml

When using WC connection on multi-chain instances, we are calling `CONNECT_SUCCESS` event for the not connected namespaces as well, which is wrong.
- Go to https://appkit-lab.reown.com/library/multichain-all/
- Open WC QR
- Connect with Rainbow mobile app (supports only EIP155)
- See in the Network tab that we send `CONNECT_SUCCESS` for `eip155`, `solana`, and `bip12` as well

fix: prevent calling CONNECT_SUCCESS event for not connected namespaces with WC

---

.changeset/ten-lights-watch.md
packages/adapters/bitcoin/src/connectors/BitcoinWalletConnectConnector.ts
packages/adapters/bitcoin/tests/utils/WalletConnectProvider.test.ts

Fixed an issue where bitcoin walletconnect signing requests did not include the correct user address
For Linear issues: Closes APKT-3637

fix: include correct user address in bitcoin walletconnect signing request

---

packages/appkit/exports/constants.ts
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/appkit-base-client.test.ts

In AppKit base client we have `checkAlloweOrigins` method where we call redundant `ErrorUtil.ALERT_ERRORS.PROJECT_ID_NOT_CONFIGURED` alerts:
- `!allowedOrigins || !CoreHelperUtil.isClient()` clause: The `!allowedOrigins` here is deadly code where it never goes falsy as we handle the errors on `fetchAllowedOrigins` method. If the error is not known, we return empty array, where it's not falsy. Only isClient() check left, and if the code runs on server side, we should not proceed running the function.
- As we handle errors on the `fetchAllowedOrigins` and return empty array for other types of errors, calling `ErrorUtil.ALERT_ERRORS.PROJECT_ID_NOT_CONFIGURED` on switch case's `default` is dead code.
If there is a UI change include …

refactor: remove redundant project id not configured error triggers

---

packages/adapters/bitcoin/src/adapter.ts
packages/adapters/bitcoin/src/connectors/UnisatConnector/index.ts
packages/adapters/bitcoin/tests/connectors/UnisatConnector.test.ts

After connecting and switching network on Bitcoin, refreshing page switches AppKit back to Bitcoin Mainnet
- Go to https://appkit-lab.reown.com/library/bitcoin/
- Connect with Unisat Wallet
- Switch to Bitcoin Signet
- Refresh page
- See that AppKit switches back to Bitcoin back

fix: use getCaipNetworks method on Bitcoin adapter to find active caip network

---

.changeset/khaki-experts-yell.md
packages/controllers/src/controllers/ExchangeController.ts
packages/controllers/tests/controllers/ExchangeController.test.ts
packages/scaffold-ui/src/views/w3m-fund-wallet-view/index.ts

- Fixes issue where error would appear if payWithExchange is not enabled.

fix: Do not show error message if payWithExchange is not enabled

---

apps/laboratory/package.json
apps/laboratory/src/components/AppKitConnections.tsx
apps/laboratory/src/components/Bitcoin/BitcoinSendTransferTest.tsx
apps/laboratory/src/components/Bitcoin/BitcoinSignPSBTTest.tsx
apps/laboratory/src/components/DemoContent.tsx
apps/laboratory/src/components/Ethers/Ethers5SendCallsTest.tsx
apps/laboratory/src/components/Ethers/Ethers5Tests.tsx
apps/laboratory/src/components/Ethers/Ethers5TransactionTest.tsx
apps/laboratory/src/components/Ethers/Ethers5WriteContractTest.tsx
apps/laboratory/src/components/Ethers/EthersSendCallsTest.tsx
apps/laboratory/src/components/Ethers/EthersTests.tsx
apps/laboratory/src/components/Ethers/EthersTransactionTest.tsx
apps/laboratory/src/components/Ethers/EthersWriteContractTest.tsx
apps/laboratory/src/components/InitializeBoundary.tsx
apps/laboratory/src/components/MultiChainInfo.tsx
apps/laboratory/src/components/Solana/SolanaSendTransactionTest.tsx
apps/laboratory/src/components/Solana/SolanaSignAllTransactionsTest.tsx
apps/laboratory/src/components/Solana/SolanaSignAndSendTransactionTest.tsx
apps/laboratory/src/components/Solana/SolanaSignJupiterSwapTest.tsx
apps/laboratory/src/components/Solana/SolanaSignMessageTest.tsx
apps/laboratory/src/components/Solana/SolanaSignTransactionTest.tsx
apps/laboratory/src/components/Solana/SolanaWriteContractTest.tsx
apps/laboratory/src/components/Toast.tsx
apps/laboratory/src/components/Wagmi/WagmiPurchaseDonutAsyncPermissionsTest.tsx
apps/laboratory/src/components/Wagmi/WagmiPurchaseDonutSyncPermissionsTest.tsx
apps/laboratory/src/components/Wagmi/WagmiSignMessageTest.tsx
apps/laboratory/src/components/Wagmi/WagmiTransactionTest.tsx
apps/laboratory/src/components/Wagmi/WagmiWriteContractTest.tsx
apps/laboratory/src/hooks/useWagmiActiveCapabilities.ts
apps/laboratory/tests/shared/utils/logs.ts

- Enable `turbopack` for laboratory
- Fix lint issues of lab

chore: enable turbopack for lab

---

apps/laboratory/package.json

chore: disable turbopack for lab build

---

.github/workflows/pr_checks.yml

Merge Queue runs are failing to fetch the references for the branches. 
What usually causes this
1.	Workflow not triggered on merge_group: If checks only run on pull_request or push, they won’t see the merge-queue ref GitHub creates. 
2.	actions/checkout not checking out the queue ref: If we don’t pass ref: ${{ github.ref }} (and sometimes need fetch-depth: 0), checkout may try to fetch a default ref and then explicitly fetch the queue ref, which 404s because it was never requested (or already GC’d).  
3.	Your job pushes/updates the ref: The gh-readonly-queue ref is read-only and ephemeral. Any step trying to push back to it (e.g., “update branch,” “commit changes,” codegen, etc.) will fail or race the ref disappearing.  
- Updates CI workflows to always check out by commit SHA instead of …

chore: use sha instead of ref checkout action

---

.changeset/ready-ducks-send.md
packages/controllers/src/utils/withErrorBoundary.ts
packages/controllers/tests/utils/withErrorBoundary.test.ts

When any error thrown on WalletKit, AppKit handle those with `withErrorBoundary` and stringifying objects. But the WK errors already returned as object and includes `message` property which will be enough for us to show proper messages. 
In this PR it updates the error boundary to look for the error.message first use it if exist. 

refactor: update error boundary to handle wk error messages properly

---

.github/workflows/pr_checks.yml
.github/workflows/publish-prerelease.yml
.github/workflows/release-canary.yml
.github/workflows/release-publish.yml
.github/workflows/release-start.yml
.github/workflows/ui_tests.yml
.github/workflows/unit_tests.yml

- Replaces `pnpm install` with `pnpm install --frozen-lockfile` on workflow files to ensure lockfile is respected during workflow runs.
- Ensures installed packages in workflows use known/stable/safe versions.
Closes ISAI-41

chore: use --frozen-lockfile on pnpm install in workflow files

---

.github/workflows/cta.yml

- Adds Copyright Transfer Agreement (CTA) workflow to require external contributors to sign an agreement when submitting changes

chore: add signature cta bot

---

.github/workflows/cta.yml

Pins CTA assistant to latest known hash

chore: pin cta assistant to latest known hash

---

pnpm-workspace.yaml

Set minimum release age to 3 days. This will only pull dependences that have been released for longer than the amount specified, including transitive dependencies.
https://pnpm.io/settings#minimumreleaseage

chore: set minimum release age

---

packages/appkit/src/client/appkit-base-client.ts
packages/scaffold-ui/src/partials/w3m-connect-announced-widget/index.ts
packages/scaffold-ui/src/partials/w3m-connect-injected-widget/index.ts
packages/scaffold-ui/src/partials/w3m-connector-list/index.ts
packages/scaffold-ui/src/utils/w3m-connecting-widget/index.ts
packages/scaffold-ui/src/views/w3m-connecting-multi-chain-view/index.ts
packages/scaffold-ui/test/partials/w3m-connect-announced-widget.test.ts
packages/scaffold-ui/test/partials/w3m-connect-injected-widget.test.ts
packages/scaffold-ui/test/views/w3m-connecting-multi-chain-view.test.ts

When connecting to an external wallet without going to `AllWallets` view the wallet is missing wallet rank number. If we don't detect the wallet rank we're going to fetch it from web3modal api when landing on the `W3mConnectingExternalView` view

fix: missing `walletRank` for external connectors

---

.changeset/afraid-pens-tell.md
packages/appkit/src/client/appkit-base-client.ts
packages/appkit/tests/client/initialization.test.ts

Fixed an issue where the `useAppKitConnection` hook returned `null` when wallet is disconnected
For Linear issues: Closes APKT-3829

fix: `useAppKitConnection` returning `null` when wallet is disconnected

---

.changeset/poor-bars-smash.md
packages/scaffold-ui/src/partials/w3m-account-wallet-features-widget/index.ts

There is a really weird issue where is happening when using socials - after connecting with socials on multichain instance, switching networks and trying to connect with Social again, moves AppKit to weird state where the modal is closed unexpectedly, thus the social flows getting broken.
We have a `AccountController.subscribe` listener in the constructor of the `w3m-wallet-features-widget`. This page is only rendered as the home page of the Embedded Wallet. 
When user connected with EW, and switch between networks of non-embedded-wallet supported network (i.e Bitcoin), then switch back to EVM again, the AppKit's (or actually `w3m-wallet-features-widget`'s life cycle methods) goes into weird state where even tho it's calling the `disconnectedCallback` as expected (I've put some logs and …

fix: social provider not connecting after switch between networks of different connectors

---

.changeset/all-bears-flash.md
packages/controllers/src/utils/withErrorBoundary.ts
packages/controllers/tests/utils/withErrorBoundary.test.ts

Fixed an issue where the universal provider threw a random object error when the wallet rejected connection request
For Linear issues: Closes APKT-3645

fix: random object error thrown when rejecting connection request from universal provider

---

apps/laboratory/next-env.d.ts
apps/laboratory/package.json
pnpm-lock.yaml

- Upgrade Next.js to latest canary
- Enable Turbopack for building app 
```sh
Build completed in 64s (1m 4s)
-------
Build completed in 32s (0m 32s)
```

chore: upgrade to new next canary and enable turbopack for builds

---

.github/workflows/devin_docs_update.yml
.github/workflows/devin_staking_dashboard_update.yml
.github/workflows/devin_unity_cdn_update.yml

- Updated all three Devin workflows to detect the new release commit format
- Release commits now use `Release/X.Y.Z (#PR)` instead of `Merge release/X.Y.Z back to main`
- Changed trigger conditions from checking for both `'Merge release/'` AND `'back to main'` to checking for `'Release/'` OR `'release/'`
- `.github/workflows/devin_docs_update.yml`
- `.github/workflows/devin_staking_dashboard_update.yml`
- `.github/workflows/devin_unity_cdn_update.yml`

fix: update devin workflow triggers for new release commit format
