- .postcssrc
- package-lock.json
- package.json
- src/styles/style.css
> Working on improving the css!

- .postcssrc
- package-lock.json
- package.json
This will allow future PRs to improve the CSS building
> Adding postcss-cssnext to parcel pipeline

- README.md
- package.json
Updated documentation re: https://github.com/WalletConnect/walletconnect.js/issues/2
> Update readme && fix example script

- package-lock.json
- package.json
- webpack.config.js
> Missing Modal images Fixed

- src/index.tsx
Fixes Issue where Fortmatic shows no response #19
> fixes typos and shows response to users

- package-lock.json
- package.json
- src/helpers/utils.ts
- tslint.json
> Update Prettier / TSLint Config

- package.json
Update Portis to its latest version
> Update Portis version

- README.md
- example/package-lock.json
- example/package.json
- example/src/App.tsx
- src/core/connectors/torus.ts
- Update torus docs
- Bump Torus version
- Use enabledVerifiers
> Add support for torus v0.2.6

- README.md
Add Totle to projects list in README.
> Add Totle to projects list

- src/components/Modal.tsx
> Modal scrollable on overflow. Closes #104

- README.md
Copy-pasted from the Discord chat.
To get people up-to-the-speed fast.
> Added instructions for vanilla JavaScript

- package.json
- src/index.ts
ProvideController is the most useful part of web3modal. If one wants to build custom UIs on the top of web3modal, this needs to be exported, so that the library consumer can get out a filtered wallet list.
It is very hard to customer web3modal UI as it. To make user elements reusable, a major rework of the library is needed. Optimally, the library consumer can decide where and how React components are rendered, instead of leaving any UI choices like shooting up modals for the library. It does not hurt to export React directly, as there are plenty of tutorials of how to embed React code in the third-party kits like Angular or Vanilla JS.
But for now, here I added simply one line export to make this available for library consumers. 
Below is some sample code how to create a wallet list in …
> Export ProvideController

- example/package-lock.json
- example/package.json
- example/src/helpers/utilities.ts
The following changes have been made in this PR:
- Fix example methods related to signing
- bump torus
Please review and approve @pedrouid
> Fix issues with example

- src/constants/chains.ts
https://artis.eco/
https://github.com/lab10-coop/sigma1
https://github.com/lab10-coop/tau1
> add ARTIS networks

- README.md
> Fix typo for utils section in README

- src/providers/injected/index.ts
- src/providers/logos/blockwallet.svg
adding support for BlockWallet as an injected provider. BlockWallet is a browser extension crypto wallet with a focus on privacy. https://blockwallet.io/
> add support for BlockWallet

- README.md
Mention Brave Wallet as a supported injected provider
> docs: add Brave Wallet to injected providers list

- src/constants/chains.ts
> Update chains.ts - add candle

- packages/react/src/hooks/account/useSignMessage.ts
- packages/react/src/hooks/account/useSignTypedData.ts
- packages/react/src/hooks/contract/useContract.ts
- packages/react/src/hooks/contract/useContractRead.ts
- packages/react/src/hooks/contract/useContractWrite.ts
- packages/react/src/hooks/contract/usePrepareContractWrite.ts
- packages/react/src/hooks/contract/useToken.ts
- packages/react/src/hooks/transaction/useSendTransaction.ts
- packages/react/src/utils/useSyncHookBuilder.ts
- Add initialOpts to relevant hooks
> Add initialOpts to functions

- chains/ethereum/src/api.ts
- chains/ethereum/src/utilities.ts
- examples/react/package.json
- package-lock.json
- package.json
- packages/core/src/controllers/ModalToastCtrl.ts
- packages/ui/src/components/w3m-modal-backcard/index.ts
- packages/ui/src/components/w3m-modal-backcard/styles.ts
- packages/ui/src/components/w3m-modal-header/styles.ts
- packages/ui/src/components/w3m-modal-toast/index.ts
- packages/ui/src/components/w3m-modal-toast/styles.ts
- packages/ui/src/components/w3m-modal/index.ts
- packages/ui/src/components/w3m-modal/styles.ts
- packages/ui/src/components/w3m-text/styles.ts
- packages/ui/src/partials/w3m-mobile-wallet-selection/index.ts
- packages/ui/src/partials/w3m-mobile-wallet-selection/styles.ts
- packages/ui/src/utils/Svgs.ts
- packages/ui/src/utils/UiHelpers.ts
- packages/ui/src/views/w3m-coinbase-mobile-connector-view/index.ts
- packages/ui/src/views/w3m-metamask-connector-view/index.ts
- packages/ui/src/views/w3m-wallet-explorer-view/index.ts
- packages/ui/src/views/w3m-walletconnect-connector-view/index.ts
- Addresses some styling related issues in #585 (tackled tasks are ticked off)
- Added accessor function for ethereumClient (without it accessing its state resulted in outdated values)
- Updated deps
- Extended toast component to be used for error messages
> Styling fixes

- packages/react/readme.md
As per README file + recent issue raised in #612
> chore(readme): update with latest React instructions.

- packages/react/readme.md
A minor fix for a typo in sample code in react/readme.md
> fixed a typo of useConnectModal in react/readme

- packages/react/readme.md
> fix: useSignMessage example

- src/providers/injected/index.ts
- src/providers/logos/exodus.svg
We will like to integrate Exodus wallet provider into web3modal. Thanks
1. Install [Exodus Browser Extension](https://www.exodus.com/browser-extension/)
2. Connect to a Wallet
3. Select Exdous
4. Connect successfully
> feat: add exodus wallet support

- examples/html/index.html
- examples/html/main.js
- examples/html/package.json
- examples/react-standalone/package.json
- examples/react-standalone/src/pages/index.tsx
- lerna.json
- package.json
- packages/html/.eslintrc.json
- packages/html/.npmignore
- packages/html/index.ts
- packages/html/package.json
- packages/html/readme.md
- packages/html/rollup.config.js
- packages/html/src/client.ts
- packages/html/tsconfig.json
- packages/react/src/components/Web3Modal.tsx
- packages/standalone/.eslintrc.json
- packages/standalone/.npmignore
- packages/standalone/index.ts
- packages/standalone/package.json
- packages/standalone/readme.md
- packages/standalone/rollup.config.js
- packages/standalone/src/client.ts
- packages/standalone/tsconfig.json
- yarn.lock
- Add `@web3modal/html`
- Add `@web3modal/standalone`
Each package exposes `Web3Modal` client that makes working in those targets much easier
> Add html and standalone packages

- README.md
- docs/providers/phantom.md
- src/providers/connectors/index.ts
- src/providers/connectors/phantom.ts
- src/providers/injected/index.ts
- src/providers/logos/phantom.svg
This PR adds support for **Phantom Wallet**.
**Links:**
[Phantom Wallet](https://phantom.app/) 
[Docs](https://docs.phantom.app/)
> Adding support for Phantom wallet

- src/providers/connectors/sequence.ts
Fixes to the sequence connector for web3modal v1
> Fixes to Sequence connector integration

- chains/ethereum/src/client.ts
- packages/ui/src/partials/w3m-modal/index.ts
fix small typo in fetchEns Name. 😬
> fix: typo in fetchEnsName

- examples/laboratory/src/pages/v2Standalone.tsx
- package.json
> Expose client id, success feedback for standalone example

- readme.md
This is just a small modification on React Example link on the readme!
> Modify react example broken link in Readme file

- chains/ethereum/package.json
- examples/create-react-app/package.json
- examples/html-standalone/package.json
- examples/html/package.json
- examples/laboratory/package.json
- examples/nextjs-standalone/package.json
- examples/nextjs/package.json
- lerna.json
- packages/core/package.json
- packages/core/src/types/controllerTypes.ts
- packages/html/package.json
- packages/react/package.json
- packages/standalone/package.json
- packages/ui/package.json
- packages/ui/src/components/w3m-modal-router/index.ts
- packages/ui/src/partials/w3m-android-wallet-selection/index.ts
- packages/ui/src/partials/w3m-android-wallet-selection/styles.css
- packages/ui/src/views/index.ts
- packages/ui/src/views/w3m-connectors-view/index.ts
- packages/ui/src/views/w3m-connectors-view/styles.css
- Add ability to select non WalletConnect option (i.e. wagmi connector) in android view
> Add connectors to android view (2.1.2)

- src/providers/injected/index.ts
- src/providers/providers/index.ts
Bitkeep - BitKeep, Uniform specification of wallet name.
> fix: wallet name

- chains/ethereum/package.json
- laboratory/package.json
- lerna.json
- packages/auth-html/package.json
- packages/auth-react/package.json
- packages/core/package.json
- packages/html/package.json
- packages/react/package.json
- packages/standalone/package.json
- packages/ui/package.json
- fix: Dependency tree of `@web3modal/auth-react` package
> Release 2.4.1

- .github/workflows/pr_checks.yml
- apps/gallery/package.json
- dangerfile.ts
- lerna.json
- package-lock.json
- package.json
- packages/core/.eslintrc.json
- packages/core/.npmignore
- packages/core/index.ts
- packages/core/package.json
- packages/core/readme.md
- packages/core/src/controllers/ModalController.ts
- packages/core/src/controllers/RouterController.ts
- packages/core/tests/controllers/ModalController.test.ts
- packages/core/tests/controllers/RouterController.test.ts
- packages/core/tsconfig.json
- tsconfig.json
- feat: add core package and first controllers
- feat: add tests setup for core
- feat: add [danger js](https://danger.systems/js/) for the repo and first set of rules
> Add first controllers, tests and danger

- chains/ethereum/package.json
- laboratory/package.json
- lerna.json
- package-lock.json
- packages/core/package.json
- packages/core/src/controllers/ExplorerCtrl.ts
- packages/core/src/utils/CoreUtil.ts
- packages/html/package.json
- packages/react/package.json
- packages/ui/package.json
- packages/ui/src/utils/UiUtil.ts
N/A
- fix: Duplicate wallet display in search when querying wallet's that were already fetched as recommended
- chore: Add `try/catch` around localStorage operations just in case users have strict CSP settings
N/A
> Release 2.6.1

- chains/ethereum/package.json
- chains/ethereum/src/utils.ts
- laboratory/package.json
- lerna.json
- package-lock.json
- package.json
- packages/core/package.json
- packages/html/package.json
- packages/react/package.json
- packages/ui/package.json
N/A
- fix: wagmi core connector import path (thank you @jgalat)
- chore: Update dependencies
N/A
> Release 2.6.2

- apps/gallery/.storybook/main.ts
- apps/gallery/.storybook/preview.tsx
- apps/gallery/stories/components/wui-icon.stories.ts
- apps/gallery/stories/components/wui-text.stories.ts
- packages/ui/src/utils/ThemeUtil.ts
- feat: Listen to background events & update `data-wui-theme`
> [:feat] add theme switch

- apps/gallery/.storybook/main.ts
- apps/gallery/.storybook/preview.tsx
- fix: Small fixes to cleanup the Storybook ui
> [:fix] some small fixes to cleanup storybook ui

- apps/gallery/stories/composites/wui-link.stories.ts
- packages/ui/src/composites/wui-button/index.ts
- packages/ui/src/composites/wui-link/index.ts
- packages/ui/src/composites/wui-link/styles.ts
- feat: Add `wui-link` component + adding `onClick` for `wui-button` and `wui-link`
> V 3/Add wui-link component

- apps/gallery/stories/components/wui-image.stories.ts
- packages/ui/src/components/wui-image/index.ts
- packages/ui/src/components/wui-image/styles.ts
- packages/ui/src/utils/ThemeUtil.ts
- feat: Add `wui-image` + small cleanup `ThemeUtil`
> adding wui-image component

- apps/gallery/stories/components/wui-image.stories.ts
- apps/gallery/stories/composites/wui-card-select.stories.ts
- apps/gallery/stories/composites/wui-wallet-image.stories.ts
- apps/gallery/utils/PresetUtils.ts
- packages/ui/index.ts
- packages/ui/src/composites/wui-button/styles.ts
- packages/ui/src/composites/wui-card-select/index.ts
- packages/ui/src/composites/wui-card-select/styles.ts
- packages/ui/src/composites/wui-link/styles.ts
- packages/ui/src/composites/wui-list-select/styles.ts
- packages/ui/src/utils/ThemeUtil.ts
- feat: Add `wui-card-select` component
> V3/ Add wui-card-select component

- packages/ui/src/composites/wui-button/styles.ts
- packages/ui/src/utils/ThemeUtil.ts
> add focus cleanup

- apps/gallery/components/gallery-container/index.ts
- apps/gallery/components/gallery-container/styles.ts
- apps/gallery/stories/layout/wui-separator.stories.ts
- dangerfile.ts
- packages/ui/index.ts
- packages/ui/src/layout/wui-separator/index.ts
- packages/ui/src/layout/wui-separator/styles.ts
- feat: Add `wui-separator` component
> V 3 / Add wui separator component

- apps/gallery/stories/layout/wui-flex.stories.ts
- apps/gallery/stories/layout/wui-grid.stories.ts
- packages/ui/src/layout/wui-flex/index.ts
- packages/ui/src/layout/wui-grid/index.ts
- packages/ui/src/utils/HelperUtils.ts
- packages/ui/src/utils/ThemeUtil.ts
- packages/ui/src/utils/TypesUtil.ts
- feat: Add `margin` and `padding` to `wui-grid` and `wui-flex`
> V 3/layout boxing

- apps/gallery/stories/layout/wui-overlay.stories.ts
- apps/laboratory/package.json
- dangerfile.ts
- package-lock.json
- packages/ui/index.ts
- packages/ui/src/layout/wui-overlay/index.ts
- packages/ui/src/layout/wui-overlay/styles.ts
- packages/ui/src/utils/ThemeUtil.ts
- Adds overlay component
- Adds new theme variables
> [v3] wui-overlay

- apps/gallery/stories/components/wui-shimmer.stories.ts
- packages/ui/index.ts
- packages/ui/src/components/wui-shimmer/index.ts
- packages/ui/src/components/wui-shimmer/styles.ts
- feat: Add `wui-shimmer` component
> V 3/ Add wui shimmer

- apps/gallery/stories/composites/wui-search-bar.stories.ts
- packages/ui/index.ts
- packages/ui/src/composites/wui-button/index.ts
- packages/ui/src/composites/wui-input-element/index.ts
- packages/ui/src/composites/wui-input/index.ts
- packages/ui/src/composites/wui-input/styles.ts
- packages/ui/src/composites/wui-list-select/index.ts
- packages/ui/src/composites/wui-search-bar/index.ts
- packages/ui/src/composites/wui-search-bar/styles.ts
- packages/ui/src/composites/wui-wallet-image/index.ts
- packages/ui/src/layout/wui-separator/index.ts
- feat: Add `wui-search-bar` component
> V 3/wui search bar

- packages/core/src/controllers/AccountController.ts
- packages/core/src/controllers/NetworkController.ts
- packages/core/tests/controllers/AccountController.test.ts
- packages/core/tests/controllers/NetworkController.test.ts
- packages/scaffold-html/src/client.ts
- packages/wagmi/src/client.ts
- Added wagmi's watch* methods to update core when account or network are changed externally
> [v3] Set up wagmi acc and network watch methods, sync with core

- .github/workflows/playwright_tests.yml
- laboratory/tests/shared/constants/index.ts
Minor changes, title
** temporary until e2e tests moved into a package
> fix: specified action to only run on v2 changes, removed unused constant

- apps/laboratory/next.config.js
- apps/laboratory/package.json
- package-lock.json
- package.json
- packages/core/package.json
- packages/scaffold/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- turbo.json
- Added watch command to packages
- Set up turborepo to launch gallery and laboratory in watch mode
- Updated deps
> [v3] fix watch mode in laboratory and gallery

- apps/laboratory/package.json
- dangerfile.ts
- examples/vue-wagmi/package.json
- package-lock.json
- package.json
- packages/core/src/controllers/ApiController.ts
- packages/core/src/utils/AssetUtil.ts
- packages/core/src/utils/TypeUtils.ts
- packages/scaffold/src/modal/w3m-modal/index.ts
- packages/scaffold/src/views/w3m-connect-view/index.ts
- packages/scaffold/src/views/w3m-connecting-external-view/index.ts
- packages/wagmi/src/client.ts
- packages/wagmi/src/utils/constants.ts
- packages/wagmi/src/utils/presets.ts
- Updated dependencies
- Added connector images
- Added connector filtering out by id
> [v3] Connector images and filtering out by explorer id

- laboratory/src/pages/index.tsx
- readme.md
- fix: removed menu item from lab as it is no longer planned
> fix: remove unused menu option

- apps/laboratory/src/layout/Header.tsx
> fix: GitHub caps

- packages/core/src/controllers/ApiController.ts
- packages/core/src/utils/CoreHelperUtil.ts
- packages/scaffold/src/partials/w3m-connecting-wc-mobile/index.ts
- packages/ui/src/components/wui-image/index.ts
- Remove crossorigin tag from images (was breaking ipfs)
- Fix issue with image loading in "all wallets" view
> [v3] Image fixes, android improvements

- apps/laboratory/src/layout/Header.tsx
- packages/ui/src/components/wui-card/styles.ts
- packages/ui/src/composites/wui-tabs/index.ts
- packages/ui/src/utils/ThemeUtil.ts
* Adjusted bg color light mode
* Adjusted tab animation
> Chore / UI tasks

- examples/react-ethers5/src/App.tsx
Fix-up react-ethers5 example after #1423
Issue:
> update react-ethers5 example

- packages/common/src/utils/DateUtil.ts
N/A
- fix: update dayjs plugin module import
> fix: update dayjs plugin module imports

- package-lock.json
- packages/core/src/controllers/ConnectionController.ts
- packages/core/src/controllers/RouterController.ts
- packages/core/src/controllers/SwapApiController.ts
- packages/core/src/utils/ConstantsUtil.ts
- packages/core/src/utils/CoreHelperUtil.ts
- packages/core/src/utils/TypeUtil.ts
- packages/core/tests/controllers/ConnectionController.test.ts
- packages/ethers5/src/client.ts
- packages/scaffold/src/views/w3m-account-view/index.ts
- packages/scaffold/src/views/w3m-swap-select-token-view/index.ts
- packages/scaffold/src/views/w3m-swap-view/index.ts
- packages/ui/src/composites/wui-input-text/index.ts
- packages/ui/src/composites/wui-token-list-item/index.ts
- packages/ui/src/composites/wui-token-list-item/styles.ts
- packages/wagmi/src/client.ts
N/A
- feat: use 1inch API for tokens, balances, spot prices and swaps
- fix:
- chore:
closes #...
> feat(1inch-api): request data from 1inch swap API

- package-lock.json
- packages/ethers/package.json
- packages/ethers5/package.json
N/A
- feat:
- fix:
- chore: update ethereum provider to 2.10.6
> chore(update-dependency): update ethereum provider to 2.10.6

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
Releasing a new stable release for the tech depth week improvements. Let's get this new version before we release the stable email feature. Some issues waited to be fixed as we discussed in [this conversation](https://walletconnect.slack.com/archives/C03RVH94K5K/p1703051164025719?thread_ts=1702956728.455579&cid=C03RVH94K5K).
cc @glitch-txs 
- chore: release v3.5.1
> chore(release): v3.5.1

- apps/laboratory/playwright.config.ts
- apps/laboratory/tests/shared/constants/index.ts
- apps/laboratory/tests/shared/fixtures/w3m-fixture.ts
- apps/laboratory/tests/shared/pages/ModalPage.ts
- dangerfile.ts
N/A
- feat(ui-tests): cover ethers
closes #...
> feat(ui-tests): cover ethers

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
> 3.6.0-alpha.1

- .vscode/settings.json
- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
- chore: version 3.5.2
closes https://github.com/WalletConnect/web3modal/issues/1653
> chore: v3.5.2

- packages/core/src/controllers/RouterController.ts
- packages/core/src/utils/RouterUtil.ts
N/A
- feat:
- fix: back button unresponsive after network switch
- chore:
> fix: back button unresponsive after network switch

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
- chore: releasing new version
> chore: update versions to 3.5.3

- .github/workflows/ui_tests.yml
- apps/laboratory/playwright.config.ts
Shoves ~30s off the test runtime by caching playwright.
- feat(ui-test): cache Playwright
closes #...
> feat(ui-test): cache Playwright

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- package-lock.json
- package.json
- packages/core/src/controllers/ConnectorController.ts
- packages/core/src/utils/ConstantsUtil.ts
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/scaffold/src/views/w3m-connect-view/index.ts
N/A
- fix: Deduplicate eip6963 wallets from connectors based on hardcoded map
- chore: Update dependencies
N/A
> fix: Deduplicate EIP6963 wallets from connectors

- apps/laboratory/tests/README.md
N/A
- feat:
- fix:
- chore:
closes #...
> feat(ui-test): improve readme

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
- Email flow UI/UX fixes and improvements
- Improve responsive styles for account and connect buttons
> chore: v3.6.0-0dbdeb8c

- .github/workflows/pr_checks.yml
- .github/workflows/ui_tests.yml
Enables other pipelines e.g. web3wallet web example wallet to run these tests.
Also fixes the lack of `concurrency` definition for the other tests.
N/A
- feat(ci): use reusable workflows
closes #...
> feat(ci): use reusable workflows

- package-lock.json
- packages/wagmi/package.json
N/A
- feat:
- fix:  restricted viem and wagmi to <v2
- chore:
> fix: restricted viem and wagmi to <v2

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
- Fixes `peerDependencies` for wagmi v1 now that v2 is released.
> chore: update to v3.5.5

- apps/laboratory/tests/README.md
- apps/laboratory/tests/shared/constants/index.ts
- dangerfile.ts
See README update for a description.
N/A
- feat(ui-test): make test subjects configurable
- fix:
- chore:
closes #...
> feat(ui-test): make test subjects configurable

- apps/laboratory/src/components/Ethers/EthersTransactionButton.tsx
- apps/laboratory/src/components/Wagmi/WagmiTransactionButton.tsx
- apps/laboratory/src/pages/library/wagmi-email.tsx
- packages/wallet/src/W3mFrameSchema.ts
- packages/wallet/src/W3mFrameTypes.ts
N/A
- feat:
- fix: wagmi email send transaction flow ui improvements
- chore:
> fix: send transaction flow fixes

- .github/workflows/pr_checks.yml
- .github/workflows/ui_tests.yml
- apps/laboratory/package.json
- apps/laboratory/playwright.config.ts
- dangerfile.ts
We want to run the connection tests exercising the wallet in the https://github.com/WalletConnect/web-examples pipeline.
This enables such endeavors: [sample run](https://github.com/WalletConnect/web-examples/actions/runs/7468930085/job/20325320013)
N/A
- feat(ui-test): allow to be used in remote repositories
closes #...
> feat(ui-test): allow to be used in remote repositories

- apps/laboratory/src/components/Siwe/SiweData.tsx
- apps/laboratory/tests/shared/validators/ModalValidator.ts
N/A
- fix(ui-tests): siwe tests broken after lab refactor
- fix:
- chore:
closes #...
> fix(ui-tests): siwe tests broken after lab refactor

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
- Ethers transactions fix on email connector.
- feat:
- fix: ethers transactions
- chore:
> chore:  v3.6.0-32bf236a

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/core/src/controllers/ConnectorController.ts
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
N/A
- feat:
- fix: sync dapp data when provider is undefined [no window]
- chore:
> fix: sync dapp data when provider is undefined [no window]

- apps/laboratory/src/components/Ethers/EthersTransactionTest.tsx
- package-lock.json
- packages/ethers/src/client.ts
- packages/wallet/src/W3mFrameConstants.ts
- packages/wallet/src/W3mFrameProvider.ts
N/A
- feat:
- fix: transactions not resolving due to race conditions on `eth_chainId` resolution.
- chore:
> fix: ethers-email transactions resolution

- package-lock.json
- packages/scaffold/src/partials/w3m-email-login-widget/styles.ts
- packages/scaffold/src/views/w3m-email-verify-otp-view/index.ts
- packages/ui/src/composites/wui-input-numeric/index.ts
- packages/ui/src/composites/wui-input-numeric/styles.ts
- packages/ui/src/composites/wui-input-text/styles.ts
- packages/ui/src/composites/wui-otp/index.ts
- packages/ui/src/composites/wui-snackbar/index.ts
- packages/ui/src/composites/wui-snackbar/styles.ts
- packages/ui/src/utils/ThemeUtil.ts
N/A
- feat:
- fix: email input spacings; wui-otp background and resend issues; icon-box color change
- chore:
Changes requested in https://www.figma.com/file/gmX3t1YIFLvXdKEwbeuqEW/Web3Modal-v3?node-id=14520%3A196097&mode=dev
> Fix/secure site UI review 3

- apps/gallery/package.json
- apps/laboratory/package.json
- apps/laboratory/src/components/Wagmi/WagmiTransactionTest.tsx
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
- Secure site type fix issues
- Loading indicators
- Alpha tag
- Generated avatar algorithm change
- feat:
- fix:
- chore: update to v3.6.0-1f872ccc
> chore: update to v3.6.0-1f872ccc

- .eslintrc.json
- apps/laboratory/tests/connect.spec.ts
- apps/laboratory/tests/siwe.spec.ts
N/A
- feat:
- fix: lint issues. Ignore coverage on lint
- chore:
> fix: lint issues. Ignore coverage in eslint

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
N/A
- feat:
- fix:
- chore: v3.5.7
> chore: bump to 3.5.7

- packages/scaffold/src/views/w3m-onramp-activity-view/index.ts
- packages/ui/src/composites/wui-onramp-activity-item/index.ts
N/A
- feat: add fungible token image if present, defaulting to current avatar.
- fix:
- chore:
- Complete activity page [#1788](https://github.com/WalletConnect/web3modal/issues/1788)
> feat: cbpay activity images

- .eslintrc.json
- .github/workflows/pr_checks.yml
- apps/laboratory/tests/connect.spec.ts
- apps/laboratory/tests/siwe.spec.ts
N/A
- feat:
- fix:
- chore: add V4 as a branch trigger for pr_checks
> fix: add V4 as a branch trigger for pr_checks

- apps/laboratory/src/pages/library/wagmi-email.tsx
- apps/laboratory/src/pages/library/wagmi-siwe.tsx
- apps/laboratory/src/pages/library/wagmi.tsx
- packages/wagmi/src/client.ts
N/A
- feat: remove `chains` param from web3modal config
- fix:
- chore:
Closes https://github.com/WalletConnect/web3modal/issues/1794
> feat: remove chains from web3modal config. use wagmi config ones

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/next-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
- Removes wagmi1 package
- Fix network sync issue on wagmiv2
- Fix connector sync issue on wagmiv2
- Fix SSR issues on wagmiv2
- Split hooks and config into different files in order to make server/client components work
- Add allWallets flag
- Fix activity image tearing
> chore: v4.0.0-alpha.1

- apps/laboratory/package.json
- apps/laboratory/src/pages/library/wagmi-email.tsx
- apps/laboratory/src/pages/library/wagmi-siwe.tsx
- apps/laboratory/src/pages/library/wagmi.tsx
- examples/react-wagmi/package.json
- package-lock.json
- packages/wagmi/src/client.ts
N/A
- feat:
- fix: connectors not being synced on init. Lab SSR support added and updated tanstack query version to support it.
- chore:
> fix: sync connector on init

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/next-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
N/A
- feat:
- fix:
- chore: v4.0.0-alpha.2
> Chore/v4.0.0 alpha.2

- apps/gallery/package.json
- apps/laboratory/package.json
- examples/html-ethers5/package.json
- examples/html-wagmi/package.json
- examples/next-wagmi/package.json
- examples/react-ethers5/package.json
- examples/react-wagmi/package.json
- examples/vue-ethers5/package.json
- examples/vue-wagmi/package.json
- lerna.json
- package-lock.json
- packages/common/package.json
- packages/core/package.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/polyfills/package.json
- packages/scaffold-react/package.json
- packages/scaffold-utils/package.json
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-vue/package.json
- packages/scaffold/package.json
- packages/siwe/package.json
- packages/ui/package.json
- packages/wagmi/package.json
- packages/wallet/package.json
- Adds cloud analytics events
- Fixes balance undefined issue
- Fixes issue on network switch when new chain was not configured
- feat:
- fix:
- chore: v.4.0.0-alpha.3
closes #...
> chore: v4.0.0-alpha.3

- apps/laboratory/src/pages/library/ethers.tsx
- apps/laboratory/src/pages/library/wagmi.tsx
N/A
- feat:
- fix:
- chore:
closes #...
> feat: added native example wallets deeplinks

- .github/workflows/ui_tests.yml
Doesn't [seem like this will fix our issue](https://github.com/actions/cache/releases/tag/v4.0.0) but still 
N/A
- feat:
- fix:
- chore:
closes #...
> feat(ui-test): upgrade github cache action from v3 to v4

- packages/wagmi/src/utils/defaultWagmiCoreConfig.ts
- packages/wagmi/src/utils/defaultWagmiReactConfig.ts
N/A
- feat: coinbase enableMobileWalletLink flag
- fix:
- chore:
fixes https://github.com/wevm/wagmi/pull/3549#issuecomment-1921819199
> feat: coinbase enableMobileWalletLink flag

- dangerfile.ts
- packages/scaffold-utils/src/ConstantsUtil.ts
- packages/scaffold-utils/tsconfig.json
- feat: `Constantsutil.version` will match package.json version of scaffold-utils
> auto update constantsutil version

- packages/scaffold/src/views/w3m-account-settings-view/index.ts
- packages/scaffold/src/views/w3m-account-view/index.ts
- packages/scaffold/tests/remove.spec.ts
Tests started failing and nobody noticed.
This fixes the broken tests.
Faster tests blocked on https://github.com/WalletConnect/web3modal/pull/1775 which @ganchoradkov is prioritizing shortly.
N/A
- feat:
- fix:
- chore:
closes #...
> fix(ui-test): tests not passing anymore

- apps/laboratory/.env.example
- apps/laboratory/tests/README.md
- Improve setup instructions based on the issues I bumped into on my end setting up the playwright tests
- Annotate the `.env.example` with where the required values can be looked up
> docs(tests): improve instructions for local playwright setup

- packages/scaffold/src/views/w3m-onramp-activity-view/index.ts
- packages/scaffold/src/views/w3m-onramp-activity-view/styles.ts
- packages/ui/src/composites/wui-onramp-activity-item/index.ts
N/A
- feat:
- fix: onramp activity failed status icon
- chore:
> fix: onramp activity status and refetch

- apps/laboratory/package.json
- examples/next-wagmi/package.json
- examples/react-wagmi/package.json
- package-lock.json
N/A
- feat:
- fix:
- chore: update examples and lab to wagmi 2.5.6
closes #...
> chore: update wagmi deps to 2.5.6

- .github/workflows/clear_cache.yml
N/A
- feat: add workflow to clear gh cache on pr close
- fix: 
- chore:
> feat: add workflow to clear gh cache on pr close

- package-lock.json
- packages/scaffold/src/views/w3m-account-view/index.ts
N/A
- chore: Revert change removing email button from account view in https://github.com/WalletConnect/web3modal/commit/3b0eafb71eeb61e123d5131ec34afcc13c83b5dd#diff-9c3fd97bc1e24b9d2685cc55b1c0122c114ab7f7b26460f8356e2b040b784e97L127
closes #...
> chore: Revert removal of email button in account view

- .changeset/dry-pots-prove.md
- .eslintrc.json
- .prettierignore
- examples/next-wagmi/src/app/layout.tsx
- examples/next-wagmi/src/config/index.ts
- examples/next-wagmi/src/context/index.tsx
N/A
- chore: `4.0.2` changeset
closes #...
> Prepare 4.0.2 changset

- package-lock.json
N/A
- chore: Update lockfile for `4.0.2`
closes #...
> chore: Update lockfile

- packages/scaffold/src/views/w3m-account-view/index.ts
N/A
- feat:
- fix: upgrade email wallet button copy
- chore:
> fix: upgrade wallet button copy

- package-lock.json
- packages/scaffold/src/views/w3m-onramp-activity-view/index.ts
- packages/ui/src/composites/wui-onramp-activity-item/index.ts
N/A
- feat:
- fix: show short date instead of time passed in onramp activity
- chore:
> fix: use short date instead of time from current date

- packages/core/src/controllers/TransactionsController.ts
- packages/scaffold/src/views/w3m-onramp-activity-view/index.ts
N/A
- feat:
- fix:
- chore:
closes #...
> fix: onramp transaction status group

- packages/core/package.json
- packages/core/src/controllers/ApiController.ts
- packages/core/src/controllers/TransactionsController.ts
- packages/core/tests/controllers/ApiController.test.ts
- packages/core/tests/controllers/AssetController.test.ts
- packages/core/tests/controllers/TransactionsController.test.ts
N/A
- feat: adds tests for ApiController
- fix:
- chore:
> feat: ApiController tests

- packages/ethers/src/client.ts
- packages/wagmi/src/client.ts
- packages/wallet/src/W3mFrameConstants.ts
- packages/wallet/src/W3mFrameHelpers.ts
Changed message we display to user when RPC call is not allowed and added a console log for developers with the exact call and detailed message.
> chore: update rpc not allowed message

- apps/laboratory/tests/shared/constants/browsers.ts
- apps/laboratory/tests/shared/utils/project.ts
N/A
- feat:
- fix:
- chore:
closes #...
> fix: brave os local path

- apps/laboratory/playwright.config.ts
- apps/laboratory/tests/email.spec.ts
- apps/laboratory/tests/shared/constants/devices.ts
- apps/laboratory/tests/shared/constants/index.ts
- apps/laboratory/tests/shared/fixtures/w3m-email-fixture.ts
- apps/laboratory/tests/shared/fixtures/w3m-fixture.ts
- apps/laboratory/tests/shared/fixtures/w3m-wallet-fixture.ts
- apps/laboratory/tests/shared/pages/DeviceRegistrationPage.ts
- apps/laboratory/tests/shared/pages/ModalPage.ts
- apps/laboratory/tests/shared/utils/actions.ts
- apps/laboratory/tests/shared/utils/email.ts
- apps/laboratory/tests/shared/utils/project.ts
- apps/laboratory/tests/shared/validators/ModalValidator.ts
- packages/scaffold/src/views/w3m-account-view/index.ts
- packages/scaffold/src/views/w3m-upgrade-wallet-view/index.ts
Fix email tests and expand email testing suite
> chore: refactor email tests

- dangerfile.ts
- packages/wallet/src/W3mFrameConstants.ts
Add warning when changing the secure site url
> chore: add warn on secure site url change

- packages/ethers/exports/index.ts
- packages/ethers5/exports/index.ts
- packages/wagmi/exports/index.ts
None
- feat: export Web3Modal type for all supported provider
https://github.com/orgs/WalletConnect/discussions/4333
> export Web3Modal type

- apps/laboratory/tests/canary.spec.ts
N/A
- fix(canary): test always reports success
- fix:
- chore:
closes #...
> fix(canary): test always reports success

- packages/scaffold/src/client.ts
N/A
- feat: Expose onRamp view type
> add onramp type to view

- package-lock.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/scaffold/package.json
- packages/wagmi/package.json
N/A
- feat:
- fix:
- chore:
closes #...
> add-siwe-as-dep

- packages/wallet/src/W3mFrameSchema.ts
N/A
- feat:
- fix:
- chore: inlclude optional `preferredAccountType` in frame response from GET_USER.
> chore: update frame schema to include optional preferredAccType response

- Dockerfile.canary
N/A
- chore: move canary variables into Dockerfile.canary
https://github.com/WalletConnect/rs-relay/pull/1518
> chore: move canary vars

- apps/laboratory/src/utils/ConstantsUtil.ts
> fix: mobile wallets links

- apps/laboratory/src/pages/index.tsx
- apps/laboratory/src/pages/library/ethers-all.tsx
- apps/laboratory/src/pages/library/wagmi-all.tsx
N/A
chore(lab): dogfooding button
> chore(lab): dogfooding button

- package-lock.json
- packages/ethers/package.json
- packages/ethers5/package.json
- packages/wagmi/package.json
N/A
- feat:
- fix:
- chore: updates ethereum-provider to latest
closes #...
> chore: updates ethereum-provider to latest

- packages/core/src/controllers/RouterController.ts
- packages/ethers/src/client.ts
- packages/scaffold/src/client.ts
- packages/scaffold/src/partials/w3m-header/index.ts
- packages/siwe/src/client.ts
- packages/wagmi/src/client.ts
N/A
- feat:
- fix:
- chore:
closes #...
> refactor: add replace option to tx router stack object

- packages/scaffold/src/partials/w3m-header/index.ts
N/A
- fix: issue where siwe and connectors screen would infinitely loop.
> fix: remove back on connecting siwe screen

- packages/core/tests/controllers/SwapController.test.ts
- packages/core/tests/utils/SwapCalculationUtil.test.ts
> fix: swap tests

- packages/siwe/src/client.ts
N/A
- feat:
- fix: close modal after declining siwe signature
- chore:
> fix: close modal on siwe cancel

- packages/scaffold/src/partials/w3m-header/index.ts
- packages/scaffold/src/partials/w3m-header/styles.ts
- packages/scaffold/src/views/w3m-approve-transaction-view/index.ts
- Fix the iframe positioning on the mobile screen
- Update header stylings and remove separator
> fix: iframe positioning on mobile view

- packages/siwe/scaffold/views/w3m-connecting-siwe-view/index.ts
- packages/siwe/src/client.ts
N/A
- feat:
- fix: siwe tests by leaving error catching in ui component where snackbar was being handled
- chore:
> fix: siwe tests

- apps/laboratory/package.json
- apps/laboratory/src/pages/library/ethers-siwe.tsx
- package-lock.json
- packages/scaffold/src/modal/w3m-modal/index.ts
- packages/scaffold/src/views/w3m-connecting-wc-view/index.ts
- packages/siwe/core/controller/SIWEController.ts
N/A
- feat:
- fix: issue where disconnecting from a 1CA session would cause siwe prompts on following connection requests. Fix wagmi connectors version
- chore:
> fix: 1CA disconnect issues

- Dockerfile.canary
N/A
- chore: UI canary 10 minute timeout
> chore: UI canary 10 minute timeout

- apps/laboratory/src/components/Wagmi/WagmiGetCallsStatusTest.tsx
- apps/laboratory/src/pages/library/wagmi-all.tsx
- apps/laboratory/src/pages/library/wagmi-email.tsx
- apps/laboratory/src/pages/library/wagmi-siwe.tsx
- apps/laboratory/src/pages/library/wagmi-wallet.tsx
- apps/laboratory/src/pages/library/wagmi.tsx
- apps/laboratory/src/utils/WagmiConstants.ts
N/A
- feat:
- fix: remove reference to wagmiConfig causing desync in modal initialization resulting in email connector not being setup
- chore:
closes #...
> fix: auth connector not showing in wagmi

- apps/laboratory/tests/shared/pages/ModalPage.ts
- fix: check if new email is visible at the end of the test
**Before:**
In the last step, the test checks if the account view is visible
**Now:**
-Check if the account view is visible again
-Check if the email in the account view is the new email
> fix: update-email test

- packages/common/src/utils/ConstantsUtil.ts
- packages/core/src/controllers/EnsController.ts
- packages/core/tests/controllers/EnsController.test.ts
- packages/scaffold/src/views/w3m-account-settings-view/index.ts
N/A
- feat:
- fix:
- chore: restrict names
> chore: restrict names

- packages/scaffold/src/views/w3m-register-account-name-view/index.ts
N/A
- feat:
- fix: issue where ens input would lose focus when loading suggestions.
- chore:
Closes APKT-300
> fix: ens input focus

- apps/laboratory/tests/canary.spec.ts
- chore: add canary for disconnect latency
[Slack conversation](https://walletconnect.slack.com/archives/C04DB2EAHE3/p1716939147711509)
> chore: add disconnect latency canary

- packages/wallet/src/W3mFrameProvider.ts
N/A
- feat:
- fix:
- chore:
closes #...
> fix: window cli error

- apps/laboratory/package.json
- package-lock.json
- package.json
- packages/solana/package.json
- turbo.json
N/A
- feat:
- fix: gallery build issues caused by `common` as devDependency on `ui` and not properly set at turbo build level
- chore:
> fix: gallery build issues

- packages/ethers5/src/client.ts
N/A
- feat:
- fix: issue where `eth_requestAccounts` was not being called on time for CB connector
- chore:
> fix: ethers5 requestAccounts

- packages/ethers/src/client.ts
- packages/ethers5/src/client.ts
N/A
- feat:
- fix: eip6963 connectors were being displayed even if not enabled in ethers
- chore:
> fix: issue where eip6963 connectors would still show with them disabled

- packages/solana/src/client.ts
- packages/solana/src/connectors/universalProvider.ts
- packages/solana/src/connectors/walletConnectConnector.ts
N/A
- feat:
- fix:
- chore:
closes #...
> fix reconnect flow

- apps/laboratory/src/components/RandomLink.tsx
- apps/laboratory/src/pages/index.tsx
The randomness is being executed at compile time. This makes the randomness execute in a client component.
- chore: fix random link
> chore: fix random link

- apps/laboratory/src/components/RandomLink.tsx
- feat:
- fix: remove error throwing as first render does not have href props ready
- chore:
> fix: laboratory hrefs

- apps/laboratory/src/components/RandomLink.tsx
N/A
- feat:
- fix: add default value and check before setting href
- chore:
> fix: add default value and check before setting href

- apps/laboratory/src/components/Web3ModalButtons.tsx
Hiding unpolished onramp widget from labs to prevent confusions and failed requests
> chore: remove onramp widget from labs

- apps/laboratory/public/.well-known/apple-app-site-association
Changed react-native sample universal links to avoid conflict with swift samples
> chore: changed react native universal links

- apps/laboratory/src/utils/ChainsUtil.ts
For Linear issues: Closes APKT-700
> chore: change labs' ethers rpc urls to walletconnect.org

- packages/wallet/src/W3mFrameConstants.ts
Updates the secure site url to its `.org` counterpart, enabling the service on restricted zones.
Closes APKT-583
> chore: update secure site url to org domain

- turbo.json
- Simplify turbo pipeline
- Remove unused pipeline tasks
- Fix issue with laboratory, gallery commands
> refactor: turbo pipeline

- apps/laboratory/tests/shared/validators/ModalValidator.ts
- apps/laboratory/tests/wallet.spec.ts
- packages/scaffold-ui/src/partials/w3m-account-default-widget/index.ts
> chore: disable onramp option for solana

- apps/laboratory/src/components/Solana/SolanaSignTransactionTest.tsx
Enables V0 transactions on Solana Lab
> chore: enable v0 tx on solana lab

- apps/laboratory/src/components/Ethers/EthersTransactionTest.tsx
- apps/laboratory/src/components/Wagmi/WagmiTransactionTest.tsx
Enable sending TXs on networks other than mainnet.
> chore: enable transaction button outside of mainnet

- apps/laboratory/next.config.js
- apps/laboratory/src/pages/library/ethers-all-internal.tsx
- apps/laboratory/src/pages/library/ethers-all.tsx
- apps/laboratory/src/pages/library/ethers-email.tsx
- apps/laboratory/src/pages/library/ethers-siwe.tsx
- apps/laboratory/src/pages/library/ethers.tsx
- examples/html-ethers5/src/main.js
- examples/react-ethers/src/App.tsx
- examples/react-ethers5/src/App.tsx
- examples/vue-ethers5/src/App.vue
- packages/ethers/src/utils/defaultConfig.ts
- packages/ethers5/src/utils/defaultConfig.ts
Removes references to unneeded Cloudflare ETH and other RPC URLs. [Slack conversation](https://walletconnect.slack.com/archives/C03RVH94K5K/p1721835331998519)
For Linear issues: Closes APKT-810
> chore: remove non-Blockchain API RPCs

- apps/demo/package.json
- apps/laboratory/package.json
- examples/html-wagmi/package.json
- examples/next-wagmi/package.json
- examples/react-wagmi/package.json
- examples/vue-wagmi/package.json
- packages/cdn/package.json
- packages/wagmi/package.json
- pnpm-lock.yaml
- Updates `wagmi`, `@wagmi/core` and `@wagmi/connectors` to latest versions
- Includes `ethereum-provider: 2.14.0` update in the wagmi connector
> chore: update wagmi dependencies to latest version

- apps/laboratory/playwright.config.ts
- We are trying to reduce flakyness and increase stability. Tests should be able to pass without multiple retries.
- Lowers retries to 1 on remote tests.
> chore: test single retry in tests

- packages/ethers/src/client.ts
- packages/wagmi/src/client.ts
Fixing issue with modal not get closed when issue on successful action.
> fix issue with modal not closing 

- apps/laboratory/public/.well-known/apple-app-site-association
Added production react native apps to apple app site association file
> chore: added rn samples in apple file

- apps/laboratory/public/.well-known/apple-app-site-association
Added Flutter universal links definitions to apple-app-site-association
> Added Flutter universal links

- apps/laboratory/src/layout/LayoutHeader.tsx
When route navigations happened the page URL wouldn't update. This fixes that...
> chore: fix page URL not updating

- apps/laboratory/public/.well-known/apple-app-site-association
> Change in flutter Universal Links paths

- packages/ethers/exports/index.ts
- packages/ethers/exports/react.tsx
- packages/ethers5/exports/react.tsx
- packages/solana/exports/index.ts
- packages/solana/exports/react.tsx
- packages/solana/exports/vue.ts
- packages/wagmi/exports/index.ts
- packages/wagmi/exports/react/index.ts
- packages/wagmi/exports/vue.ts
Exports the AppKitOptions type definitions for the backwards compatible packages.
> chore: export appkit options

- apps/laboratory/public/.well-known/assetlinks.json
> Added Flutter android links to assetlinks

- apps/laboratory/public/.well-known/assetlinks.json
> Added entries on assetlinks for flutter wallet

- packages/base/adapters/evm/wagmi/client.ts
- packages/wagmi/package.json
- packages/wagmi/tests/adapter.test.ts
- packages/wagmi/tests/mocks/adapter.mock.ts
- packages/wagmi/tsconfig.json
- pnpm-lock.yaml
- Adding tests for wagmi adapter
> chore: fix wagmi not disconnecting and add adapter tests

- packages/base/adapters/solana/web3js/client.ts
- packages/scaffold-utils/src/solana/SolanaConstantsUtil.ts
Change universal provider relay url and move to constants file.
> chore: change universal provider relay url and move to constants file

- .github/workflows/ui_tests.yml
- apps/laboratory/src/utils/ConstantsUtil.ts
- Updates workflow to use shared GH token
> chore: use shared gh token

- apps/laboratory/public/.well-known/apple-app-site-association
- apps/laboratory/public/.well-known/assetlinks.json
Changed links of React Native sample apps
> chore: changed android and ios links for react native sample apps

- apps/laboratory/public/.well-known/apple-app-site-association
Changed order of universal links
> chore: changed order of links

- apps/laboratory/public/.well-known/assetlinks.json
> chore: update assetlinks.json

- apps/laboratory/src/components/Solana/SolanaSendTransactionTest.tsx
- apps/laboratory/src/components/Solana/SolanaSignAllTransactionsTest.tsx
- apps/laboratory/src/components/Solana/SolanaSignAndSendTransactionTest.tsx
- apps/laboratory/src/components/Solana/SolanaSignJupiterSwapTest.tsx
- apps/laboratory/src/components/Solana/SolanaSignTransactionTest.tsx
- apps/laboratory/src/components/Solana/SolanaTests.tsx
This PR is allowing to test Solana transactions in mainnet using the laboratory. Mostly of the wallets only supports mainnet, restricting to devnet/testnet would not allow to test these wallets. 
> chore: allow laboratory solana tests on mainnet

- .changeset/brown-months-walk.md
- packages/wallet/src/W3mFrameSchema.ts
Makes `sdkVersion` value optional 
Trying to get a lab version with 5.1.8 running to test this but could take a bit
> chore: make sdkVersion header optional

- apps/laboratory/tests/multichain/multichain-wagmi-solana.spec.ts
- packages/adapters/solana/src/providers/AuthProvider.ts
- packages/core/src/controllers/ChainController.ts
- packages/core/src/controllers/ConnectionController.ts
- packages/core/src/controllers/NetworkController.ts
> fix: revert tests only changes

- packages/appkit-utils/package.json
- pnpm-lock.yaml
Adding `@walletconnect/logger` package to `@reown/appkit-utils`. This will unblock other PR's so they'll be able to check bundle size in main branch.
> chore: add `@walletconnect/logger` to `@reown/appkit-utils`

- .changeset/strange-terms-switch.md
- packages/core/src/controllers/SwapController.ts
Updates amount calculation to not have floating numbers as a result. This breaks the Swap TX creation. 
> fix: remove floating numbers for swap

- apps/laboratory/next.config.mjs
- apps/laboratory/tests/multichain/multichain-ethers-solana-email-siwe.spec.ts
- apps/laboratory/tests/multichain/multichain-ethers-solana-siwe.spec.ts
- apps/laboratory/tests/multichain/multichain-ethers5-solana-email-siwe.spec.ts
- apps/laboratory/tests/multichain/multichain-wagmi-solana-email-siwe.spec.ts
- apps/laboratory/tests/multichain/multichain-wagmi-solana-siwe.spec.ts
- apps/laboratory/tests/siwe-email.spec.ts
- Makes SIWE tests validate de authentication on tests
> chore: expect unAuthenticated on siwe tests

- .changeset/two-ligers-flash.md
Adding changeset for this PR https://github.com/reown-com/appkit/pull/2945
> chore: changeset for multi-account / single account ui fix

- packages/base/adapters/solana/web3js/client.ts
- packages/base/adapters/solana/web3js/providers/WalletConnectProvider.ts
- packages/base/adapters/solana/web3js/providers/WalletStandardProvider.ts
- packages/scaffold-ui/src/partials/w3m-connecting-wc-browser/index.ts
- packages/scaffold-ui/src/views/w3m-connecting-wc-view/index.ts
Check for installed extensions in "All Wallets" list when using Solana Adapter.
> fix: v5 solana check installed extensions

- packages/adapters/solana/src/client.ts
- packages/adapters/solana/src/providers/WalletConnectProvider.ts
- packages/adapters/solana/src/providers/WalletStandardProvider.ts
- packages/scaffold-ui/src/partials/w3m-connecting-wc-browser/index.ts
- packages/scaffold-ui/src/views/w3m-connecting-wc-view/index.ts
This PR is adding the logic to check if a extension wallet is installed when using Solana.
> fix: check for installed extensions on all wallets list

- packages/core/src/controllers/NetworkController.ts
- packages/core/tests/controllers/NetworkController.test.ts
- packages/scaffold-ui/src/views/w3m-account-settings-view/index.ts
This PR is removing names for Solana chains on V5
For Linear issues: Closes APKT-1033
> fix: v5 remove names flow for solana

- packages/base/adapters/solana/web3js/client.ts
This PR fixes connecting state being kept when trying to use WC or Extension and close the modal while the connection is happening.
For Linear issues: Closes APKT-1043
> fix: v5 solana connect loading

- .changeset/green-kiwis-play.md
- packages/adapters/solana/src/client.ts
- packages/core/src/controllers/ConnectorController.ts
This PR fixes the issue with connectors not appearing when using Solana Adapter. It also adds a safety test for proxying connectors with valtio so won't prevent other connectors to be used.
For Linear issues: Closes APKT-1227
> fix: connectors not appearing on solana

- packages/experimental/package.json
- Fixes experimental package version
> fix: experimental package version

- .changeset/silver-geckos-repair.md
- examples/html-wagmi-cdn/index.html
- examples/html-wagmi-cdn/main.js
- examples/html-wagmi-cdn/package.json
- examples/html-wagmi-cdn/vite.config.js
- packages/cdn/lib/appkit.ts
- packages/cdn/lib/ethers.ts
- packages/cdn/lib/ethers5.ts
- packages/cdn/lib/solana.ts
- packages/cdn/lib/wagmi.ts
- packages/cdn/package.json
- packages/cdn/vite.config.ts
- packages/scaffold-ui/src/views/w3m-connecting-wc-view/index.ts
- pnpm-lock.yaml
Refactor our CDN package to properly export our modules for plan JS or other use cases (like WebGL). 
For Linear issues: Closes APKT-321, APKT-817, APKT-1232
> refactor: appkit packages cdn workaround

- scripts/inject-version.js
Update inject version script to avoid using `assert`. 
Related to https://github.com/reown-com/appkit/pull/3036
> chore: update inject-version script

- .changeset/giant-chairs-smile.md
- packages/adapters/ethers/package.json
- packages/appkit/exports/constants.ts
- pnpm-lock.yaml
> chore: revert wc types package on ethers adapter

- .changeset/config.json
- .github/workflows/ui_tests.yml
> chore: update old repo urls/refs

- apps/laboratory/next.config.mjs
- examples/next-wagmi-app-router/next.config.mjs
- examples/next-wagmi-pages-router/next.config.mjs
This PR fixes next.js build errors
> fix: build errors

- readme.md
> chore(deprecation): reflects deprecation status

- apps/laboratory/tests/shared/constants/index.ts
Replacing secure site url so that email e2e tests are not failing
> chore: replace e2e secure site url 

- .changeset/lucky-guests-try.md
- packages/adapters/wagmi/src/client.ts
- packages/appkit/exports/constants.ts
setStatus for WalletConnect connector on syncAccount
> fix:setStatus for WalletConnect connector on syncAccount

- apps/laboratory/src/pages/library/ethers5.tsx
- apps/laboratory/src/pages/library/solana.tsx
- apps/laboratory/src/pages/library/wagmi.tsx
Remove custom social options from main wagmi/ethers/solana examples to list all social options.
> chore: enable all social options on lab

- apps/laboratory/src/utils/ConstantsUtil.ts
Adds Hedera network to laboratory pages
> chore: add hedera network to lab

- package.json
- packages/adapters/ethers/package.json
- packages/adapters/ethers5/package.json
- packages/adapters/polkadot/package.json
- packages/adapters/solana/package.json
- packages/adapters/wagmi/package.json
- packages/appkit-utils/package.json
- packages/appkit/package.json
- packages/common/package.json
- packages/core/package.json
- packages/experimental/package.json
- packages/scaffold-ui/package.json
- packages/ui/package.json
- packages/wallet/package.json
- pnpm-lock.yaml
- services/id-allocation-service/package.json
- Update dependencies from vulnerable versions. 
- Update vitest deps.
> chore: update dependencies from vulnerable versions. Update vitest deps.

- .changeset/tall-zebras-protect.md
- apps/laboratory/src/components/AppKitButtons.tsx
- apps/laboratory/tests/shared/pages/ModalPage.ts
- apps/laboratory/tests/wallet.spec.ts
- packages/core/exports/react.ts
- packages/core/exports/vue.ts
Adding `useDisconnect` hook for react and vue
For Linear issues: Closes APKT-1045
> feat: `useDisconnect` hook

- examples/vue-wagmi/package.json
- examples/vue-wagmi/src/App.vue
- examples/vue-wagmi/src/main.js
- examples/vue-wagmi/vite.config.js
- package.json
> refactor: wagmi vue example configs

- .changeset/silver-planes-draw.md
- examples/html-wagmi-cdn/index.html
- examples/html-wagmi-cdn/inject-cdn-version.js
- examples/html-wagmi-cdn/main.js
- packages/cdn/vite.config.ts
For our CDN users, it's better option to switch to ES build which is working in different use cases like WebGL as well. This PR introduces changes to CDN package configs and CDN example app
For Linear issues: Closes APKT-1295
> refactor: cdn configs for es build

- apps/laboratory/next.config.mjs
- apps/laboratory/src/utils/ConstantsUtil.ts
- apps/laboratory/tests/siwe-sa.spec.ts
- apps/laboratory/tests/smart-account.spec.ts
- packages/adapters/wagmi/src/connectors/AuthConnector.ts
- packages/ui/src/composites/wui-list-account/index.ts
- Updates unsupported network to use Uniswap Sepolia
For Linear issues: Closes APKT-1380
> chore: update unsupported network on sa tests

- packages/siwx/package.json
Manually set the `@reown/appkit-siwx` package in the correct version.
> chore: set siwx package in the correct version

- examples/vue-ethers5/vite.config.ts
- examples/vue-solana/src/App.vue
- examples/vue-solana/vite.config.ts
> refactor: remove env configs from vite settings

- .changeset/wet-bulldogs-move.md
- packages/appkit/exports/constants.ts
- packages/scaffold-ui/src/views/w3m-profile-view/index.ts
- packages/ui/src/composites/wui-list-account/index.ts
- Improves multi account ui for SAs
- Fix issue where wagmi would flake when switching to an unsupported network with new SS
- Moved switch to button before balance to prevent weird flicker
> chore: SA Multi-Account UI

- .github/workflows/publish_canary.yml
Adds `publish_canary` workflow to update canary image on every merge to main
> feat: re add publish canary workflow

- .changeset/clean-books-visit.md
- apps/laboratory/src/components/AppKitHooks.tsx
- packages/adapters/ethers/src/client.ts
- packages/adapters/ethers/src/tests/client.test.ts
- packages/adapters/ethers5/src/client.ts
- packages/adapters/ethers5/src/tests/client.test.ts
When usin
For Linear issues: Closes APKT-1411
**Before:**
https://github.com/user-attachments/assets/f43e5f0d-091a-4e86-a3f3-8bca6b00d6fc
**After:**
https://github.com/user-attachments/assets/4764b733-66ba-483a-ad8c-aaa2e919bf59
> fix: coinbase wallet not reconnecting (ethers/ethers5)

- Dockerfile.canary
[Slack conversation](https://reown-inc.slack.com/archives/C058RS0MH38/p1730921471632279?thread_ts=1730822730.844109&cid=C058RS0MH38)
> chore: fix canary BASE_URL

- examples/vue-ethers5/package.json
- examples/vue-solana/package.json
- examples/vue-wagmi/package.json
- packages/adapters/solana/package.json
- packages/appkit/exports/constants.ts
- packages/cdn/package.json
- pnpm-lock.yaml
- Sets a static TS version to prevent build issues
> fix: update ts to 5.3.3 across all packages

- apps/laboratory/src/pages/library/wagmi.tsx
Adds custom wallets to Wagmi example back
> chore: add custom wallets to wagmi examples

- .changeset/five-eels-camp.md
- packages/scaffold-ui/src/views/w3m-connect-view/styles.ts
Reduced scroll gradient effect from 140px to 40px.
> chore: improve scroll gradient effect

- apps/laboratory/next.config.mjs
- examples/vue-ethers-solana/package.json
- examples/vue-wagmi-solana/package.json
- pnpm-lock.yaml
Unifies ts versions to prevent build issues
> chore: unify ts versions on 5.3.3

- apps/gallery-new/components/gallery-container/index.ts
- apps/gallery-new/components/gallery-placeholder/index.ts
- apps/gallery-new/package.json
- apps/gallery-new/stories/assets/Icons.mdx
- package.json
- packages/ui-new/src/utils/ThemeUtil.ts
- pnpm-lock.yaml
Removed `@reown/appkit-ui` from gallery-new and added `build:gallery-new` script
> fix: appkit gallery styles not working

- apps/gallery-new/.storybook/preview.tsx
- apps/gallery-new/stories/composites/wui-tag.stories.ts
- apps/gallery-new/utils/PresetUtils.ts
- packages/ui-new/src/composites/wui-tag/index.ts
- packages/ui-new/src/composites/wui-tag/styles.ts
- packages/ui-new/src/utils/TypeUtil.ts
Adds new Tag component
For Linear issues: Closes APKT-1477
https://github.com/user-attachments/assets/f8162214-35b0-4d28-b093-2ecceac14c7d
> feat: tag component

- apps/laboratory/src/pages/library/bitcoin.tsx
- packages/adapters/bitcoin/src/connectors/SatsConnectConnector.ts
- packages/adapters/bitcoin/src/connectors/WalletStandardConnector.ts
- packages/adapters/bitcoin/src/utils/BitcoinConnector.ts
- Adds sats-connect transfers
- Makes BitcoinConnector implement base Provider class and make connectors implement it
> feat: implement transfers

- .changeset/lovely-cougars-count.md
- packages/appkit/src/tests/utils/HelpersUtil.test.ts
- packages/appkit/src/utils/HelpersUtil.ts
Fixes wrong case checking for deprecated chain id on solanaDevnet
> fix: wrong case checking for deprecated chain id on solanaDevnet

- readme.md
> feat(readme): add install size

- .changeset/polite-maps-relax.md
- apps/laboratory-new/package.json
- apps/laboratory/package.json
- packages/adapters/solana/package.json
- packages/appkit-utils/package.json
- pnpm-lock.yaml
Upgrades Web3.js version, with the recent vulnerability versions in mind, see:
- https://socket.dev/blog/supply-chain-attack-solana-web3-js-library
> chore: upgrade solana/web3.js library

- .changeset/young-bags-warn.md
- packages/core/src/utils/TypeUtil.ts
- packages/scaffold-ui-new/src/views/w3m-email-verify-otp-view/index.ts
- packages/scaffold-ui-new/src/views/w3m-update-email-primary-otp-view/index.ts
- packages/scaffold-ui-new/src/views/w3m-update-email-secondary-otp-view/index.ts
- packages/scaffold-ui/src/views/w3m-email-verify-otp-view/index.ts
- packages/scaffold-ui/src/views/w3m-update-email-primary-otp-view/index.ts
- packages/scaffold-ui/src/views/w3m-update-email-secondary-otp-view/index.ts
Pass error message to email otp verification error event
> refactor: add message to email otp error event

- .changeset/old-laws-brake.md
- packages/appkit/src/client.ts
- packages/core/src/controllers/ModalController.ts
- packages/core/src/controllers/OptionsController.ts
- packages/core/src/utils/ConstantsUtil.ts
- packages/core/src/utils/TypeUtil.ts
- packages/scaffold-ui/src/modal/w3m-modal/index.ts
- packages/scaffold-ui/src/modal/w3m-modal/styles.ts
- packages/scaffold-ui/src/partials/w3m-account-default-widget/index.ts
- packages/scaffold-ui/src/partials/w3m-account-wallet-features-widget/index.ts
- packages/scaffold-ui/src/partials/w3m-email-login-widget/index.ts
- packages/scaffold-ui/src/partials/w3m-social-login-list/index.ts
- packages/scaffold-ui/src/partials/w3m-social-login-widget/index.ts
- packages/scaffold-ui/src/partials/w3m-social-login-widget/styles.ts
- packages/scaffold-ui/src/partials/w3m-wallet-guide/index.ts
- packages/scaffold-ui/src/views/w3m-connect-view/index.ts
- packages/scaffold-ui/src/views/w3m-connect-view/styles.ts
- packages/scaffold-ui/src/views/w3m-connecting-external-view/index.ts
- packages/scaffold-ui/test/views/w3m-connect-view.test.ts
- pnpm-lock.yaml
Refactors AppKit UI and features to be customized for Builder project.
- Add new functions to the AppKit client to update enable/disable some features
- Add `embeddedMode` flag to do conditional page redirections for embedded mode, specifically for Builder project.
- Refactor connect view to conditionally render and sort connect methods
- Refactor account views to conditionally render and sort wallet features 
For Linear issues: Closes APKT-1664
> refactor: connect method and wallet features for customization and sorting features

- .changeset/twelve-rats-grin.md
- packages/scaffold-ui-new/src/partials/w3m-all-wallets-list-item/styles.ts
- packages/scaffold-ui/src/modal/w3m-modal/index.test.ts
- packages/scaffold-ui/src/modal/w3m-modal/index.ts
- packages/scaffold-ui/src/modal/w3m-modal/styles.ts
- packages/scaffold-ui/src/partials/w3m-all-wallets-list-item/styles.ts
- packages/ui/src/composites/wui-wallet-image/index.ts
- packages/ui/src/utils/ThemeUtil.ts
- Fixes for embedded mode to make sure connection status is behaving as same with modal version - for Builder app
- Improvement to UI for border radius transition
For Linear issues: Closes APKT-1682
https://github.com/user-attachments/assets/ed3db27b-f66f-4146-a11d-3d455b0935e6
> refactor: embedded mode state fix, add transition for border radius

- .changeset/grumpy-jeans-carry.md
- packages/adapters/solana/src/utils/handleMobileWalletRedirection.ts
Fixes URL parameter to encode for Phantom and Coinbase deeplinking structure to work properly.
For Linear issues: Closes APKT-1695
https://github.com/user-attachments/assets/1ead38f2-5352-488c-956e-651d8e6813af
> refactor: phantom deeplinking

- .changeset/bright-ads-relate.md
- .changeset/config.json
- .changeset/cyan-peaches-visit.md
- .changeset/eight-goats-search.md
- .changeset/grumpy-jeans-carry.md
- .changeset/lemon-coats-think.md
- .changeset/soft-eggs-glow.md
- .changeset/sour-berries-shout.md
- .changeset/swift-ladybugs-smile.md
- Removes builder changesets to prevent pipeline errors
- [] Approver of this PR confirms that the changes are tested on the preview link
> chore: remove builder changesets

- .changeset/young-goats-carry.md
Removes builder from changesets
> chore: remove builder config

- .changeset/warm-ligers-flow.md
> chore: rempve builder changeset

- apps/builder/components/branding-header.tsx
- apps/builder/providers/appkit-context-provider.tsx
- Fixes theme state sync between Demo app and AppKit
- Capitalizes the title on the sidebar on Demo app
> chore: set appkit theme at first render on demo

- .changeset/twenty-badgers-complain.md
- packages/adapters/ethers/src/client.ts
- packages/adapters/wagmi/package.json
- packages/adapters/wagmi/src/client.ts
- packages/adapters/wagmi/src/tests/client.test.ts
- packages/appkit/src/client.ts
> fix: wagmi connector not disconnecting

- .changeset/config.json
- .changeset/pink-trees-give.md
- packages/adapters/bitcoin/package.json
Makes `@reown/appkit-adapter-bitcoin` public
> chore: make bitcoin package public

- examples/parcel/package.json
Make exmaple private to prevent pipeline from getting stuck
> chore: make parcel example private to unblock Changesets pipeline

- .changeset/tall-carrots-jam.md
- packages/adapters/bitcoin/src/adapter.ts
- packages/adapters/bitcoin/tests/BitcoinAdapter.test.ts
- packages/adapters/bitcoin/tests/mocks/mockSatsConnect.ts
Add unit testing for Bitcoin adapter and fix unused default values.
> chore: bitcoin adapter unit testing

- examples/html-ethers/index.html
- examples/html-ethers/src/main.js
Updates html-ethers example to listen provider state and use for do actions.
> chore: update html-ethers example with provider usage

- .changeset/soft-mangos-deliver.md
- packages/appkit/src/tests/siwe.test.ts
- packages/core/src/utils/SIWXUtil.ts
Set connected wallet info when going to authenticate flow.
For Linear issues: Closes CLO-307
> fix: connected wallet info 1ca

- .changeset/beige-spiders-tell.md
- .changeset/chilly-schools-teach.md
- .changeset/config.json
- .changeset/fair-carrots-mix.md
- .changeset/great-wolves-cheer.md
- .changeset/late-suits-glow.md
- .changeset/nice-planes-smell.md
- .changeset/seven-shirts-act.md
- .changeset/smart-penguins-speak.md
- .changeset/soft-mangos-deliver.md
- apps/browser-extension/package.json
- examples/sveltekit-ethers/package.json
- packages/appkit/src/library/vue/index.ts
Fix Vue hooks to return Reactive values
> fix: vue hooks reactive values

- .changeset/sour-pigs-complain.md
- packages/adapters/solana/package.json
Updates `@solana/web3.js` to version 1.9.8
- Closes APKT-1838
> chore: update solana web3js

- .changeset/little-boats-help.md
> chore: remove invalid changeset

- .changeset/twelve-swans-bow.md
- apps/laboratory/src/components/AppKitInfo.tsx
- apps/laboratory/src/components/Ethers/Ethers5ModalInfo.tsx
- apps/laboratory/src/components/Ethers/EthersModalInfo.tsx
- apps/laboratory/src/components/Solana/SolanaModalInfo.tsx
- apps/laboratory/src/components/Wagmi/WagmiModalInfo.tsx
- packages/appkit/src/client.ts
- packages/appkit/tests/appkit.test.ts
- pnpm-lock.yaml
- `syncExistingConnection` was only being called for previously connected namespaces, causing non-connected namespaces to never get their status flag set as 'disconnected'
- Calls method on all namespaces. Internal disconnection handling is already taken care of by `syncNamespaceConnection`
> chore: fix status not being synced on all namespaces

- examples/nuxt-wagmi/package.json
- pnpm-lock.yaml
Nuxt example had non-existent version of AppKit
> fix: nuxt deps

- packages/scaffold-ui/src/partials/w3m-activity-list/index.ts
- packages/scaffold-ui/test/partials/w3m-account-activity-widget.test.ts
- packages/scaffold-ui/test/utils/HelpersUtil.ts
Added integration test for `w3m-account-activity-widget` view
For Linear issues: Closes APKT-1902
> chore: add test for `w3m-account-activity-widget`

- packages/scaffold-ui/test/partials/w3m-account-auth-button.test.ts
Added integration test for `w3m-account-auth-button` component
For Linear issues: Closes APKT-1903
> chore: add test for `w3m-account-auth-button`

- packages/scaffold-ui/src/partials/w3m-account-nfts-widget/index.ts
- packages/scaffold-ui/test/partials/w3m-account-nfts-widget.test.ts
Added integration test for `w3m-account-nfts-widget` component
For Linear issues: Closes APKT-1904
> chore: add test for `w3m-account-nfts-widget`

- .changeset/few-birds-speak.md
- packages/adapters/bitcoin/src/adapter.ts
- packages/adapters/bitcoin/tests/BitcoinAdapter.test.ts
- packages/adapters/bitcoin/tests/mocks/mockUniversalProvider.ts
Fix BitcoinAdapter `switchNetwork` function execution by keeping the Blueprint default implementation.
> fix: bitcoin adapter switch network

- .changeset/dull-turkeys-roll.md
- packages/appkit/src/client.ts
- packages/appkit/tests/appkit.test.ts
Fix condition for unsupported chain for `chainChanged` event on wallet connect event
For Linear issues: Closes APKT-1900
> fix: chain switch bug in appkit when using wallet on different

- .changeset/sweet-sloths-sneeze.md
- packages/scaffold-ui/src/partials/w3m-connecting-wc-qrcode/index.ts
- packages/scaffold-ui/test/partials/w3m-connecting-wc-qrcode.test.ts
> fix: remove duplicated basic button

- .changeset/plenty-colts-rush.md
- apps/laboratory/src/pages/library/multichain-basic.tsx
- packages/appkit/src/client.ts
- packages/core/src/controllers/BlockchainApiController.ts
- packages/core/src/controllers/OnRampController.ts
- packages/core/src/controllers/SwapController.ts
- Queries Blockchain api supported chains list endpoint on initialization
- Prevent calls on unsupported networks to blockchain api requests
> chore: add check for suported networks on blockchain api controller

- .changeset/tricky-spies-reply.md
- packages/common/index.ts
- packages/common/src/utils/ConstantsUtil.ts
- packages/common/src/utils/SafeLocalStorage.ts
- packages/core/src/controllers/EventsController.ts
- packages/core/tests/controllers/ApiController.test.ts
- packages/core/tests/controllers/EventsController.test.ts
- packages/core/vitest.config.ts
Added an alert error if the analytics event fails with a forbidden status.
For Linear issues: Closes APKT-2060
> chore: show alert error for forbidden analytics event

- apps/laboratory/next.config.mjs
See [Slack conversation](https://reown-inc.slack.com/archives/C03RVH94K5K/p1738093950773889?thread_ts=1737656831.626119&cid=C03RVH94K5K)
- x ] Chore (non-breaking change that addresses non-functional tasks, maintenance, or code quality improvements)
> chore: add cdn.zerion.io to CSP

- apps/laboratory/src/pages/api/auth/[...nextauth].ts
- packages/appkit-utils/exports/index.ts
- packages/siwe/core/helpers/index.ts
- packages/siwe/package.json
- packages/siwx/src/verifiers/EIP155Verifier.ts
- packages/siwx/tests/mocks/mockSession.ts
- packages/siwx/tests/verifiers/EIP155Verifier.test.ts
- pnpm-lock.yaml
Fixes issue verifying signature on SIWX for EIP155Verifier
> fix: siwx eip155 verifier faling with social logins

- .changeset/dull-toes-pay.md
- packages/common/src/utils/DateUtil.ts
- packages/experimental/src/smart-session/ui/views/w3m-smart-session-list-view/index.ts
- packages/scaffold-ui/test/partials/w3m-account-activity-widget.test.ts
- packages/ui-new/src/utils/TransactionUtil.ts
- packages/ui/src/utils/TransactionUtil.ts
> fix: get month name by index util method

- packages/appkit/tests/client/balance.test.ts
> chore: remove unnecessary account mock

- .changeset/wicked-peaches-sneeze.md
- packages/appkit/tests/client/balance.test.ts
- packages/core/src/utils/ConstantsUtil.ts
> chore: update meld key

- dangerfile.ts
- Adds danger rule checking for keys and secrets in the updated or created files
> chore: add danger rule to warn on keys

- packages/appkit/exports/constants.ts
- packages/appkit/src/client/core.ts
- Do not call Blockchain api supported-chains on initialization
For Linear issues: Closes APKT-2130
- [] I have tested my changes on the preview link
- [] Approver of this PR confirms that the changes are tested on the preview link
> chore: defer supported chains call

- examples/html-ak-basic-sign-client/src/main.js
- examples/html-ak-basic-up/src/main.js
- packages/appkit-new/src/client.ts
- packages/appkit/src/client/core.ts
- packages/appkit/tests/client/universal-adapter.test.ts
- packages/core/src/controllers/OptionsController.ts
- packages/scaffold-ui/src/views/w3m-connecting-wc-view/index.ts
- Adds `manualWCControl` flag to indicate connection is controlled externally
> Adds manualWCControl flag 

- apps/builder/app/layout.tsx
Updates Google Tag Manager id for Builder app
> chore: update gtag id for builder app

- examples/html-ak-basic/src/main.js
Fixed an issue where `useAppKitTheme` wasn't in sync
For Linear issues: Closes APKT-2201
> fix: `useAppKitTheme` doesn't have initial state

- apps/builder/app/layout.tsx
- apps/builder/lib/gtag.ts
> fix: google tag manager setup

- apps/laboratory/src/components/Wagmi/WagmiSendUSDCTest.tsx
- pnpm-lock.yaml
Display yellow insufficient warning when USDC input exceeds available balance
- Updated the UI to no longer disable the send button if the input is greater than the balance.
- Added a yellow warning icon and message to indicate that the amount entered exceeds available USDC.
> feat(WagmiSendUSDCTest): display yellow insufficient warning

- .changeset/rude-bulldogs-jam.md
- packages/appkit/src/client.ts
- packages/core/src/controllers/BlockchainApiController.ts
- packages/core/src/controllers/SwapController.ts
- packages/core/src/controllers/TransactionsController.ts
- packages/core/src/utils/FetchUtil.ts
- packages/core/src/utils/SwapApiUtil.ts
- packages/core/src/utils/TypeUtil.ts
- packages/core/tests/controllers/BlockchainApiController.test.ts
- packages/core/tests/controllers/TransactionsController.test.ts
- packages/core/tests/utils/SwapApiUtil.test.ts
- packages/scaffold-ui/src/views/w3m-buy-in-progress-view/index.ts
> chore: add sdk properties to ideintity request

- packages/appkit/src/client.ts
- packages/core/src/controllers/RouterController.ts
- packages/scaffold-ui/src/modal/w3m-modal/index.ts
- packages/scaffold-ui/src/views/w3m-network-switch-view/index.ts
return authProvider when using social/email
return universalProvider when using walletConnect
after every switch network, just close the modal (currently there is too much logic and if else with many edge cases)
> fix auth switch network issue

- apps/builder/lib/config.ts
- examples/next-ak-basic-app-router/src/context/index.tsx
- examples/next-wagmi-solana-bitcoin-app-router/src/context/index.tsx
Fixes metadata for Demo and some example apps
> chore: update metadata links

- packages/common/index.ts
- packages/common/src/utils/SystemUtil.ts
- packages/core/src/utils/ConstantsUtil.ts
- packages/scaffold-ui/src/utils/ConstantsUtil.ts
- packages/wallet-button/src/utils/ConstantsUtil.ts
- packages/wallet/src/W3mFrameConstants.ts
- Importing `SystemUtil` from a different module caused it to execute at runtime, which in turn results in `process` being `undefined`
- Removed `SystemUtil`
- Added manual checks on envvars across the code.
> chore: remove system util

- .changeset/gorgeous-timers-rescue.md
- packages/appkit/src/client/core.ts
- packages/appkit/tests/client/public-methods.test.ts
added new `getAccount` method in appkit core class
For Linear issues: Closes APKT-2376
> feat: add `appKit.getAccount` public method

- packages/experimental/src/smart-session/ui/permissions/wui-permission-contract-call/index.ts
- packages/experimental/src/smart-session/ui/views/w3m-smart-session-created-view/index.ts
- packages/experimental/src/smart-session/ui/views/w3m-smart-session-list-view/index.ts
Added missing core-ui imports in smart-sessions ui component
> chore: add missing core-ui imports in smart-sessions ui component

- Dockerfile.canary
Fixes the failing canary image builds. Example: https://github.com/reown-com/appkit/actions/runs/13769571346/job/38504525808
[Slack conversation](https://reown-inc.slack.com/archives/C03RVH94K5K/p1741626874509999?thread_ts=1741601093.363329&cid=C03RVH94K5K)
> fix: canary image build

- packages/appkit/tests/client/adapter-management.test.ts
- packages/appkit/tests/client/appkit-basic.test.ts
- packages/appkit/tests/client/balance.test.ts
- packages/appkit/tests/client/connection.test.ts
- packages/appkit/tests/client/initialization.test.ts
- packages/appkit/tests/client/listeners.test.ts
- packages/appkit/tests/client/public-methods.test.ts
- packages/appkit/tests/client/universal-adapter.test.ts
- packages/appkit/tests/client/walletconnect-events.test.ts
Updates global mocks to make sure they are not getting overridden by other tests
> chore: move global mocks to before each

- packages/appkit-utils/src/PresetsUtil.ts
Adds an icon for berachain.
Relates to DR-417
> chore(icons): add berachain icon

- packages/scaffold-ui/src/modal/w3m-router/styles.ts
- packages/scaffold-ui/src/partials/w3m-wallet-guide/index.ts
- packages/scaffold-ui/src/partials/w3m-wallet-guide/styles.ts
- Adds deleted padding on w3m-router
> chore: fix padding

- .changeset/cute-dingos-study.md
- .changeset/tricky-candies-fold.md
- apps/browser-extension/package.json
- apps/builder/package.json
- apps/laboratory/package.json
- examples/html-wagmi-cdn/src/main.js
- package.json
- packages/adapters/solana/package.json
- packages/appkit-utils/package.json
- patches/@changesets__assemble-release-plan@6.0.6.patch
- pnpm-lock.yaml
- Patches `changesets` prerelease management to add an optional chaining and prevent breakage in CI
For Linear issues: Closes APKT-2523
> chore: patch changesets prerelease management

- Dockerfile.canary
- Downgrades docker node version to node21
Closes APKT-2535
> chore: downgrade to node 21

- .changeset/wet-shoes-give.md
- packages/adapters/bitcoin/src/connectors/LeatherConnector.ts
- packages/adapters/bitcoin/tests/connectors/LeatherConnector.test.ts
- packages/adapters/bitcoin/tests/mocks/mockSatsConnect.ts
- Adds missing `+xml` to leather wallet icon
Closes APKT-1758
> Fix: leather icon

- .github/workflows/changesets.yml
- Exit prerelease mode before releasing canary
> chore: exit pre mode before publishing

- Dockerfile.canary
- Bumps node version to 22 on canary dockerfile
> chore: bump node version to 22 on canary dockerfile

- apps/laboratory/tests/shared/constants/index.ts
- apps/laboratory/tests/shared/pages/ModalPage.ts
- apps/laboratory/tests/shared/pages/WalletPage.ts
> chore: update sample wallet page log flow to not if already loaded before

- apps/laboratory/tests/shared/pages/WalletPage.ts
- Adds `waitForLoaded` after manually navigating on single address connection
- Increases timeout for uri component to be visible to 10s as 5s is the default.
> chore: add waitForLoadState, increase uri timeout

- packages/controllers/src/controllers/AccountController.ts
- packages/controllers/src/controllers/BlockchainApiController.ts
- packages/controllers/src/controllers/SwapController.ts
- packages/controllers/src/utils/TypeUtil.ts
- packages/controllers/tests/controllers/AccountController.test.ts
> Revert "Inwallet swap with chain abstracted balances"

- package.json
- patches/@changesets__assemble-release-plan@6.0.6.patch
- pnpm-lock.yaml
> chore: move patcheddependencies inside of pnpm directive in package.json

- packages/appkit/exports/constants.ts
- packages/appkit/src/adapters/ChainAdapterBlueprint.ts
- packages/controllers/src/controllers/SwapController.ts
- packages/controllers/src/utils/TypeUtil.ts
- packages/scaffold-ui/src/partials/w3m-swap-details/index.ts
- packages/scaffold-ui/test/views/w3m-swap-preview-view.test.ts
- Remove passing `gas` value for `eth_sendTransaction` call for swap transactions (allowance + swap )
- Remove Transaction cost element from preview swap screen.
Closes APKT-2572
> fix: appkit swap

- packages/adapters/bitcoin/src/adapter.ts
- packages/adapters/bitcoin/tests/BitcoinAdapter.test.ts
- packages/adapters/ethers/src/client.ts
- packages/adapters/ethers/src/tests/client.test.ts
- packages/adapters/ethers5/src/client.ts
- packages/adapters/ethers5/src/tests/client.test.ts
- packages/adapters/solana/src/client.ts
- packages/adapters/solana/src/tests/client.test.ts
- packages/adapters/wagmi/src/client.ts
- packages/adapters/wagmi/src/tests/client.test.ts
- packages/appkit/src/adapters/ChainAdapterBlueprint.ts
- packages/common/src/utils/ConstantsUtil.ts
> chore: add adapter type to bitcoin adapter

- apps/laboratory/app/library/multichain-no-adapters/page.tsx
- apps/laboratory/src/components/AppKitHooks.tsx
Currently there's no easy way to connect Solana/Bitcoin to AppKit Core. This changes that.
> feat(appkit-core): allows for easier testing of Solana and Bitcoin

- apps/laboratory/tests/siwe-email.spec.ts
[Slack conversation](https://reown-inc.slack.com/archives/C03RVH94K5K/p1743092972252349)
> chore: timingRecord for siwe email spec beforeAll

- apps/laboratory/tests/email.spec.ts
- apps/laboratory/tests/smart-account.spec.ts
> Revert "chore: avoids expecting a loader on socials tests"

- .github/workflows/pr_checks.yml
- .github/workflows/ui_tests.yml
- .gitignore
Currently a PR takes ~17mins for all tests to pass with the e2e UI tests being the slowest ones. Currently, if an e2e tests fails, a retry requires rebuilding the package which consumes ~5mins.
After this change e2e test retries are significantly faster and the overall test suite completes ~5minutes faster.
> feat(tests): speed up e2e tests & make them retryable

- packages/appkit-utils/src/PresetsUtil.ts
> feat(icons): add Abstract Mainnet

- packages/appkit-utils/src/PresetsUtil.ts
Used the wrong icon ..
now using the correct one https://github.com/reown-com/web-monorepo/pull/1893/files
> fix(icons): using correct icon for Abstract Network

- .changeset/loose-boxes-decide.md
- packages/adapters/bitcoin/exports/index.ts
- packages/adapters/bitcoin/package.json
- packages/adapters/bitcoin/tests/exports.test.ts
- pnpm-lock.yaml
Added `@reown/appkit-polyfills` for bitcoin
For Linear issues: Closes APKT-2607
> fix: bitcoin missing polyfills

- .github/workflows/ui_tests.yml
Currently we run the same test 5 times. This wastes time and resources.
> chore(tests): run canary only once

- .gitignore
- Pre-emptively setting `.envrc` files to be ignored
- See: https://docs.devin.ai/onboard-devin/repo-setup#configuring-environment-variables
> chore: update .gitignore to include .envrc files

- .changeset/loose-readers-care.md
- packages/controllers/src/controllers/ApiController.ts
- packages/scaffold-ui/src/partials/w3m-connect-external-widget/index.ts
- packages/scaffold-ui/src/utils/ConnectorUtil.ts
- packages/scaffold-ui/test/partials/w3m-connect-external-widget.test.ts
Fixed issue where `safe` wagmi connector was not hidden when excluded
For Linear issues: Closes APKT-2314
> fix: `safe` wagmi connector not hidden when excluded

- .changeset/twelve-laws-fix.md
- packages/appkit/src/client/appkit-base-client.ts
- packages/appkit/tests/client/public-methods.test.ts
- packages/controllers/exports/react.ts
- packages/controllers/tests/hooks/react.test.ts
Fixed an issue where the username from the embedded wallet info wasn’t properly synchronized
For Linear issues: Closes APKT-2595
> fix: username is not properly in sync with `embeddedWalletInfo`

- apps/laboratory/tests/shared/pages/ModalPage.ts
> chore: improve e2e flakes by refactoring close behavior on playwright

- apps/laboratory/tests/siwe-email.spec.ts
- apps/laboratory/tests/siwe-sa.spec.ts
- packages/appkit/src/client/appkit.ts
- packages/controllers/src/controllers/PublicStateController.ts
- packages/wallet/src/W3mFrameHelpers.ts
- Only subscribe to `open` instead of full `PublicStateController`
> chore: improve siwe email flakes

- apps/laboratory/tests/siwe-email.spec.ts
Unidentified Race Condition. Was reproducible 100% of times for me locally. This fixes it.
> fix(e2e-tests): siwe-email test not resilient

- apps/laboratory/tests/multichain/multichain-ethers5-solana-email-siwe.spec.ts
Makes siwe-email test more resilient against flakes.
> fix(tests): siwe test not resilient

- apps/laboratory/tests/siwe-sa.spec.ts
Fixing another case where tests might break because of timeouts.
> fix(e2e-tests): siwe-sa test not resilient

- .changeset/wicked-wombats-feel.md
- packages/scaffold-ui/src/partials/w3m-connect-injected-widget/index.ts
- packages/scaffold-ui/src/utils/ConnectorUtil.ts
- packages/scaffold-ui/test/partials/w3m-connect-injected-widget.test.ts
- packages/scaffold-ui/test/partials/w3m-connector-list.test.ts
Fixed an issue where custom connectors weren't showing on mobile
For Linear issues: Closes APKT-2136
> fix: custom connectors not showing on mobile

- .github/workflows/ui_tests.yml
- apps/laboratory/package.json
- apps/laboratory/tests/multichain/multichain-ethers-solana-email-siwe.spec.ts
- apps/laboratory/tests/multichain/multichain-wagmi-solana-email-siwe.spec.ts
> [DO NOT MERGE] feat: playwright cache

- .github/workflows/ui_tests.yml
* uses more shards to speed up test runs
* uses turbocache which in some cases results in faster builds
> chore(e2e-tests): run in more shards & leverage turbocache

- .github/workflows/pr_checks.yml
- package.json
- turbo.json
configures Turbocache. Not clear why this was disabled prior.
On cache hits this takes the build time in the best case from a few minutes to a few seconds.
> chore(build): configure turbocache

- .github/workflows/pr_checks.yml
- .github/workflows/ui_tests.yml
Should speed up the CI by ~1mins in the average case.
Tested in several runs.
> chore(ci): cache NextJS

- apps/laboratory/src/utils/NetworkUtil.ts
- apps/laboratory/tests/email-after-farcaster.spec.ts
- apps/laboratory/tests/email.spec.ts
- apps/laboratory/tests/multichain-extension.spec.ts
- apps/laboratory/tests/multichain-siwe-extension.spec.ts
- apps/laboratory/tests/shared/pages/ModalWalletPage.ts
- apps/laboratory/tests/siwe-email.spec.ts
- apps/laboratory/tests/siwe-sa.spec.ts
- apps/laboratory/tests/smart-account.spec.ts
> chore: add failed network log tests

- apps/laboratory/tests/shared/pages/ModalPage.ts
- packages/scaffold-ui/src/partials/w3m-header/index.ts
> chore: remove header buffering

- .github/workflows/ui_tests.yml
> chore(ci): pass shards command differently

- .github/workflows/pr_checks.yml
- .github/workflows/ui_tests.yml
Use number of shards from the config
> chore: use just one shard for the secure site

- apps/laboratory/tests/shared/pages/ModalPage.ts
- packages/controllers/src/controllers/ModalController.ts
> DEBUG: fix enable playwright logs. Add open and close trace logs

- packages/controllers/src/controllers/ModalController.ts
> chore: remove  modalcontroller logs

- .github/workflows/ui_tests.yml
Replaces the `script - argument` order while running PW tests as the sharding script is not working as expected if provided before the test script
```sh
pnpm --shard=3/10 playwright:test
pnpm playwright:test --shard=3/10
```
> chore: update shard param

- .github/workflows/ui_tests.yml
- Save 2 CI minutes if workflow is executed from SS as demo and extension tests are not executed there.
> chore: remove Demo and Extension builds from secure site workflows

- .changeset/plain-houses-pull.md
- examples/vue-wagmi-solana/src/App.vue
- examples/vue-wagmi-solana/src/config.ts
- packages/controllers/src/controllers/ConnectionController.ts
- packages/controllers/tests/controllers/ConnectionController.test.ts
Fixed an issue where deep links on mobile were not working properly and refactored the vue wagmi project
For Linear issues: Closes APKT-2691
> fix: wc mobile deeplink and vue wagmi project

- .changeset/some-cobras-battle.md
- apps/laboratory/src/components/AppKitPay.tsx
- packages/pay/exports/index.ts
- packages/pay/exports/react.ts
- packages/pay/src/client.ts
- packages/pay/src/controllers/PayController.ts
- packages/pay/src/types/options.ts
- packages/pay/src/utils/AssetUtil.ts
- packages/pay/tests/controllers/PayController.test.ts
Change the interface to add asset metadata to the exchange fetching methods
> chore: add asset metadata for exchange fetch

- .changeset/tasty-buses-worry.md
- packages/scaffold-ui/src/partials/w3m-input-address/index.ts
- packages/scaffold-ui/test/partials/w3m-input-address.test.ts
- packages/scaffold-ui/test/views/w3m-wallet-send-view.test.ts
Fixes send flow address input where the current business logic is not handling the entered value as expected and also make unnecessary ENS call if the given address is valid address
https://github.com/user-attachments/assets/a8152c56-682e-4c85-8a91-5d4e1aef100f
> fix: send flow address input logics

- .changeset/forty-bears-attack.md
- apps/laboratory/src/components/AppKitPay.tsx
- packages/pay/src/ui/w3m-pay-view/index.ts
- packages/pay/src/utils/AssetUtil.ts
- packages/pay/tests/ui/w3m-pay-view.test.ts
- packages/pay/tests/utils/AssetUtil.test.ts
Add Solana in available Pay with Exchange Assets.
This also fixes an issue in the lab with asset configuration editing
Resolves PAY-28
> chore: enable solana pay with exchange

- .github/workflows/ui_tests.yml
- apps/laboratory/playwright-merge.config.ts
- apps/laboratory/playwright.config.ts
> feat(ci): upload consolidated playwright report

- .github/workflows/pr_checks.yml
- .github/workflows/ui_tests.yml
- readme.md
Uploads the Playwright reports to S3 so other tools can analyze its history.
> feat(ci): upload playwritght reports to S3 to enable historical analysis

- .changeset/wild-ideas-sing.md
Adds missing changeset for https://github.com/reown-com/appkit/pull/4375
> chore: add changeset

- .github/workflows/devin_docs_update.yml
* Successful GHA run from branch with "emulated" `chore: version packages` commit on `HEAD`: https://github.com/reown-com/appkit/actions/runs/15140944047
* E2E validation is [here](https://reown-inc.slack.com/archives/C08MKQ248SY/p1747753072661359) (Devin being triggered via the Slack webhook)
Introduces a new GitHub Actions workflow (`.github/workflows/devin_docs_update.yml`) designed to automate the process of triggering documentation updates.
**Workflow Details:**
*   **Trigger:** The workflow runs on pushes to the `main` and `test/devin-workflow-trigger` branches, specifically when the head commit message contains 'chore: version packages'.
*   **Action:**
*   It sends a detailed Slack notification into `#system-devin`
*   The notification prompts an analysis of the commit's impact …
> feat(ci): trigger devin on `chore: version packages`

- .changeset/young-lizards-cut.md
- packages/controllers/src/controllers/OnRampController.ts
- packages/controllers/tests/controllers/OnRampController.test.ts
- Adds `externalCustomerId` query param to meld url
> feat: meld externalCustomerId

- .changeset/ninety-parts-mix.md
- packages/controllers/src/controllers/ApiController.ts
- packages/controllers/tests/controllers/ApiController.test.ts
Ids where wrongly copied from explorer preventing Coinbase to be displayed and causing Solflare to show up while not supporting WC protocol in All Wallets view
Closes APKT-2789
> fix: wrong ids on filterWalletsByPlatform

- CONTRIBUTING.md
> feat(docs): create CONTRIBUTING.md

- .github/workflows/publish-prerelease.yml
- Adds workflow_dispatch to publish a canary from a branch
> chore: add workflow dispatch to publish canary

- apps/demo/package.json
- pnpm-lock.yaml
> chore: fix demo lockfile

- .changeset/config.json
> chore: update changeset config to fix package versions

- apps/laboratory/src/components/AppKitInfo.tsx
Adds wallet name and icon to lab's AppKitInfo comp
> chore: add wallet icon and name on lab

- .changeset/soft-geese-write.md
- apps/laboratory/tests/email-after-farcaster.spec.ts
- apps/laboratory/tests/email.spec.ts
- packages/appkit-utils/src/ErrorUtil.ts
- packages/appkit/exports/constants.ts
- packages/appkit/src/client/appkit-base-client.ts
- packages/appkit/src/utils/ConfigUtil.ts
- packages/appkit/tests/client/appkit-base-client.test.ts
- packages/appkit/tests/client/appkit-error-handling.test.ts
- packages/appkit/tests/utils/ConfigUtil.test.ts
- packages/common/src/utils/ConstantsUtil.ts
- packages/controllers/src/controllers/AlertController.ts
- packages/controllers/src/controllers/EventsController.ts
- packages/controllers/src/controllers/SwapController.ts
- packages/controllers/tests/controllers/AlertController.test.ts
- packages/controllers/tests/controllers/EventsController.test.ts
- packages/scaffold-ui/src/partials/w3m-social-login-list/index.ts
- packages/scaffold-ui/src/partials/w3m-social-login-widget/index.ts
- packages/scaffold-ui/test/modal/w3m-modal.test.ts
Updates ErrorUtil to make sure each error has error code and updated the error messages.
> refactor: error messages

- apps/pay-test-exchange/app/api/status/route.ts
Remove KV get cache (default is 60s) in order to get instant data
> chore: remove KV get cache

- .github/workflows/release-prepare.yml
> fix: workflow permissions

- packages/controllers/src/controllers/ApiController.ts
> chore: enable binance

- packages/appkit/exports/constants.ts
- packages/appkit/src/client/appkit.ts
- packages/controllers/src/controllers/ConnectionController.ts
- packages/controllers/src/controllers/EventsController.ts
- packages/controllers/src/utils/ConnectorControllerUtil.ts
- packages/controllers/src/utils/TypeUtil.ts
- packages/controllers/tests/controllers/EventsController.test.ts
- packages/scaffold-ui/src/partials/w3m-account-default-widget/index.ts
- packages/scaffold-ui/src/partials/w3m-connecting-wc-browser/index.ts
- packages/scaffold-ui/src/views/w3m-account-settings-view/index.ts
- packages/scaffold-ui/src/views/w3m-connecting-external-view/index.ts
- packages/scaffold-ui/src/views/w3m-connecting-farcaster-view/index.ts
- packages/scaffold-ui/src/views/w3m-connecting-social-view/index.ts
- packages/scaffold-ui/src/views/w3m-email-verify-otp-view/index.ts
- packages/scaffold-ui/src/views/w3m-unsupported-chain-view/index.ts
- packages/scaffold-ui/test/partials/w3m-connecting-wc-browser.test.ts
- packages/scaffold-ui/test/partials/w3m-default-account-widget.test.ts
> Revert "chore: add activeCaipNetworkId to all events"

- .github/workflows/release-start.yml
Release PR was based of the main branch, fixing the workflow so its based off the release branch.
> fix: start release pr branch

- packages/appkit/src/client/appkit-base-client.ts
- packages/appkit/tests/client/initialization.test.ts
> fix: wrong enabling condition for reown authentication

- .changeset/chatty-mammals-dance.md
> chore: add FFE changeset

- package.json
Updating `package.json` in order to match the license in `LICENSE.md`
> chore: update package.json to match LICENSE.md

- .changeset/thin-bees-ring.md
- packages/scaffold-ui/src/partials/w3m-header/index.ts
Replace "deposit from an exchange" to "deposit from exchange"
> chore: replace "deposit from an exchange" to "deposit from exchange" in header

- package.json
- packages/cli/index.js
- packages/cli/package.json
- packages/cli/utils.js
- packages/codemod/package.json
- packages/codemod/src/utils.js
- pnpm-lock.yaml
Removes chalk dependency. Chalk is not used in any of our production packages, just for the development purposed packages:
- `packages/codemod`
- `packages/cli`
> chore: remove chalk dep

- apps/laboratory/test-results.json
- apps/laboratory/tests/verify.spec.ts
- packages/appkit/exports/constants.ts
Adds a test that the full flow works even when Verify API is blocked.
[Conversation](https://www.notion.so/walletconnect/WalletConnect-D-DoS-Susceptibility-Mitigations-26c3a661771e8006a1fbe908a3f73c37?source=copy_link#26c3a661771e80cab701fe587ec492b0)
> chore: test behavior when Verify API is blocked

- .changeset/hip-pans-follow.md
- packages/adapters/wagmi/src/client.ts
- packages/adapters/wagmi/src/tests/client.test.ts
- packages/appkit/src/client/appkit-base-client.ts
- packages/controllers/src/controllers/OptionsController.ts
- packages/scaffold-ui/src/utils/ConnectorUtil.ts
- packages/scaffold-ui/test/utils/ConnectorUtil.test.ts
- Deprecate `enableWalletConnect` flag
Closes APKT-3752
> feat: deprecate disable wc flag

- packages/controllers/src/controllers/OptionsController.ts
> chore: update `sixw` prop jsdoc

- .github/workflows/pr_checks.yml
- .size-limit.js
- BUNDLE_SIZE_TRACKING.md
- package.json
- pnpm-lock.yaml
track/enforce `size-limit`
See `BUNDLE_SIZE_TRACKING.md` for how it works.
See https://github.com/reown-com/appkit/actions/runs/18273851220/job/52021613817?pr=5156
> feat(ci): track/enforce size-limit

- apps/laboratory/docker-canary.sh
Add playwright logs to CloudWatch output
> feat(canary): add playwright logs to CloudWatch output
